### ISSUE TITLE
Docker integration

### ISSUE THREAD

**Issue by xificurC** [linkedin/gobblin#1006]
Are there any plans to make gobblin docker-friendly? E.g. `gobblin-mapreduce` is starting MapReduce jobs through `${HADOOP_BIN}/hadoop jar ...`. In a typical docker environment I'd expect Hadoop's components to be scattered in separate containers and would therefore need to request the job through the network (as `${HADOOP_BIN}` is not on our host). Does that make any sense? I'm starting things out here and don't have a quite clean view of your architecture yet.

**Comment by sahilTakiar** [comment]
I believe there have been a few other users who have done this. Here are the relevant threads:

https://github.com/linkedin/gobblin/issues/900
https://github.com/linkedin/gobblin/issues/905

**Comment by xificurC** [comment]
Thanks @sahilTakiar , I saw those threads but still not quite sure how does gobblin fit in the architecture when looking at it from docker's perspective. Since there isn't much usage of it in this area I will fiddle with it a bit more and see what I come up with.

**Comment by abti** [comment]
Docker integration was added: https://github.com/linkedin/gobblin/pull/1308
