### ISSUE TITLE
Gobblin build fails due to javadoc parameter problem

### ISSUE THREAD

**Issue by nihavend** [linkedin/gobblin#1014]
According to **http://gobblin.readthedocs.io/en/latest/Getting-Started/** i had clone the gobblin project and execute ./gradlew clean build -x test command.

it has finished with error : javadoc: error - invalid flag: -qu²et

i realized that the file "javadoc.options" in path ...\gobblin\build\gobblin-api\tmp\javadoc contains a line that has the buggy encoded parameter "-quıet"

i tried to recover the problem by working on gradle codes, but unfortunately i could not success.

the file "javadoc.options"  is generated with buggy encoding. it is related with java lowercase method dependency to regional setting i guess

i disabled javadoc genereation as a workaround.

**Comment by chavdar** [comment]
i can't reproduce this. Are you sure you haven't accidentally modified
./build.gradle ?

The correct line is (line 567):

options.addStringOption('Xdoclint:none', '-quiet')


Try "git checkout build.gradle" and building again.

**Comment by hulagu** [comment]
It is related with regional setting, language and file encoding or with all i guess. It is not easy to reproduce.

I am sure :)

the line is does not have an effect on problem.

check the attached text....
[javadoc.options.txt](https://github.com/linkedin/gobblin/files/279965/javadoc.options.txt)

**Comment by chavdar** [comment]
I am unable to reproduce it. Here is what a fragment of the javadoc.options
file looks on my machine:

-link 'http://avro.apache.org/docs/1.7.7/api/java/'
-link 'https://dropwizard.github.io/metrics/3.1.0/apidocs/'
-linkoffline 'http://linkedin.github.io/gobblin/javadoc/0.6.2/gobblin-admin/'
'/Users/cbotev/projects/gobblin_github/build/gobblin-admin/docs/javadoc/'
-linkoffline 'http://linkedin.github.io/gobblin/javadoc/0.6.2/gobblin-api/'
'/Users/cbotev/projects/gobblin_github/build/gobblin-api/docs/javadoc/'
-linkoffline 'http://linkedin.github.io/gobblin/javadoc/0.6.2/gobblin-core/'
'/Users/cbotev/projects/gobblin_github/build/gobblin-core/docs/javadoc/'
-linkoffline '
http://linkedin.github.io/gobblin/javadoc/0.6.2/gobblin-hive-registration/'
'/Users/cbotev/projects/gobblin_github/build/gobblin-hive-registration/docs/javadoc/'
-linkoffline '
http://linkedin.github.io/gobblin/javadoc/0.6.2/gobblin-metrics/'
'/Users/cbotev/projects/gobblin_github/build/gobblin-metrics/docs/javadoc/'
-linkoffline '
http://linkedin.github.io/gobblin/javadoc/0.6.2/gobblin-metastore/'
'/Users/cbotev/projects/gobblin_github/build/gobblin-metastore/docs/javadoc/'
-linkoffline '
http://linkedin.github.io/gobblin/javadoc/0.6.2/gobblin-utility/'
'/Users/cbotev/projects/gobblin_github/build/gobblin-utility/docs/javadoc/'
-linkoffline '
http://linkedin.github.io/gobblin/javadoc/0.6.2/gobblin-rest-api/'
'/Users/cbotev/projects/gobblin_github/build/gobblin-rest-api/docs/javadoc/'
-linkoffline '
http://linkedin.github.io/gobblin/javadoc/0.6.2/gobblin-rest-server/'
'/Users/cbotev/projects/gobblin_github/build/gobblin-rest-server/docs/javadoc/'
-linkoffline '
http://linkedin.github.io/gobblin/javadoc/0.6.2/gobblin-rest-client/'
'/Users/cbotev/projects/gobblin_github/build/gobblin-rest-client/docs/javadoc/'
-linkoffline '
http://linkedin.github.io/gobblin/javadoc/0.6.2/gobblin-tunnel/'
'/Users/cbotev/projects/gobblin_github/build/gobblin-tunnel/docs/javadoc/'
-linkoffline '
http://linkedin.github.io/gobblin/javadoc/0.6.2/gobblin-config-client/'
'/Users/cbotev/projects/gobblin_github/build/gobblin-config-client/docs/javadoc/'
-linkoffline '
http://linkedin.github.io/gobblin/javadoc/0.6.2/gobblin-config-core/'
'/Users/cbotev/projects/gobblin_github/build/gobblin-config-core/docs/javadoc/'
-quiet
-windowtitle 'gobblin-runtime 0.6.2-531-g9e8f96c API'
'/Users/cbotev/projects/gobblin_github/gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java'
'/Users/cbotev/projects/gobblin_github/gobblin-runtime/src/main/java/gobblin/runtime/AbstractTaskStateTracker.java'
'/Users/cbotev/projects/gobblin_github/gobblin-runtime/src/main/java/gobblin/runtime/BaseLimiterType.java'
'/Users/cbotev/projects/gobblin_github/gobblin-runtime/src/main/java/gobblin/runtime/BoundedBlockingRecordQueue.java'
'/Users/cbotev/projects/gobblin_github/gobblin-runtime/src/main/java/gobblin/runtime/CountBasedLimiter.java'

I don't know where the strange character comes from. It is not from gobblin.

**Comment by hulagu** [comment]
Ok. I know that it is not generated by gobblin itself. It is a bug coming from gradle. At the end of the day, it is the blocker of gobblin build process for systems has the settings for locale Turkish.

1.You can say it is not our business solve it with gradle, 
or 
2. check your build process through gradle

Depends on you.

if we compare the lines we can see;

yours : 

'/Users/cbotev/projects/gobblin_github/build/gobblin-config-core/docs/javadoc/'
-quiet
-windowtitle 'gobblin-runtime 0.6.2-531-g9e8f96c API'

mine :
-link 'https://dropwizard.github.io/metrics/3.1.0/apidocs/'
-qu?et 
-windowtitle 'gobblin-api 0.6.2-526-g08ade59 API'

As you can see, the javadoc.options is a gradle generated file. For the non-turkish systems it works well. 

There is a famous bug with upperCase and lowerCase eg http://mattryall.net/blog/2009/02/the-infamous-turkish-locale-bug 

As of now; I solved the problem by disabling javadoc generation.

For couple of days i am debugging gradle code to find the bug but not solved yet :( I will work for some more time hope to success...

**Comment by chavdar** [comment]
Thanks for the explanation. We have had plans to upgrade to Gradle 2 for a
while which may or may not address this issue.

**Comment by hulagu** [comment]
:+1: 
Thanx...
