### ISSUE TITLE
State management changes to TaskState, DatasetSate and JobState broke arbitrary number of implementations of Source and Extractors

### ISSUE THREAD

**Issue by abti** [linkedin/gobblin#1022]
The changes to state management induced with this PR: https://github.com/linkedin/gobblin/pull/932 broke a few Source / Extractors. 

The job specific properties being read from WorkUnitState are not available in it anymore, and are now to be read from JobState; whereas any previous code references / implementation assumed that all were available via WorkUnitState

If you face this issue, use this workaround (instead of reading property directly from WorkUnitState, use this): 

```
// If WorkUnitState does not contains a property, it should be attempted to be fetched from JobState
private String readProp(String key, WorkUnitState workUnitState) {
    String value = workUnitState.getWorkunit().getProp(key);
    if (StringUtils.isBlank(value)) {
      value = workUnitState.getJobState().getProp(key);
    } 

    return value;
}
```

**Comment by sahilTakiar** [comment]
@abti is this related to https://github.com/linkedin/gobblin/issues/1065? If this is breaking all the JDBC extractors we probably need to fix this ASAP.

**Comment by abti** [comment]
@sahilTakiar yes this seems related
