### ISSUE TITLE
Enhance multi tenancy by adding quotas and queue

### ISSUE THREAD

**Issue by abti** [linkedin/gobblin#1041]
We need a story and implementation around quotas and queues in Gobblin for better multi tenancy

**Comment by sahilTakiar** [comment]
@abti care to share some more details :)

**Comment by abti** [comment]
Sure.  I will try to roughly describe the problem :) 

**Intro:** This is a bi-fold problem of queue / capacity distribution and rate limiting.

So far Gobblin has been run mostly in map-reduce mode, so we do not have any concept of queues  / capacity distribution and rate limiting built into Gobblin. We rely on platform to limit our compute power (further limited by queue capacity if any) and we utilize 100% of what is provided to us. 

**Rate limiting:** We have certain disconnected rate limiters in place shared by multiple threads in same JVM or within a mapper to limit call rates to sources / sinks. 
**Queue / capacity:** We do not have anything in standalone mode, and we rely on platform ie. Yarn / Hadoop schedulers / queues and run different jobs as different users to achieve pseudo queues / capacity distribution

However, this does not works very well:
**Rate limiting:** Multiple mappers hitting same source or multiple jobs on same platform hitting same source (such as a REST API endpoint or Hive metastore) can either bring down the source OR starve certain mappers or jobs over others OR get the jobs blacklisted by source. So we need a global rate limiting system
**Queues / capacity:** On similar lines, we need to introduce concept of queues and capacity distribution in Gobblin - which may not be so useful in map-reduce mode but is quite needed for standalone or cluster (yarn / aws) modes. This will ensure that in a multi-tenant cluster environment we can provide capacity guarantees and isolation to users and prioritize different jobs of different users as per their capacity and queue status. We can start to think about it very much on the lines of what Hadoop has today. 

I haven't thought much about it but: This system can even live outside of Gobblin and Gobblin only be a client of it or we can fully bake this into Gobblin. 

@shirshanka also had some thoughts around it. 

@shirshanka - do you also want to add anything here?
