### ISSUE TITLE
git describe --tags --always returns gobblin_0.6.2 not gobblin_0.7.0

### ISSUE THREAD

**Issue by sahilTakiar** [linkedin/gobblin#1042]
The `git describe --tags --always` returns `gobblin_0.6.2-[commitId]` rather than `gobblin_0.7.0-[commitId]` - even though the tag `gobblin_0.7.0` has been pushed and released to the master repo: https://github.com/linkedin/gobblin/tree/gobblin_0.7.0

I'm not sure why this is happening, but when users build Gobblin locally it creates a distribution `gobblin-distribution-0.6.2-[...].tar.gz` rather than `gobblin-distribution-0.7.0-[...].tar.gz`.

**Comment by sahilTakiar** [comment]
@chavdar do you have any idea why this is happening? I've tried to debug this, but I without much success.

All I have found out is that there is some difference between the `gobblin_0.7.0` tag and the `gobblin_0.6.2` tag:

The command `git show gobblin_0.7.0` returns:

```
tag gobblin_0.7.0
Tagger: Sahil Takiar <stakiar@linkedin.com>
Date:   Thu May 12 11:22:28 2016 -0700

Release 0.7.0

commit 3ab15950ad904fea84dde32bfd705c2b79a656dd
Author: Sahil Takiar <stakiar@linkedin.com>
Date:   Thu May 12 11:22:22 2016 -0700

    Release 0.7.0

diff --git a/CHANGELOG b/CHANGELOG
index 852bb0d..f12ee88 100644
--- a/CHANGELOG
+++ b/CHANGELOG
@@ -1,3 +1,138 @@
+GOBBLIN 0.7.0
+-------------
+
+Created Date: 05/11/2016
...
```

The command `git show gobblin_0.6.2` returns:

```
commit ffd0aa97210486ff54144f66f3426f47fd6b1e99
Merge: feec99e 116c79b
Author: Issac Buenrostro <issac.buenrostro@gmail.com>
Date:   Tue Feb 2 13:26:24 2016 -0800

    Merge pull request #653 from ibuenros/v0.6.2

    V0.6.2

```

**Comment by abti** [comment]
I just tried to look around a bit for this, and stumbled upon this:
http://stackoverflow.com/questions/4154485/git-describe-ignores-a-tag

If I am reading it correctly, it resembles to what OP faced in the thread
above:
[abtiwari@abtiwari-mn1 ~/Work/temp/gobblin] 10:10:09 $ git show
gobblin_0.6.2
commit ffd0aa97210486ff54144f66f3426f47fd6b1e99
Merge: feec99e 116c79b
Author: Issac Buenrostro <issac.buenrostro@gmail.com>
Date:   Tue Feb 2 13:26:24 2016 -0800

    Merge pull request #653 from ibuenros/v0.6.2

    V0.6.2

[abtiwari@abtiwari-mn1 ~/Work/temp/gobblin] 10:10:12 $ git show
gobblin_0.7.0
tag gobblin_0.7.0
Tagger: Sahil Takiar <stakiar@linkedin.com>
Date:   Thu May 12 11:22:28 2016 -0700

Release 0.7.0

commit 3ab15950ad904fea84dde32bfd705c2b79a656dd
Author: Sahil Takiar <stakiar@linkedin.com>
Date:   Thu May 12 11:22:22 2016 -0700

    Release 0.7.0

I tried:
git tag -fa -m "Release 0.7.0" gobblin_0.7.0
3ab15950ad904fea84dde32bfd705c2b79a656dd

.. but that didn't make any difference either

Abhishek

**Comment by lbendig** [comment]
For me dropping and recreating the annotation was the only solution:

```
user@home:~/gobblin$ git --version
git version 2.8.0
user@home:~/gobblin$ git checkout cec3398fb6d7caf00e00db209ab5efe1c744ee78
user@home:~/gobblin$ git tag -d gobblin_0.7.0
user@home:~/gobblin$ git push origin :refs/tags/gobblin_0.7.0
user@home:~/gobblin$ git tag -a -m "Release 0.7.0" gobblin_0.7.0
user@home:~/gobblin$ git push origin gobblin_0.7.0
user@home:~/gobblin$ git cat-file -t gobblin_0.7.0
tag
user@home:~/gobblin$ git checkout master
user@home:~/gobblin$ git rev-parse HEAD
4f3bb7b0a26d85f74a7c05c6abc28b9980f8c742
user@home:~/gobblin$ git describe --tags --always
gobblin_0.7.0-128-g4f3bb7b
```
