### ISSUE TITLE
FAILURE: Build failed with an exception.

### ISSUE THREAD

**Issue by LouisChang** [linkedin/gobblin#1061]
Hi,

I git clone the code and run
./gradlew clean build -PhadoopVersion=2.7.2, and then it gave me error saying Build failed with an exception.

Anyone can tell me what happened since I have no clue about those stuff.

**Comment by chavdar** [comment]
What is the exception?

**Comment by LouisChang** [comment]
Hi,

So if I do not add -x test to ignore the test case, my program will always
return me bugs saying it can/t be built successfully. I would say it is the
test case issue?

On Wed, Jun 22, 2016 at 2:00 AM, Chavdar Botev <notifications@github.com>
wrote:

> What is the exception?
>
> On Tue, Jun 21, 2016 at 5:10 PM, Sidi Chang <notifications@github.com>
> wrote:
>
> > Hi,
> >
> > I git clone the code and run
> > ./gradlew clean build -PhadoopVersion=2.7.2, and then it gave me error
> > saying Build failed with an exception.
> >
> > Anyone can tell me what happened since I have no clue about those stuff.
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/linkedin/gobblin/issues/1061>, or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AA4sG0rSm9IqdCuFVqi1A4zQyMf18x6hks5qOH11gaJpZM4I7SzO
> >
> > .
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/linkedin/gobblin/issues/1061#issuecomment-227651259>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEExOpnQYWxQ163rK_DuqgENgtrqlTUOks5qOM99gaJpZM4I7SzO>
> .
>



-- 
Sidi CHANG
Master in Computer Science (Computational Operations Research Track)
College of William and Mary
Williamsburg, VA, United States

**Comment by LouisChang** [comment]
As following:
gobblin.metastore.DatabaseJobHistoryStoreV100Test.setUp FAILED
    com.wix.mysql.exceptions.MissingDependencyException

15 tests completed, 1 failed, 10 skipped
:gobblin-metrics:test FAILED

**Comment by chavdar** [comment]
Is it always the above failure?

**Comment by LouisChang** [comment]
Yep, if I do not add -x test. It can build if I add -x test.

On Thursday, June 23, 2016, Chavdar Botev <notifications@github.com> wrote:

> Is it always the above failure?
>
> On Wed, Jun 22, 2016 at 6:35 PM, Sidi Chang <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > As following:
> > gobblin.metastore.DatabaseJobHistoryStoreV100Test.setUp FAILED
> > com.wix.mysql.exceptions.MissingDependencyException
> >
> > 15 tests completed, 1 failed, 10 skipped
> > :gobblin-metrics:test FAILED
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/linkedin/gobblin/issues/1061#issuecomment-227926416
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AA4sG9ct5w22KZxI_qU9uD8HlYkfoP7eks5qOeLxgaJpZM4I7SzO
> >
> > .
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/linkedin/gobblin/issues/1061#issuecomment-227962410>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEExOool0p5-OWCYo-F-lYEXXDXNvvuVks5qOikhgaJpZM4I7SzO>
> .
>


-- 
Sidi CHANG
Master in Computer Science (Computational Operations Research Track)
College of William and Mary
Williamsburg, VA, United States

**Comment by sahilTakiar** [comment]
@LouisChang I would recommend just building without running the tests. If you want to run a specific test, there are ways in Gradle to just run a single test, or a list of tests.

Any PR that gets created is built and fully tested on [Travis](https://travis-ci.org/). I would generally leave it to Travis to run all the tests.

**Comment by abti** [comment]
@LouisChang I hope @sahilTakiar answer helped you build successfully. For creating a PR for any specific module, you can always build and test within that module. That would not get affected by the test thats creating an issue for you at the moment. The comprehensive tests like Sahil mentioned would be run on Travis when you try to submit a PR. 

Closing this issue. Reopen if you have more questions or thoughts.
