### ISSUE TITLE
Findbugs issue with Gobblin build

### ISSUE THREAD

**Issue by geek311** [linkedin/gobblin#1137]
Hi
I am getting the following while trying to do ./gradlew build -x test

Any pointers on how to fix this?

:gobblin-runtime:findbugsMain FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':gobblin-data-management:compileJava'.
  
  > Compilation failed; see the compiler error output for details.
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by chavdar** [comment]
./build/gobblin-runtime/reports/findbugs/main.html should have more info.
