### ISSUE TITLE
Issues with gobblin-yarn.sh

### ISSUE THREAD

**Issue by watashiarc** [linkedin/gobblin#1144]
I am getting issues with running gobblin-dist/bin/gobblin-yarn.sh:

WARN [NativeCodeLoader] Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
WARN [ZKHelixAdmin] Root directory exists.Cleaning the root directory:/GobblinYarn
Exception in thread "main" java.net.ConnectException: Call From hostname/1.1.1.1 to 0.0.0.0:8032 failed on connection exception: java.net.ConnectException: Connection refused; For more details see:  http://wiki.apache.org/hadoop/ConnectionRefused
        at sun.reflect.GeneratedConstructorAccessor6.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at org.apache.hadoop.net.NetUtils.wrapWithMessage(NetUtils.java:783)
        at org.apache.hadoop.net.NetUtils.wrapException(NetUtils.java:730)
        at org.apache.hadoop.ipc.Client.call(Client.java:1410)
        at org.apache.hadoop.ipc.Client.call(Client.java:1359)
        at org.apache.hadoop.ipc.ProtobufRpcEngine$Invoker.invoke(ProtobufRpcEngine.java:206)
        at com.sun.proxy.$Proxy19.getApplications(Unknown Source)

Here are my configuration files:
# application.conf

gobblin.yarn.helix.cluster.name=GobblinYarn
gobblin.yarn.app.name=GobblinYarn
gobblin.yarn.app.master.memory.mbs=256
gobblin.yarn.initial.containers=2
gobblin.yarn.container.memory.mbs=512
gobblin.yarn.conf.dir="/home/username/gobblin-dist/conf/yarn"
gobblin.yarn.lib.jars.dir="/home/username/gobblin-dist/lib"
gobblin.yarn.app.master.files.local=${gobblin.yarn.conf.dir}"/log4j-yarn.properties,"${gobblin.yarn.conf.dir}"/application.conf,"${gobblin.yarn.conf.dir}"/reference.conf"
gobblin.yarn.container.files.local=${gobblin.yarn.app.master.files.local}
gobblin.yarn.job.conf.path=<path where Gobblin job configuration file are located>
gobblin.yarn.keytab.file.path="/home/username/keytab/file.keytab"
gobblin.yarn.keytab.principal.name=gobblin
gobblin.yarn.logs.sink.root.dir=/home/username/gobblin-dist/applogs

writer.fs.uri=${fs.uri}
state.store.fs.uri=${fs.uri}

writer.destination.type=HDFS
writer.output.format=AVRO
writer.staging.dir=${gobblin.yarn.work.dir}/task-staging
writer.output.dir=${gobblin.yarn.work.dir}/task-output

data.publisher.type=gobblin.publisher.BaseDataPublisher
data.publisher.final.dir=${gobblin.yarn.work.dir}/job-output
data.publisher.replace.final.dir=false

state.store.dir=${gobblin.yarn.work.dir}/state-store

qualitychecker.row.err.file=${gobblin.yarn.work.dir}/err

job.lock.enabled=false
job.lock.dir=${gobblin.yarn.work.dir}/locks
metrics.log.dir=${gobblin.yarn.work.dir}/metrics
task.status.reportintervalinms=1000
metrics.enabled=true
# reference.conf

gobblin.yarn.app.queue=default
gobblin.yarn.helix.cluster.name=GobblinYarn
gobblin.yarn.app.name=GobblinYarn
gobblin.yarn.app.master.memory.mbs=512
gobblin.yarn.app.master.cores=1
gobblin.yarn.app.report.interval.minutes=5
gobblin.yarn.max.get.app.report.failures=4
gobblin.yarn.email.notification.on.shutdown=false
gobblin.yarn.initial.containers=1
gobblin.yarn.container.memory.mbs=512
gobblin.yarn.container.cores=1
gobblin.yarn.container.affinity.enabled=true
gobblin.yarn.helix.instance.max.retries=2
gobblin.yarn.keytab.login.interval.minutes=1440
gobblin.yarn.token.renew.interval.minutes=720
gobblin.yarn.work.dir=/user/limandy/gobblin-yarn
gobblin.yarn.zk.connection.string=${zookeeper.connection.string}

localhost=hostname.org

fs.uri="hdfs://"${localhost}":8020"
zookeeper.connection.string=${localhost}":2181"

job.execinfo.server.enabled=false

**Comment by andytlim** [comment]
Is there a way to change the uri of the yarn resource manager?

A

**Comment by SamirPatni** [comment]
Hey this is a blocking issue. Request someone to take it up ASAP... 
I don't think there are any workarounds either. 

Please let me know if there are any ?

**Comment by andytlim** [comment]
Can someone let me know if I need to rebuild one of the jars in order to modify this?
