### ISSUE TITLE
 Rest API for triggering Jobs. 

### ISSUE THREAD

**Issue by dallaybatta** [linkedin/gobblin#1254]
I have raised a discussion here 
 https://groups.google.com/forum/#!topic/gobblin-users/8kGgFWt49QY
 I am raising an issue for it it too.

**Comment by chavdar** [comment]
Hi Shankar,

Currently, you can run Gobblin in standalone mode to poll a directory for
job files. Then, you can run a simple web server that uploads the job files
to a directory. Previously, Gobblin supported polling only local file
system for job files. In our latest release (0.8.0), we have added support
for polling any Hadoop file system (e.g. HDFS).

We are also working on some improvements on how jobs are launched which
will address directly your use case (uploading Jobs through a REST API) and
add support for other use cases such as creating/triggering jobs from Kafka
events. We hope to introduce those enhancements in our next release - 0.9.0.

Thanks.
