### ISSUE TITLE
statestore-checker does not work for DatasetState

### ISSUE THREAD

**Issue by pcadabam** [linkedin/gobblin#1261]
The gobblin statestore-checker fails to read the statestore jst files for jobs that use `datasetUrn` (`JobState.DatasetSet`).

`FsDatasetStateStore.getAll(String storeName, String tableName)` looks for `current.jst` file under the statestore/jobName directory. For jobs that use `DatasetState`, there are multiple current jst files. One for each dataset in the format `dataset-urn-current.jst`.
We need to read all the `*-currnet.jst` files and pass it to the json wirter.

Also update the wiki if needed https://github.com/linkedin/gobblin/blob/master/gobblin-docs/user-guide/Troubleshooting.md

**Comment by abti** [comment]
Fixed with https://github.com/linkedin/gobblin/pull/1323 
Thanks @agepati
