### ISSUE TITLE
Gobblin Docker Integration

### ISSUE THREAD

**Issue by sahilTakiar** [linkedin/gobblin#1307]
Create some basic Gobblin integration with Docker. Main idea is to run the Gobblin standalone service inside a Docker container. Created a new entry in the docs page called `Docker Integration` which explains everything in depth.

For Gobblin users familiar with Docker, should provide a good way to get Gobblin up and running quickly.

Docker images will be hosted on Docker Hub, I created a Gobblin group on Docker Hub to host the images https://hub.docker.com/u/gobblin/dashboard/ (I've already built and uploaded the images from the Dockerfile present in this PR). Any committers that want to be added to the group, just create an account on Docker Hub, send me your username and I will add you as an owner.

Related Issues:
#1006
#905
#900

**Comment by abti** [comment]
Great! Thanks @sahilTakiar My username is same as github at docker ( @abti ). Please add me too. 
I don't see the PR that you talk about in the description. Are you yet to send it?

**Comment by sahilTakiar** [comment]
@abti added you to the repos on Docker Hub

**Comment by abti** [comment]
This was merged here: https://github.com/linkedin/gobblin/pull/1308
