### ISSUE TITLE
NullPointerException thrown when wikipedia.pull content is empty

### ISSUE THREAD

**Issue by yukuai518** [linkedin/gobblin#1312]
Tried to follow the hello world tutorial (http://gobblin.readthedocs.io/en/latest/Getting-Started/#run-your-first-job). Due to a download issue, my wikipedia.pull config file was empty. The bin/gobblin-standalone.sh start command then failed due to a null pointer error in the starting phase.

**Comment by pcadabam** [comment]
Gobblin should fail gracefully with an error message describing the exact config key that was missing. In this case `job.name`.
