### ISSUE TITLE
Can MapReduce Compactor be improved to guarantee which one will be preserved when doing dedup?.

### ISSUE THREAD

**Issue by bit1129** [linkedin/gobblin#1315]
Hi,
I read from guide that MapReduce compactor can be used to deduplicate on all or certain fields of the records. For duplicate records, one of them will be preserved; there is no guarantee which one will be preserved.
I brief through the code of AvroKeyDedupReducer, and find the following code,
    for (AvroValue<GenericRecord> value : values) {
      this.outKey.datum(value.datum());
      numVals++;
    }
From the logic, if there are duplicating values,  the latter value will overwrite the former one, and the last one will eventually win.
I would ask, is it possible to provide a field such as timestamp to indicate which one to preserve, eg, the largest timestamp will win?

**Comment by bit1129** [comment]
Can someone take a look at this question?Thanks!

**Comment by abti** [comment]
That would need an enhancement: one way to approach it could be to specify 'comparator' field and order (asc or desc) via the config which is primitive type so that it can easily help order values if present; and hence improve upon the dedup process.
