### ISSUE TITLE
Unable to download more than 10 files using single work unit from sftp source

### ISSUE THREAD

**Issue by sidarthakarna** [linkedin/gobblin#1319]
We have a remote sftp source which generates huge number of files (>7000 per day) which we try to pull into our HDFS. We are running into OOM memory issues most likely due to issue mentioned in #623. 

To mitigate this, I tried to limit the number of work units  using _source.max.number.of.partitions_ to 50. Each work unit may now download about 140 files. This is causing "Channel cannot be opened" exception after downloading 10 files from each container and the job is retrying the same set of files again and again before failing the job. 

The culprit most likely is SfpFsHelper.getFileStream which does not close the channel once the stream read is completed. I fixed similar issue in #1267.  But, it is much trickier in this case as completing the input stream read has to be confirmed by the calling method. Any ideas to help resolve this issue?

**Comment by pcadabam** [comment]
I think the `InputStream` returned by `FsHelper` should be wrapped as `gobblin.source.extractor.extract.sftp.SftpLightWeightFileSystem.SftpFsFileInputStream` which closes the `Channel` when `InputStream.close()` is called. 

```
private static class SftpFsFileInputStream extends SeekableFSInputStream {

    private final Channel channel;

    public SftpFsFileInputStream(InputStream in, Channel channel) {
      super(in);
      this.channel = channel;
    }

    @Override
    public void close() throws IOException {
      super.close();
      this.channel.disconnect();
    }
  }
```

**Comment by pcadabam** [comment]
Created a pull request https://github.com/linkedin/gobblin/pull/1320

**Comment by sidarthakarna** [comment]
Thanks a lot @pcadabam. I will test it with these changes and comment on the results.

**Comment by sidarthakarna** [comment]
This fixed our issue. Thanks a lot @pcadabam

**Comment by pcadabam** [comment]
No problem. Thanks for reporting the issue. @ibuenros / @sahilTakiar / @ydai1124  anyone for this quick pr https://github.com/linkedin/gobblin/pull/1320 ?
