### ISSUE TITLE
JdbcWriter sets wrong property

### ISSUE THREAD

**Issue by chosh0615** [linkedin/gobblin#1322]
I have an issue when retrying JdbcWriter.

In the JdbcWriter, it appends FORK_BRANCH_ID_KEY property, but nowhere in the source code it is read as a list. I think it should be modified to use setProp method instead of appendToListProp method.

`this.state.appendToListProp(ConfigurationKeys.FORK_BRANCH_ID_KEY, Integer.toString(builder.branch));`

If I'm correct, I can make a pull request.

**Comment by abti** [comment]
@jinhyukchang Do you have a quick answer for this?

**Comment by jinhyukchang** [comment]
@chosh0615 Thanks for pointing it out. Could you make a pull request?

**Comment by abti** [comment]
PR merged, this issue is fixed.
