### ISSUE TITLE
Kafka-HDFS-Ingestion: Manually set partition offsets

### ISSUE THREAD

**Issue by fixje** [linkedin/gobblin#1334]
We are running Gobblin to ingest data from Kafka 0.8.2 to HDFS. Kafka is configured with a retention period of 30 days. At peak times one of hour topics needs to store 35000 records/s which are distributed over 6 partitions.

 It sometimes happens that partition offsets are out of range. The `nearest` option for `reset.on.offset.out.of.range` doesn't do a good job as Gobblin still fetches data from more than two weeks ago. This run takes forever as it only reads ~30k records/s from each partition which is 1/6 of our peak input rate.

Is there a possibility to circumvent this problem at all?
Given, I know the partition offset where I want Gobblin to start consuming, how to get this into the state store?

Here is the job config:

```
job.name=OpenSkyModeS2Hdfs
job.group=OpenSkyKafka
job.description=OpenSky ModeS Kafka to HDFS
job.lock.enabled=true
## specifies custom Extractor
source.class=org.opensky.gobblin.ModeSKafkaSource

extract.namespace=opensky.extract.kafka.modes

## Base Settings
# final job output
data.publisher.final.dir=/user/opensky/raw/

# full = publish data only if everything was fine
job.commit.policy=full

# Kafka setting
kafka.brokers=kafka2-1:9092,kafka2-2:9092,kafka2-3:9092,kafka2-4:9092
topic.whitelist=ads-b.mode-s

# "null" = no compression, "deflate", "snappy"
writer.codec.type=deflate
writer.builder.class=gobblin.writer.AvroDataWriterBuilder
# temporary output path
writer.file.path.type=tablename
writer.destination.type=HDFS
writer.output.format=AVRO

writer.partitioner.class=org.opensky.gobblin.TimeAtServerPartitioner
writer.partition.pattern=yyyy/MM/dd/HH
writer.partition.timezone=UTC
writer.partition.granularity=HOUR

data.publisher.type=gobblin.publisher.TimePartitionedDataPublisher

mr.job.max.mappers=6
mr.job.root.dir=${env:GOBBLIN_WORK_DIR}/working

metrics.reporting.file.enabled=true
metrics.log.dir=${env:GOBBLIN_WORK_DIR}/metrics
metrics.reporting.file.suffix=txt

# HDFS setting, store everything there
fs.uri=hdfs://hadoop-3:8020
writer.fs.uri=${fs.uri}
state.store.fs.uri=${fs.uri}

# ${env:GOBBLIN_WORK_DIR} default is /user/opensky/gobblin-kafka
state.store.dir=${env:GOBBLIN_WORK_DIR}/state-store
task.data.root.dir=${env:GOBBLIN_WORK_DIR}/task-data
job.lock.dir=${env:GOBBLIN_WORK_DIR}/locks
```

**Comment by abti** [comment]
At the moment there is no easy way to modify the state. However, the state files are sequence files, so you can write a script that can inspect and modify the state to do that. Offset for Kafka is set as watermark. 
Alternatively, you can change KafkaSource or your custom Kafka source: ModeSKafkaSource to accept offset via job config and override the watermark based offset. 
If you end up writing a script or modifying the KafkaSource, please feel free to contribute back.

**Comment by fixje** [comment]
Thanks for your suggestions. The cleanliest solution imho is changing KafkaSource. I'll send a PR when I got something.

**Comment by abti** [comment]
Thanks!

**Comment by lurenx** [comment]
I have tried to set the  ```lowWatermark``` and ```highWatermark``` in my own ```Extractor```, it works.

```public class GobblinSimpleExtractor extends KafkaExtractor<String, byte[]> {

    private static final Logger LOG = LoggerFactory.getLogger(GobblinSimpleExtractor.class);

    public GobblinSimpleExtractor(WorkUnitState state) {

        super(state);
        this.nextWatermark.set(0, (long) 0);
        this.highWatermark.set(0,20);
        LOG.info(
                String.format(
                    "Pulling partition  0 from offset %d to %d, range=%d",
                    this.nextWatermark.get(0),
                    this.highWatermark.get(0),
                    this.highWatermark.get(0) - this.nextWatermark.get(0)
                )
        );
        
    }

    @Override
    protected byte[] decodeRecord(MessageAndOffset messageAndOffset) throws IOException {
        return getBytes(messageAndOffset.message().payload());
    }

    public String getSchema() throws IOException {
        return this.topicName;
    }
}
```

The  ```nextWatermark```  is  the  ```lowWatermark``` in this time running , and  the  ```highWatermark``` is  the kafka highwatermark currently that the workunit get from kafka.


I think this method is  much  easier .
