### ISSUE TITLE
Misleading error message in gobblin.source.extractor.extract.jdbc.JdbcExtractor

### ISSUE THREAD

**Issue by fakeone** [linkedin/gobblin#1335]
Error messages in class gobblin.source.extractor.extract.jdbc.JdbcExtractor:
line 791 - "Failed to get schema from Mysql - Resultset has no record" - mentions MySQL, while this class isn't MySql specific.
The  same issue repeats for many times in this class.

**Comment by abti** [comment]
Thanks for reporting. Its fixed now.
