### ISSUE TITLE
Configuration converter.classes can't be loaded when there exist converter classes configurations for fork branches.

### ISSUE THREAD

**Issue by bq-zhou** [linkedin/gobblin#1358]
My pull file contains both converter.classes and converter.classes.0 configurations, and then I find the pre-fork converter did not work. By tracking log and source code, I find the converter.classes was not loaded from pull file. After reading source code of PullFileLoader.java and the com.typesafe.config, I find the configuration converter.classes will be removed where there exist configurations like converter.classess.xxx.

After viewing git history, I notices the code for loading configuration was refactored in gobblin_0.8.0 and I'm using gobblin_0.8.0, too.

**Comment by chavdar** [comment]
Hi,

Thank you for reporting this.

Can you point me to the place where you found that "converter.classes" is
being removed?

**Comment by bq-zhou** [comment]
gobblin.util.PullFileLoader is the class responsible for loading configuration. Following is the method loading config from java properties file:
private Config loadJavaPropsWithFallback(Path path, Config fallback) throws IOException {

    PropertiesConfiguration propertiesConfiguration = new PropertiesConfiguration();
    try (InputStreamReader inputStreamReader = new InputStreamReader(this.fs.open(path),
        Charsets.UTF_8)) {
      propertiesConfiguration.load(inputStreamReader);

      return ConfigFactory.parseMap(ImmutableMap.of(ConfigurationKeys.JOB_CONFIG_FILE_PATH_KEY,
          PathUtils.getPathWithoutSchemeAndAuthority(path).toString()))
          .withFallback(ConfigFactory.parseProperties(ConfigurationConverter.getProperties(propertiesConfiguration)))
          .withFallback(fallback);
    } catch (ConfigurationException ce) {
      throw new IOException(ce);
    }
  }

I find the object propertiesConfiguration contains all the key in pull file, but the method ConfigFactory.parseProperties will remove the key "converter.classes".

This is the API document of ConfigFactory.parseProperties, it maybe helpful. https://typesafehub.github.io/config/latest/api/com/typesafe/config/ConfigFactory.html#parseProperties-java.util.Properties-com.typesafe.config.ConfigParseOptions-

**Comment by chavdar** [comment]
Hi,

How are you starting your jobs? Are you using gobblin-standalone.sh or
gobblin.sh ?

Thanks.

**Comment by bq-zhou** [comment]
I use gobblin-standalone.sh to start it.

**Comment by chavdar** [comment]
Thanks for reporting this. We are testing a fix.

**Comment by chavdar** [comment]
Can you check if you still see the error with the latest version in github?

**Comment by abti** [comment]
@chavdar Was this fixed?

**Comment by bq-zhou** [comment]
I think it was fixed.

**Comment by abti** [comment]
@bq-zhou Thanks for confirming.
