### ISSUE TITLE
[Help Needed] Is there a way to set startOffset and endOffset in the job config file when pulling data from Kafka

### ISSUE THREAD

**Issue by jeffwang66** [linkedin/gobblin#1390]
Hi,

I am using Gobblin to pull data from Kafka. I just would like to ask if it is possible to set startOffset and endOffset for each Kafka partition in the job config file?

Also, I know Gobblin reads the state of previous run from the sequence file. Is there any utility to read and create such sequence file?

Thanks

**Comment by chavdar** [comment]
Hi,

Currently, there is no way to set offsets to explicit values although we
are considering adding this in the near future. You can specify starting
from the latest or earliest offset on the Kafka brokers. Another way to
control consumption is to keep previous states as checkpoints and recover
from them.

Could you describe your use case? Why do you need to start from specific
values?

Thanks.

**Comment by jeffwang66** [comment]
@chavdar 

Thanks for your quick reply. 

I am considering if there is any downtime of consumer side, but the producer application keeps sendings msgs to Kafka, could be better to let Gobblin only consumes a max number of msgs in each run, rather than reading entire messages from the topic?

Thanks

**Comment by chavdar** [comment]
How about a time limit on the consumption?

**Comment by jeffwang66** [comment]
Time limit is good as well.

**Comment by lurenx** [comment]
I have tried to set the  ```lowWatermark``` and ```highWatermark``` in my own ```Extractor```, it works.

```public class GobblinSimpleExtractor extends KafkaExtractor<String, byte[]> {

    private static final Logger LOG = LoggerFactory.getLogger(GobblinSimpleExtractor.class);

    public GobblinSimpleExtractor(WorkUnitState state) {

        super(state);
        this.nextWatermark.set(0, (long) 0);
        this.highWatermark.set(0,20);
        LOG.info(
                String.format(
                    "Pulling partition  0 from offset %d to %d, range=%d",
                    this.nextWatermark.get(0),
                    this.highWatermark.get(0),
                    this.highWatermark.get(0) - this.nextWatermark.get(0)
                )
        );
        
    }

    @Override
    protected byte[] decodeRecord(MessageAndOffset messageAndOffset) throws IOException {
        return getBytes(messageAndOffset.message().payload());
    }

    public String getSchema() throws IOException {
        return this.topicName;
    }
}
```

The  ```nextWatermark```  is  the  kafka ```lowWatermark``` in this time running , and  the  ```highWatermark``` is  the kafka highwatermark currently that the workunit get from kafka. 

So you can:

1.     write yourself define ```Extractor```
2.     set the ```lowWatermark``` and ```highwatermark``` for each partion in your ```kafka.pull```
3.     modify yourself define ```Extractor``` to change the  ```lowWatermark``` and ```highwatermark``` for some partition in ```state```
 
Maybe  this method is what you need .

**Comment by jeffwang66** [comment]
@lurenx Thanks. This is very helpful.

**Comment by abti** [comment]
Please reopen if still unresolved.
