### ISSUE TITLE
offset out of range 

### ISSUE THREAD

**Issue by lurenx** [linkedin/gobblin#1402]
```
18-11-2016 11:23:04 CST DumpKafka INFO - WARN Start offset for partition cachelog-huge-a:78 is out of range. Start offset = 0, earliest offset = 1702454011, latest offset = 1847203166.This partition will start from the earliest offset: 1702454011
18-11-2016 11:23:04 CST DumpKafka INFO - INFO Created workunit for partition cachelog-huge-a:78: lowWatermark=1702454011, highWatermark=1847203166, range=144749155
```

when gobblin check the watermark , i find the warn as above, what should i do to fix this warn without  lose data. 

Thank you

**Comment by ibuenros** [comment]
Hi,
I'm assuming this is the first time you run gobblin-kafka on that topic?
You will lose no data, it's just saying it found no watermark, so it will
start consuming from the beginning of the partition.
Issac

**Comment by lurenx** [comment]
this  is not the  first time,i have run the gobblin job for about a months.

**Comment by mwol** [comment]
Could it be, that you cannot catch up with the amount of incoming data?

**Comment by lurenx** [comment]
It‘s easy for gobblin to deal the  incoming  data. it may cost 15 mins to deal the one hour incoming data.

**Comment by ydai1124** [comment]
@lurenx , is this still an issue for you? @mwol is correct that failing to catch up with the incoming data can be one cause. You may want to try to tune some parameters for improving your ingestion speed.
