### ISSUE TITLE
WriterInitializerFactory should not depend on JdbcWriterBuilder or JdbcWriterCommandsFactory

### ISSUE THREAD

**Issue by shirshanka** [linkedin/gobblin#1432]
gobblin.writer.initializer.WriterInitializerFactory seems to depend explicitly on JDBC classes. 

if(JdbcWriterBuilder.class.getName().equals(writerBuilderClass)) {
      return new JdbcWriterInitializer(state, workUnits, new JdbcWriterCommandsFactory(), branches, branchId);
    }

@jinhyukchang : Can you propose a way to break this dependency? 

Also, this class should probably move to gobblin-runtime as I don't see any other class (other than AbstractJobLauncher) depending on this class.

**Comment by jinhyukchang** [comment]
Hi @shirshanka ,

I think we can make DataWriterBuilder provide its WriterInitializer where by default it will provide NO-OP writer initializer and JdbcWriterBuilder provides its own by overriding it. This will make it more generic and it makes sense to move it to gobblin-runtime.

Thoughts?
