### ISSUE TITLE
NullPointerException in GobblinMultiTaskAttempt 

### ISSUE THREAD

**Issue by Spracklen** [linkedin/gobblin#1447]
In my gobblin job I am using [KafkaSource](https://github.com/linkedin/gobblin/blob/6cc8335ee845460e7e0c1e37662f4a101b1ba69e/gobblin-modules/gobblin-kafka-08/src/main/java/gobblin/source/extractor/extract/kafka/KafkaSource.java) .  It creates a set of work units as follows:

2016-12-08 11:39:42 PST INFO  [pool-8-thread-11] gobblin.source.extractor.extract.kafka.KafkaSource  373 - Created workunit for partition s_browse_view:0: lowWatermark=1723      399, highWatermark=1723415, range=16
23196 2016-12-08 11:39:42 PST INFO  [pool-8-thread-8] gobblin.source.extractor.extract.kafka.KafkaSource  373 - Created workunit for partition s_pets_purchased:0: lowWatermark=67      9, highWatermark=679, range=0
23197 2016-12-08 11:39:42 PST INFO  [pool-8-thread-12] gobblin.source.extractor.extract.kafka.KafkaSource  373 - Created workunit for partition s_friend_request:0: lowWatermark=6      1, highWatermark=61, range=0
23198 2016-12-08 11:39:42 PST INFO  [pool-8-thread-1] gobblin.source.extractor.extract.kafka.KafkaSource  373 - Created workunit for partition s_payment:0: lowWatermark=143, high      Watermark=143, range=0
23199 2016-12-08 11:39:42 PST INFO  [pool-8-thread-4] gobblin.source.extractor.extract.kafka.KafkaSource  373 - Created workunit for partition s_meetme:0: lowWatermark=113, highW      atermark=113, range=0
23200 2016-12-08 11:39:42 PST INFO  [pool-8-thread-2] gobblin.source.extractor.extract.kafka.KafkaSource  373 - Created workunit for partition s_login_detail:0: lowWatermark=1030      6, highWatermark=10306, range=0
23201 2016-12-08 11:39:42 PST INFO  [pool-8-thread-9] gobblin.source.extractor.extract.kafka.KafkaSource  373 - Created workunit for partition s_photo_upload:0: lowWatermark=3994      , highWatermark=3994, range=0
23202 2016-12-08 11:39:42 PST INFO  [pool-8-thread-15] gobblin.source.extractor.extract.kafka.KafkaSource  373 - Created workunit for partition s_mail_send:0: lowWatermark=18, hi      ghWatermark=18, range=0
23203 2016-12-08 11:39:42 PST INFO  [pool-8-thread-14] gobblin.source.extractor.extract.kafka.KafkaSource  373 - Created workunit for partition s_mobile_activity:0: lowWatermark=      0, highWatermark=0, range=0
23204 2016-12-08 11:39:42 PST INFO  [pool-8-thread-3] gobblin.source.extractor.extract.kafka.KafkaSource  373 - Created workunit for partition s_login:0: lowWatermark=10282, high      Watermark=10282, range=0
23205 2016-12-08 11:39:42 PST INFO  [pool-8-thread-16] gobblin.source.extractor.extract.kafka.KafkaSource  373 - Created workunit for partition s_pinch_point:0: lowWatermark=21,       highWatermark=21, range=0
23206 2016-12-08 11:39:42 PST INFO  [pool-8-thread-6] gobblin.source.extractor.extract.kafka.KafkaSource  373 - Created workunit for partition s_gold:0: lowWatermark=561, highWat      ermark=561, range=0
23207 2016-12-08 11:39:42 PST INFO  [pool-8-thread-5] gobblin.source.extractor.extract.kafka.KafkaSource  373 - Created workunit for partition s_comment:0: lowWatermark=20, highW      atermark=20, range=0
23208 2016-12-08 11:39:42 PST INFO  [pool-8-thread-13] gobblin.source.extractor.extract.kafka.KafkaSource  373 - Created workunit for partition s_mess:0: lowWatermark=11951, high      Watermark=11951, range=0
23209 2016-12-08 11:39:42 PST INFO  [pool-8-thread-7] gobblin.source.extractor.extract.kafka.KafkaSource  373 - Created workunit for partition s_page_view:0: lowWatermark=1891895      3, highWatermark=18919164, range=211
23210 2016-12-08 11:39:42 PST INFO  [pool-8-thread-10] gobblin.source.extractor.extract.kafka.KafkaSource  373 - Created workunit for partition s_newsfeed:0: lowWatermark=12797,       highWatermark=12797, range=0
23211 2016-12-08 11:39:42 PST INFO  [pool-8-thread-3] gobblin.source.extractor.extract.kafka.KafkaSource  373 - Created workunit for partition s_login:1: lowWatermark=10044, high      Watermark=10044, range=0
23212 2016-12-08 11:39:42 PST INFO  [pool-8-thread-17] gobblin.source.extractor.extract.kafka.KafkaSource  373 - Created workunit for partition s_browse_actions:0: lowWatermark=8      2, highWatermark=82, range=0
23213 2016-12-08 11:39:42 PST INFO  [pool-8-thread-2] gobblin.source.extractor.extract.kafka.KafkaSource  373 - Created workunit for partition s_login_detail:1: lowWatermark=1032      6, highWatermark=10326, range=0
23214 2016-12-08 11:39:42 PST INFO  [pool-8-thread-7] gobblin.source.extractor.extract.kafka.KafkaSource  373 - Created workunit for partition s_page_view:1: lowWatermark=1904510      6, highWatermark=19045315, range=209
23215 2016-12-08 11:39:42 PST INFO  [pool-8-thread-4] gobblin.source.extractor.extract.kafka.KafkaSource  373 - Created workunit for partition s_meetme:1: lowWatermark=118, highW      atermark=118, range=0
2016-12-08 11:39:42 PST INFO  [pool-8-thread-7] gobblin.source.extractor.extract.kafka.KafkaSource  373 - Created workunit for partition s_page_view:2: lowWatermark=1891627      5, highWatermark=18916486, range=211
23217 2016-12-08 11:39:42 PST INFO  [pool-8-thread-4] gobblin.source.extractor.extract.kafka.KafkaSource  373 - Created workunit for partition s_meetme:2: lowWatermark=115, highW      atermark=115, range=0
23218 2016-12-08 11:39:42 PST INFO  [pool-8-thread-4] gobblin.source.extractor.extract.kafka.KafkaSource  373 - Created workunit for partition s_meetme:3: lowWatermark=116, highW      atermark=116, range=0
23219 2016-12-08 11:39:42 PST INFO  [pool-8-thread-7] gobblin.source.extractor.extract.kafka.KafkaSource  373 - Created workunit for partition s_page_view:3: lowWatermark=1903276      7, highWatermark=19032975, range=208

In my configuration I am specifying the max number of mappers:

mr.job.max.mappers=15

So in the KafkaSource source code it does the following:
```java
int numOfMultiWorkunits =
        state.getPropAsInt(ConfigurationKeys.MR_JOB_MAX_MAPPERS_KEY, ConfigurationKeys.DEFAULT_MR_JOB_MAX_MAPPERS);
    return KafkaWorkUnitPacker.getInstance(this, state).pack(workUnits, numOfMultiWorkunits);
```
Where it attempts to pack the work units created across the 15 containers. The problem I am having is that the KafkaWorkUnitPacker is creating lots of empty work units as can be seen from the following:

23242 2016-12-08 11:39:42 PST INFO  [main] gobblin.source.extractor.extract.kafka.workunit.packer.KafkaWorkUnitPacker  289 - MultiWorkUnit 0: estimated load=0.003010, partitions=      [[s_pets_purchased:0], [s_newsfeed:0]]
23243 2016-12-08 11:39:42 PST INFO  [main] gobblin.source.extractor.extract.kafka.workunit.packer.KafkaWorkUnitPacker  289 - MultiWorkUnit 1: estimated load=17.522272, partitions      =[[s_page_view:2]]
23244 2016-12-08 11:39:42 PST INFO  [main] gobblin.source.extractor.extract.kafka.workunit.packer.KafkaWorkUnitPacker  289 - MultiWorkUnit 2: estimated load=17.522272, partitions      =[[s_page_view:0]]
23245 2016-12-08 11:39:42 PST INFO  [main] gobblin.source.extractor.extract.kafka.workunit.packer.KafkaWorkUnitPacker  289 - MultiWorkUnit 3: estimated load=13.157519, partitions      =[[s_browse_view:0]]
23246 2016-12-08 11:39:42 PST INFO  [main] gobblin.source.extractor.extract.kafka.workunit.packer.KafkaWorkUnitPacker  289 - MultiWorkUnit 4: estimated load=0.004771, partitions=      [[s_mobile_activity:0], [s_login_detail:0, s_login_detail:1], [s_friend_request:0]]
23247 2016-12-08 11:39:42 PST INFO  [main] gobblin.source.extractor.extract.kafka.workunit.packer.KafkaWorkUnitPacker  289 - MultiWorkUnit 5: estimated load=0.003010, partitions=      [[s_gold:0], [s_photo_upload:0]]
23248 2016-12-08 11:39:42 PST INFO  [main] gobblin.source.extractor.extract.kafka.workunit.packer.KafkaWorkUnitPacker  289 - MultiWorkUnit 6: estimated load=0.003010, partitions=      []
23249 2016-12-08 11:39:42 PST INFO  [main] gobblin.source.extractor.extract.kafka.workunit.packer.KafkaWorkUnitPacker  289 - MultiWorkUnit 7: estimated load=17.356184, partitions      =[[s_page_view:1]]
23250 2016-12-08 11:39:42 PST INFO  [main] gobblin.source.extractor.extract.kafka.workunit.packer.KafkaWorkUnitPacker  289 - MultiWorkUnit 8: estimated load=17.273140, partitions      =[[s_page_view:3]]
23251 2016-12-08 11:39:42 PST INFO  [main] gobblin.source.extractor.extract.kafka.workunit.packer.KafkaWorkUnitPacker  289 - MultiWorkUnit 9: estimated load=0.004771, partitions=      [[s_mess:0], [s_meetme:0, s_meetme:1, s_meetme:2, s_meetme:3], [s_browse_actions:0]]
23252 2016-12-08 11:39:42 PST INFO  [main] gobblin.source.extractor.extract.kafka.workunit.packer.KafkaWorkUnitPacker  289 - MultiWorkUnit 10: estimated load=0.004771, partitions      =[[s_pinch_point:0], [s_mail_send:0], [s_comment:0]]
23253 2016-12-08 11:39:42 PST INFO  [main] gobblin.source.extractor.extract.kafka.workunit.packer.KafkaWorkUnitPacker  289 - MultiWorkUnit 11: estimated load=0.003010, partitions      =[]
23254 2016-12-08 11:39:42 PST INFO  [main] gobblin.source.extractor.extract.kafka.workunit.packer.KafkaWorkUnitPacker  289 - MultiWorkUnit 12: estimated load=0.003010, partitions      =[]
23255 2016-12-08 11:39:42 PST INFO  [main] gobblin.source.extractor.extract.kafka.workunit.packer.KafkaWorkUnitPacker  289 - MultiWorkUnit 13: estimated load=0.003010, partitions      =[]
23256 2016-12-08 11:39:42 PST INFO  [main] gobblin.source.extractor.extract.kafka.workunit.packer.KafkaWorkUnitPacker  289 - MultiWorkUnit 14: estimated load=0.003010, partitions      =[[s_payment:0], [s_login:0, s_login:1]]

Now the problem this creates is that in [GobblinMultiTaskAttempt](https://github.com/linkedin/gobblin/blob/bb284d83dfcfd283da6254cd8e099503a2388c62/gobblin-runtime/src/main/java/gobblin/runtime/GobblinMultiTaskAttempt.java) if the work units are empty it returns : 
```java
public void run()
      throws IOException, InterruptedException {
    if (workUnits.isEmpty()) {
      log.warn("No work units to run in container " + containerIdOptional.or(""));
      return;
    }

    CountDownLatch countDownLatch = new CountDownLatch(workUnits.size());
    this.tasks = AbstractJobLauncher
        .runWorkUnits(jobId, jobState, workUnits, containerIdOptional, taskStateTracker, taskExecutor, countDownLatch);
```
which means that the tasks variable is never assigned a value, causing the NullPointerException in:

```java
public void commit()
      throws IOException {
    Iterator<Callable<Void>> callableIterator =
        Iterators.transform(this.tasks.iterator(), new Function<Task, Callable<Void>>() {
          @Override
          public Callable<Void> apply(final Task task) {
            return new Callable<Void>() {
              @Nullable
              @Override
              public Void call()
                  throws Exception {
                task.commit();
                return null;
              }
            };
          }
        });
```

I'm not sure if this is an issue with my configuration or with a bug in the code. My configuration is shown below:

job.name=Gobblin
job.group=GobblinKafka
job.description=Gobblin quick start job for Kafka
job.lock.enabled=false

kafka.brokers=kafkadatahub01:9092,kafkadatahub02:9092,kafkadatahub03:9092,kafkadatahub04:9092,kafkadatahub05:9092,kafkadatahub06:9092

source.class=com.ramblas.tagged.RamblasKafkaSource
extract.namespace=gobblin.extract.kafka
writer.partitioner.class=gobblin.writer.partitioner.TimeBasedAvroWriterPartitioner
writer.partition.pattern=YYYYMMdd/HH
writer.partition.timezone=-08
writer.partition.level=hourly
writer.builder.class=com.ramblas.tagged.RamblasDataWriterBuilder
writer.file.path.type=tablename
writer.destination.type=HDFS
writer.output.format=avro
mr.job.max.mappers=15
data.publisher.type=gobblin.publisher.TimePartitionedDataPublisher
data.publisher.replace.final.dir=false
metrics.enabled=false
schema.registry.class=com.tagged.tasr.schemaregistry.TASRSchemaRegistry
etl.schema.registry.url=http://tasr/tasr/subject
bootstrap.with.offset=latest
fs.uri=hdfs://dahdp2nn01.tag-dev.com:8020
writer.fs.uri=hdfs://dahdp2nn01.tag-dev.com:8020
state.store.fs.uri=hdfs://dahdp2nn01.tag-dev.com:8020
mr.job.root.dir=/gobblin-kafka/working
state.store.dir=/gobblin-kafka/state-store
task.data.root.dir=/jobs/kafkaetl/gobblin/gobblin-kafka/task-data
data.publisher.final.dir=/GobblinOutput/job-output/event_log

**Comment by ydai1124** [comment]
Hi,

Thanks for reporting that! It is a bug. I will fix it soon.

**Comment by ydai1124** [comment]
Fixed in PR: https://github.com/linkedin/gobblin/pull/1448

**Comment by Spracklen** [comment]
@ydai1124 Okay thanks for clarifying and thanks for being so quick on the fix!

One question: 

Why is the WorkUnitPacker creating so many empty work units here? If the load from Kafka is sufficiently low that it doesn't require all 15 mappers then why is it creating 15 work unit files? Why doesn't it just spin up the number of mapper that it needs instead of spinning up mappers that essentially do nothing? 

My understanding of mr.job.max.mappers=15 is that its only the max number that can be spun up?

**Comment by ydai1124** [comment]
Hi,

Gobblin kafka source creates one workunit for each topic partition. For a
partitions that is essentially empty, it creates a workunit with the same
low watermark and high watermark, which basically does nothing.

Looking further in the code, I think the original reason that empty
workunits are created is because KafkaSource relies on these empty
workunits to carry over previous job state, e.g., previous committed offset
for each partition. I believe this is something can be improved with the
current "dataset" state store model in gobblin. Basically, workunits belong
to the same topic partition will have separate state store, and no empty
workunits will be needed for carrying over states between executions.
@Chavdar, let me know if you have any comments.

Yes, currently "mr.job.max.mappers" is the only key to set the max number
of mappers. You can find more details about grouping kafka workunits here:
http://gobblin.readthedocs.io/en/latest/case-studies/Kafka-H
DFS-Ingestion/#grouping-workunits

**Comment by abti** [comment]
Closing since it is resolved
