### ISSUE TITLE
Get Kafka Brokers list using zookeeper client

### ISSUE THREAD

**Issue by wosiu** [linkedin/gobblin#1467]
[enhancement] It is hard to maintain kafka.brokers parameter in job properties of Kafka-HDFS map-reduce ingestion job, when we run it as scheduled oozie job.
It would be nice to not specify this property in config, instead we could use only zookeeper.connection.string to get brokers list each time we run scheduled MR job.

http://stackoverflow.com/questions/29490113/kafka-get-broker-host-from-zookeeper

**Comment by ibuenros** [comment]
@wosiu Sounds reasonable. Do you want to try to modify the `KafkaSource` to do this?
