### ISSUE TITLE
How to use oozie to schedule gobblin  with mapreduce mode, not the local mode

### ISSUE THREAD

**Issue by maiyatanglxn** [linkedin/gobblin#1565]
The document have an example,but it is only for local mode, how about mapreduce mode?
I changed the "CliLocalJobLauncher" to "CliMrJobLauncher" in workflow.xml, but  the mapreduce task
on yarn exit with error: java.lang.NoClassFoundError:gobblin/configuration/state.It seems that the jars are not found. How can I let the jars found? PS: it is the mapreduce task distributed by the joblaucher that can not found jars,not the joblaucher itself.

Any suggestion is appreciated.

**Comment by sungpeo** [comment]
I haven't tried local mode, but mapreduce mode. Did you put jars into oozie library path (or workflow lib)?

**Comment by cvaliente** [comment]
set

    job.hdfs.jars 

to your gobblin library directory
in the gobblin-mapreduce.properties (which you should add to oozie's working dir through e.g.
    
    <file>/path/to/gobblin-mapreduce.properties#gobblin-mapreduce.properties</file>

**Comment by Re1tReddy** [comment]
Hi cvaliente ,
Could you please explain the steps in details ..  I am also facing similar issue . It would be great if you can help me .
