### ISSUE TITLE
How does Gobblin store Kafka consumer group offset?

### ISSUE THREAD

**Issue by kitgary** [linkedin/gobblin#1568]
I set job.group=GobblinToHdfs1 in the job conf, but I can't find the consumer group by using either

kafka-consumer-groups.sh --zookeeper zk:2181 --list
or
kafka-consumer-groups.sh  --bootstrap-server localhost:9092  --list

I am curious how Gobblin manage the consumer group offset?

**Comment by ibuenros** [comment]
Hi Gary,
Gobblin does not use the usual Zookeeper way of storing offsets, instead
keeping state in its own state store. If you're curious, under Gobblin work
directory you should see a subdirectory called state-store, which contains
*.jst files with that state for every job. The state is keyed by job.name.
Best,
Issac

**Comment by shirshanka** [comment]
@kitgary : Did this response resolve your question? Did you need further clarification?
