### ISSUE TITLE
gobblin+azkaban mapreduce failed | job.state file does not exist

### ISSUE THREAD

**Issue by daku123** [linkedin/gobblin#1667]
i am trying to execute gobblin job with azkaban integration as mentioned in gobblin documentation using azkaban jobtypes (hadoopjava types).when i am executing it,gobblin generate lock folder and write work-units file .wu and job.state file on hdfs but when it comes to runworkunits ,it tries to read the job.state file from local filesystem and throw an error file not found .i am providing error logs here -

01-03-2017 21:23:43 PST wikipedia INFO - Starting job wikipedia at 1488432223913
01-03-2017 21:23:43 PST wikipedia INFO - Building hadoopJava job executor. 
01-03-2017 21:23:43 PST wikipedia INFO - 1 commands to execute.
01-03-2017 21:23:43 PST wikipedia INFO - Command: java -Xdebug -Xrunjdwp:server=y,transport=dt_socket,address=4000,suspend=y -Xms64M -Xmx256M -cp /root/Shared/vb_shared/java-wc/lib/*:/usr/lib/hadoop/lib/hadoop-core-1.2.1.jar:/root/Shared/vb_shared/java-wc/lib/apache-logging-log4j.jar:/root/Shared/vb_shared/java-wc/lib/commons-logging-1.2.jar	:/root/azkaban-solo-2.5.0/plugins/azkaban-jobtype-3.0.0/hadoopJava/azkaban-jobtype-3.0.0.jar:/root/azkaban-solo-2.5.0/lib/azkaban-2.5.0.jar:/root/azkaban-solo-2.5.0/plugins/azkaban-jobtype-3.0.0/azkaban-hadoopsecuritymanageryarn-3.0.0.jar:/root/azkaban-solo-2.5.0/executions/31/_resources_wikipedia azkaban.jobtype.HadoopJavaJobRunnerMain /root/Shared/vb_shared/java-wc/gobblin-omniture.properties
01-03-2017 21:23:43 PST wikipedia INFO - Environment variables: {JOB_OUTPUT_PROP_FILE=/root/azkaban-solo-2.5.0/executions/31/wikipedia_output_2257729854019556273_tmp, JOB_PROP_FILE=/root/azkaban-solo-2.5.0/executions/31/wikipedia_props_3084332309877945624_tmp, JOB_NAME=wikipedia}
01-03-2017 21:23:43 PST wikipedia INFO - Working directory: /root/azkaban-solo-2.5.0/executions/31
01-03-2017 21:23:44 PST wikipedia INFO - Listening for transport dt_socket at address: 4000
01-03-2017 21:23:56 PST wikipedia INFO - WARN Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
01-03-2017 21:23:57 PST wikipedia INFO - INFO Running job wikipedia
01-03-2017 21:23:57 PST wikipedia INFO - INFO Class name gobblin.azkaban.AzkabanJobLauncher
01-03-2017 21:23:57 PST wikipedia INFO - INFO Constructor found public gobblin.azkaban.AzkabanJobLauncher(java.lang.String,java.util.Properties) throws java.lang.Exception
01-03-2017 21:23:57 PST wikipedia INFO - INFO fs.default.name is deprecated. Instead, use fs.defaultFS
01-03-2017 21:23:57 PST wikipedia INFO - INFO Job type hadoopJava provides Hadoop tokens automatically. Using provided tokens.
01-03-2017 21:23:57 PST wikipedia INFO - WARN No config value found for config azkaban.flow.projectname. Metrics will not have tag azkabanProjectName
01-03-2017 21:23:57 PST wikipedia INFO - WARN No config value found for config azkaban.flow.flowid. Metrics will not have tag azkabanFlowId
01-03-2017 21:23:57 PST wikipedia INFO - WARN No config value found for config azkaban.job.id. Metrics will not have tag azkabanJobId
01-03-2017 21:23:57 PST wikipedia INFO - WARN No config value found for config azkaban.flow.execid. Metrics will not have tag azkabanExecId
01-03-2017 21:23:58 PST wikipedia INFO - WARN Property task.data.root.dir is missing.
01-03-2017 21:23:59 PST wikipedia INFO - INFO no default cluster mapping found
01-03-2017 21:24:00 PST wikipedia INFO - INFO Got object gobblin.azkaban.AzkabanJobLauncher@28cb9120
01-03-2017 21:24:00 PST wikipedia INFO - INFO Invoking method run
01-03-2017 21:24:00 PST wikipedia INFO - INFO Proxy check failed, not proxying run.
01-03-2017 21:24:00 PST wikipedia INFO - INFO Starting the Gobblin application and all its associated Services
01-03-2017 21:24:00 PST wikipedia INFO - INFO Attempting to shutdown ExecutorService: java.util.concurrent.ThreadPoolExecutor@57bd802b[Shutting down, pool size = 2, active threads = 1, queued tasks = 0, completed tasks = 1]
01-03-2017 21:24:00 PST wikipedia INFO - INFO Successfully shutdown ExecutorService: java.util.concurrent.ThreadPoolExecutor@57bd802b[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]
01-03-2017 21:24:00 PST wikipedia INFO - source class : execution start
01-03-2017 21:24:00 PST wikipedia INFO - watermark created!!!
01-03-2017 21:24:00 PST wikipedia INFO - titles :LinkedIn
01-03-2017 21:24:00 PST wikipedia INFO - titles :Wikipedia:Sandbox
01-03-2017 21:24:00 PST wikipedia INFO - workunit created!!
01-03-2017 21:24:00 PST wikipedia INFO - {
01-03-2017 21:24:00 PST wikipedia INFO - 	"job name": "PullFromWikipedia",
01-03-2017 21:24:00 PST wikipedia INFO - 	"job id": "job_PullFromWikipedia_1488432237822",
01-03-2017 21:24:00 PST wikipedia INFO - 	"job state": "PENDING",
01-03-2017 21:24:00 PST wikipedia INFO - 	"start time": 0,
01-03-2017 21:24:00 PST wikipedia INFO - 	"end time": 0,
01-03-2017 21:24:00 PST wikipedia INFO - 	"duration": 0,
01-03-2017 21:24:00 PST wikipedia INFO - 	"tasks": 0,
01-03-2017 21:24:00 PST wikipedia INFO - 	"completed tasks": 0,
01-03-2017 21:24:00 PST wikipedia INFO - 	"task states": []
01-03-2017 21:24:00 PST wikipedia INFO - }
01-03-2017 21:24:00 PST wikipedia INFO - INFO Attempting to shutdown ExecutorService: java.util.concurrent.ThreadPoolExecutor@15fdd1f2[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
01-03-2017 21:24:00 PST wikipedia INFO - INFO Successfully shutdown ExecutorService: java.util.concurrent.ThreadPoolExecutor@15fdd1f2[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0]
01-03-2017 21:24:00 PST wikipedia INFO - INFO Starting job job_PullFromWikipedia_1488432237822
01-03-2017 21:24:00 PST wikipedia INFO - INFO Attempting to shutdown ExecutorService: java.util.concurrent.ThreadPoolExecutor@1b005a0b[Shutting down, pool size = 2, active threads = 0, queued tasks = 0, completed tasks = 2]
01-03-2017 21:24:00 PST wikipedia INFO - INFO Successfully shutdown ExecutorService: java.util.concurrent.ThreadPoolExecutor@1b005a0b[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]
01-03-2017 21:24:00 PST wikipedia INFO - INFO Attempting to shutdown ExecutorService: java.util.concurrent.ThreadPoolExecutor@3015db78[Shutting down, pool size = 2, active threads = 1, queued tasks = 0, completed tasks = 1]
01-03-2017 21:24:00 PST wikipedia INFO - INFO Successfully shutdown ExecutorService: java.util.concurrent.ThreadPoolExecutor@3015db78[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]
01-03-2017 21:24:00 PST wikipedia INFO - INFO Starting the TaskStateCollectorService
01-03-2017 21:24:00 PST wikipedia INFO - INFO Launching Hadoop MR job Gobblin-PullFromWikipedia
01-03-2017 21:24:16 PST wikipedia INFO - INFO session.id is deprecated. Instead, use dfs.metrics.session-id
01-03-2017 21:24:16 PST wikipedia INFO - INFO Initializing JVM Metrics with processName=JobTracker, sessionId=
01-03-2017 21:25:11 PST wikipedia INFO - WARN Output task state path /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/output/job_PullFromWikipedia_1488432237822 does not exist
01-03-2017 21:27:59 PST wikipedia INFO - WARN Output task state path /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/output/job_PullFromWikipedia_1488432237822 does not exist
01-03-2017 21:27:59 PST wikipedia INFO - WARN Output task state path /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/output/job_PullFromWikipedia_1488432237822 does not exist
01-03-2017 21:30:02 PST wikipedia INFO - WARN Output task state path /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/output/job_PullFromWikipedia_1488432237822 does not exist
01-03-2017 21:30:27 PST wikipedia INFO - WARN Output task state path /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/output/job_PullFromWikipedia_1488432237822 does not exist
01-03-2017 21:31:12 PST wikipedia INFO - WARN Output task state path /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/output/job_PullFromWikipedia_1488432237822 does not exist
01-03-2017 21:31:25 PST wikipedia INFO - WARN Output task state path /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/output/job_PullFromWikipedia_1488432237822 does not exist
01-03-2017 21:33:38 PST wikipedia INFO - WARN Output task state path /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/output/job_PullFromWikipedia_1488432237822 does not exist
01-03-2017 21:33:49 PST wikipedia INFO - WARN Output task state path /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/output/job_PullFromWikipedia_1488432237822 does not exist
01-03-2017 21:37:08 PST wikipedia INFO - WARN Output task state path /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/output/job_PullFromWikipedia_1488432237822 does not exist
01-03-2017 21:37:08 PST wikipedia INFO - WARN Output task state path /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/output/job_PullFromWikipedia_1488432237822 does not exist
01-03-2017 21:37:34 PST wikipedia INFO - WARN Output task state path /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/output/job_PullFromWikipedia_1488432237822 does not exist
01-03-2017 21:37:42 PST wikipedia INFO - WARN Output task state path /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/output/job_PullFromWikipedia_1488432237822 does not exist
01-03-2017 21:41:34 PST wikipedia INFO - WARN Output task state path /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/output/job_PullFromWikipedia_1488432237822 does not exist
01-03-2017 21:41:56 PST wikipedia INFO - WARN Output task state path /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/output/job_PullFromWikipedia_1488432237822 does not exist
01-03-2017 21:42:13 PST wikipedia INFO - WARN Output task state path /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/output/job_PullFromWikipedia_1488432237822 does not exist
01-03-2017 21:42:32 PST wikipedia INFO - WARN Output task state path /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/output/job_PullFromWikipedia_1488432237822 does not exist
01-03-2017 21:42:32 PST wikipedia INFO - WARN Output task state path /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/output/job_PullFromWikipedia_1488432237822 does not exist
01-03-2017 21:43:45 PST wikipedia INFO - WARN Output task state path /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/output/job_PullFromWikipedia_1488432237822 does not exist
01-03-2017 21:44:28 PST wikipedia INFO - WARN Output task state path /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/output/job_PullFromWikipedia_1488432237822 does not exist
01-03-2017 21:46:12 PST wikipedia INFO - WARN Output task state path /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/output/job_PullFromWikipedia_1488432237822 does not exist
01-03-2017 21:46:21 PST wikipedia INFO - WARN Output task state path /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/output/job_PullFromWikipedia_1488432237822 does not exist
01-03-2017 21:47:23 PST wikipedia INFO - WARN Output task state path /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/output/job_PullFromWikipedia_1488432237822 does not exist
01-03-2017 21:48:10 PST wikipedia INFO - WARN Output task state path /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/output/job_PullFromWikipedia_1488432237822 does not exist
01-03-2017 21:50:02 PST wikipedia INFO - WARN Output task state path /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/output/job_PullFromWikipedia_1488432237822 does not exist
01-03-2017 21:50:03 PST wikipedia INFO - WARN Output task state path /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/output/job_PullFromWikipedia_1488432237822 does not exist
01-03-2017 21:51:26 PST wikipedia INFO - WARN Output task state path /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/output/job_PullFromWikipedia_1488432237822 does not exist
01-03-2017 21:52:09 PST wikipedia INFO - WARN Output task state path /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/output/job_PullFromWikipedia_1488432237822 does not exist
01-03-2017 21:53:19 PST wikipedia INFO - WARN Output task state path /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/output/job_PullFromWikipedia_1488432237822 does not exist
01-03-2017 21:54:05 PST wikipedia INFO - WARN Output task state path /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/output/job_PullFromWikipedia_1488432237822 does not exist
01-03-2017 21:55:14 PST wikipedia INFO - WARN Output task state path /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/output/job_PullFromWikipedia_1488432237822 does not exist
01-03-2017 21:55:33 PST wikipedia INFO - WARN Hadoop command-line option parsing not performed. Implement the Tool interface and execute your application with ToolRunner to remedy this.
01-03-2017 21:56:02 PST wikipedia INFO - INFO Cleaning up the staging area file:/tmp/hadoop-root/mapred/staging/root1857923643/.staging/job_local1857923643_0001
01-03-2017 21:56:49 PST wikipedia INFO - WARN Output task state path /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/output/job_PullFromWikipedia_1488432237822 does not exist
01-03-2017 21:57:07 PST wikipedia INFO - WARN Output task state path /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/output/job_PullFromWikipedia_1488432237822 does not exist
01-03-2017 21:58:24 PST wikipedia INFO - WARN PriviledgedActionException as:root (auth:SIMPLE) cause:java.io.FileNotFoundException: File /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/job.state does not exist
01-03-2017 21:58:39 PST wikipedia INFO - WARN Output task state path /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/output/job_PullFromWikipedia_1488432237822 does not exist
01-03-2017 21:58:52 PST wikipedia INFO - INFO Stopping the TaskStateCollectorService
01-03-2017 21:58:52 PST wikipedia INFO - WARN Output task state path /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/output/job_PullFromWikipedia_1488432237822 does not exist
01-03-2017 21:58:53 PST wikipedia INFO - INFO Deleted working directory /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822
01-03-2017 21:59:03 PST wikipedia INFO - ERROR Failed to launch and run job job_PullFromWikipedia_1488432237822: java.io.FileNotFoundException: File /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/job.state does not exist
01-03-2017 21:59:03 PST wikipedia INFO - java.io.FileNotFoundException: File /root/gobblin-work/work_dir/working/PullFromWikipedia/job_PullFromWikipedia_1488432237822/job.state does not exist
01-03-2017 21:59:03 PST wikipedia INFO - 	at org.apache.hadoop.fs.RawLocalFileSystem.deprecatedGetFileStatus(RawLocalFileSystem.java:511)
01-03-2017 21:59:03 PST wikipedia INFO - 	at org.apache.hadoop.fs.RawLocalFileSystem.getFileLinkStatusInternal(RawLocalFileSystem.java:722)
01-03-2017 21:59:03 PST wikipedia INFO - 	at org.apache.hadoop.fs.RawLocalFileSystem.getFileStatus(RawLocalFileSystem.java:501)
01-03-2017 21:59:03 PST wikipedia INFO - 	at org.apache.hadoop.fs.FilterFileSystem.getFileStatus(FilterFileSystem.java:398)
01-03-2017 21:59:03 PST wikipedia INFO - 	at org.apache.hadoop.mapreduce.filecache.ClientDistributedCacheManager.getFileStatus(ClientDistributedCacheManager.java:288)
01-03-2017 21:59:03 PST wikipedia INFO - 	at org.apache.hadoop.mapreduce.filecache.ClientDistributedCacheManager.getFileStatus(ClientDistributedCacheManager.java:224)
01-03-2017 21:59:03 PST wikipedia INFO - 	at org.apache.hadoop.mapreduce.filecache.ClientDistributedCacheManager.determineTimestamps(ClientDistributedCacheManager.java:93)
01-03-2017 21:59:03 PST wikipedia INFO - 	at org.apache.hadoop.mapreduce.filecache.ClientDistributedCacheManager.determineTimestampsAndCacheVisibilities(ClientDistributedCacheManager.java:57)
01-03-2017 21:59:03 PST wikipedia INFO - 	at org.apache.hadoop.mapreduce.JobSubmitter.copyAndConfigureFiles(JobSubmitter.java:265)
01-03-2017 21:59:03 PST wikipedia INFO - 	at org.apache.hadoop.mapreduce.JobSubmitter.copyAndConfigureFiles(JobSubmitter.java:301)
01-03-2017 21:59:03 PST wikipedia INFO - 	at org.apache.hadoop.mapreduce.JobSubmitter.submitJobInternal(JobSubmitter.java:389)
01-03-2017 21:59:03 PST wikipedia INFO - 	at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1285)
01-03-2017 21:59:03 PST wikipedia INFO - 	at org.apache.hadoop.mapreduce.Job$10.run(Job.java:1282)
01-03-2017 21:59:03 PST wikipedia INFO - 	at java.security.AccessController.doPrivileged(Native Method)
01-03-2017 21:59:03 PST wikipedia INFO - 	at javax.security.auth.Subject.doAs(Subject.java:422)
01-03-2017 21:59:03 PST wikipedia INFO - 	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1548)
01-03-2017 21:59:03 PST wikipedia INFO - 	at org.apache.hadoop.mapreduce.Job.submit(Job.java:1282)
01-03-2017 21:59:03 PST wikipedia INFO - 	at gobblin.runtime.mapreduce.MRJobLauncher.runWorkUnits(MRJobLauncher.java:203)
01-03-2017 21:59:03 PST wikipedia INFO - 	at gobblin.runtime.AbstractJobLauncher.launchJob(AbstractJobLauncher.java:296)
01-03-2017 21:59:03 PST wikipedia INFO - 	at gobblin.azkaban.AzkabanJobLauncher.launchJob(AzkabanJobLauncher.java:207)
01-03-2017 21:59:03 PST wikipedia INFO - 	at gobblin.azkaban.AzkabanJobLauncher.run(AzkabanJobLauncher.java:171)
01-03-2017 21:59:03 PST wikipedia INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01-03-2017 21:59:03 PST wikipedia INFO - 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01-03-2017 21:59:03 PST wikipedia INFO - 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01-03-2017 21:59:03 PST wikipedia INFO - 	at java.lang.reflect.Method.invoke(Method.java:497)
01-03-2017 21:59:03 PST wikipedia INFO - 	at azkaban.jobtype.HadoopJavaJobRunnerMain.runMethod(HadoopJavaJobRunnerMain.java:240)
01-03-2017 21:59:03 PST wikipedia INFO - 	at azkaban.jobtype.HadoopJavaJobRunnerMain.(HadoopJavaJobRunnerMain.java:177)
01-03-2017 21:59:03 PST wikipedia INFO - 	at azkaban.jobtype.HadoopJavaJobRunnerMain.main(HadoopJavaJobRunnerMain.java:80)

i dont why i am getting this error.if anyone have an idea, please let me know.
thanks

**Comment by ydai1124** [comment]
@daku123 Can you share your job config file? Did you set `state.store.fs.uri`?
