### ISSUE TITLE
Avro to ORC converter does not preserve order of the newly added columns (schema evolution)

### ISSUE THREAD

**Issue by mwiewior** [linkedin/gobblin#1672]
Hi, we discovered that after adding more than 1 column in the source Avro based table at a time and then run avro to orc converter with a schema evolution feature enabled then all the columns are added in the target ORC table but in a random order. This causes that we cannot read from the  ORC table unless we alter it manually and reorder the columns.

**Comment by abti** [comment]
Fixed by: https://github.com/linkedin/gobblin/pull/1674 
Thanks @aditya1105
