### ISSUE TITLE
gobblin-distribution tar is not available on Maven Central

### ISSUE THREAD

**Issue by chemikadze** [linkedin/gobblin#1718]
Probably I'm missing something, but looks like gobblin-distribution tarball is not available on Maven Central. Is that expected, or just no one needed that before?

**Comment by ibuenros** [comment]
Hi Nikolay,

Why do you need the tarball on Maven? If you're depending on Gobblin, you
should use the *.jar artifacts instead. Maybe I don't fully understand your
use case.

Best,
Issac

**Comment by chemikadze** [comment]
Thing is that in my case that's not Java program, but "super-distribution" tarball that has gobblin as part of itself.

**Comment by sahilTakiar** [comment]
We created distributions for each release, they can be found here: https://github.com/linkedin/gobblin/releases

Would simply downloading them from the releases page be sufficient for your use case?

**Comment by chemikadze** [comment]
Yeah, I know that.

In our case we've expected these tar artifacts to be available through nexus, so this issue got created.
