### ISSUE TITLE
JobScheduler failed when "jobconf.fullyQualifiedPath" is not set.

### ISSUE THREAD

**Issue by kadaan** [linkedin/gobblin#1792]
In JobScheduler.java, seems like there is a bug where jobConfigFileDirPath does not get set if "jobconf.fullyQualifiedPath" is not configured. Seems like this should be supported as there is a check in JobScheduler.java.startUp which sets "jobconf.fullyQualifiedPath".

**Comment by autumnust** [comment]
Hi @kadaan , thanks for pointing this out.

`jobconf.fullyQualifiedPath` is added for loading configuration file from general file system instead of localFS only. Will make this backward compatible.

**Comment by kadaan** [comment]
I think the easiest solution might be to move 
```
if (this.properties.containsKey(ConfigurationKeys.JOB_CONFIG_FILE_DIR_KEY) && !this.properties.containsKey(ConfigurationKeys.JOB_CONFIG_FILE_GENERAL_PATH_KEY)) {
      this.properties.setProperty(ConfigurationKeys.JOB_CONFIG_FILE_GENERAL_PATH_KEY, "file://" + this.properties.getProperty(ConfigurationKeys.JOB_CONFIG_FILE_DIR_KEY));
}
```
into the constructor before 
```
if (this.properties.containsKey(ConfigurationKeys.JOB_CONFIG_FILE_GENERAL_PATH_KEY)) {
      this.jobConfigFileDirPath = new Path(this.properties.getProperty(ConfigurationKeys.JOB_CONFIG_FILE_GENERAL_PATH_KEY));
      this.listener = new PathAlterationListenerAdaptorForMonitor(jobConfigFileDirPath, this);
} else {
      // This is needed because HelixJobScheduler does not use the same way of finding changed paths
      this.jobConfigFileDirPath = null;
      this.listener = null;
}
```

**Comment by kadaan** [comment]
There is also another problem here.  The legacy property, `ConfigurationKeys.JOB_CONFIG_FILE_DIR_KEY`, supported a relative path.  With the new code, this is not supported.  The solution is to convert `ConfigurationKeys.JOB_CONFIG_FILE_DIR_KEY` to an absolute path before prepending it with `file:///` and finishing the creation of the job config monitor.
