### ISSUE TITLE
Jobs created with same JobId over and over

### ISSUE THREAD

**Issue by kadaan** [linkedin/gobblin#1853]
Running in gobblin-yarn, jobs seem to be created over and over with the same JobId.  Seems to be related to 98bb53c3d37a960956ba0fe99dbbc115a54e7c55.

**Comment by kadaan** [comment]
@htran1 Can you please look into this?

**Comment by htran1** [comment]
Fixed in PR https://github.com/linkedin/gobblin/pull/1974.
