### ISSUE TITLE
Gobblin 0.10.0 distribution TAR missing under releases

### ISSUE THREAD

**Issue by mihkels** [linkedin/gobblin#1859]
For other releases, there is pre-built distribution TAR published under releases but not for 0.10.0.
Will it be published or is it expected that from now on all developers should build their own distribution TAR?

**Comment by ydai1124** [comment]
@mihkels There will be a pre-built distribution TAR. @autumnust can you take a look?

**Comment by mihkels** [comment]
Cool thank You. Another thing I noticed missing is a link to release notes I saw them in Google mailing list but would be useful to add them to Github releases.

**Comment by autumnust** [comment]
@mihkels I've updated the release and add the release page link on it. Thanks for pointing that out.

**Comment by mihkels** [comment]
Thank you @autumnust. Now my setup scripts work perfectly will close the issue.
