### ISSUE TITLE
SQL Server - incomplete JDBC URL

### ISSUE THREAD

**Issue by debelyoo** [linkedin/gobblin#1867]
The connection URL lacks the database name. The URL returned by getConnectionUrl() (in SqlServerExtractor.java) looks like this `jdbc:sqlserver://sql_server_host:1433` but should be `jdbc:sqlserver://sql_server_host:1433;databaseName=myDb` (similar to what is done for MySQL).

I propose the following fix
`String database = this.workUnitState.getProp(ConfigurationKeys.SOURCE_QUERYBASED_SCHEMA);
    String url = "jdbc:sqlserver://" + host.trim() + ":" + port + ";databaseName=" + database.trim();`

**Comment by arjun4084346** [comment]
Hi @debelyoo,
We have filed a ticket for this https://issues.apache.org/jira/browse/GOBBLIN-27
Meanwhile, could you answer if source.querybased.query in your job file contains schema name?

Thanks,
