### ISSUE TITLE
Setup auto-building of docker

### ISSUE THREAD

**Issue by MikeSchroll** [linkedin/gobblin#1897]
The docker repo setup at: https://hub.docker.com/u/gobblin/
Is not tied to the github repo...
As a result, it's not up to date, and has gotten stale.

Can I suggest that you tie it to the repo, so it can auto-rebuild on pushes / releases; and then those wishing to pull those docker containers can keep up with latest releases?

**Comment by sahilTakiar** [comment]
I can spend some time looking into this. I may need help from someone at LinkedIn though, I'm guessing this may require integration with Github Webhooks. Something I currently don't have permission to do.

**Comment by ibuenros** [comment]
Sahil,
Let us know what you need and we'll try to do it.

**Comment by sahilTakiar** [comment]
As a start, I published a PR for publishing updated docker images for the 0.9.0 and 0.10.0 release - #1898

**Comment by sahilTakiar** [comment]
I pushed the docker images for the 0.9.0 and 0.10.0 to Docker Hub: https://hub.docker.com/r/gobblin/gobblin-standalone/

Setting up automatic builds is actually pretty straight forward, but it does require giving Docker Hub read and write access to the git repo.

I'm assuming Gobblin is going to move into a new location on GitHub once its officially in apache-incubator? It may make more sense to wait until that happens before setting up automatic builds.

Links on how automatic builds and GitHub integration works:

https://docs.docker.com/docker-hub/github/
https://docs.docker.com/docker-hub/builds/
http://blog.docker.com/2015/11/upgraded-autobuild-docker-hub/
