### ISSUE TITLE
dataset specific properties are ignored&dropped by KafkaBiLevelWorkUnitPacker

### ISSUE THREAD

**Issue by cvaliente** [linkedin/gobblin#1901]
I failed to get dataset.specific.props to work on our jobs, and I think I found the reason:

in KafkaSource.getWorkUnitForTopicPartition the properties are added correctly to the individual workunits.

The KafkaBiLevelWorkUnitPacker then assigns the WorkUnits to their bins and combines them into one WorkUnit in squeezeMultiWorkUnit() but doesn't copy over the topicSpecificSettings.

Using the KafkaSingleLevelWorkUnitPacker works fine with dataset.specific.props since it doesn't call squeezeMultiWorkUnit on non-empty workUnits.

**Comment by cvaliente** [comment]
fix in #1903

**Comment by sahilTakiar** [comment]
Doesn't `KafkaSource#addTopicSpecificPropsToWorkUnits` handle adding dataset specific configuration? That method is run after the bin-packing is done. So if `dataset.specific.props` isn't working I would guess the bug would be in that method.

**Comment by cvaliente** [comment]
You are right, that wasn't yet implemented in 0.9 and I forgot to check upstream.
