### ISSUE TITLE
Elasticsearch Writer

### ISSUE THREAD

**Issue by sahilTakiar** [linkedin/gobblin#1912]
Add an Elasticsearch writer to Gobblin.

Let me know if anyone is already working on this, or has any thoughts on this writer. Will probably work on it over the new few weeks.

**Comment by shirshanka** [comment]
Model it on couchbase/Kafka/eventhub writer so you get streaming plus async for free. 

Shirshanka

**Comment by zxcware** [comment]
Is it a writer based on http protocol?

**Comment by sahilTakiar** [comment]
@shirshanka will do. Right now I have the writer implementing `BatchAsyncDataWriter` and using `BufferedAsyncDataWriter`.  This way it gets batching for free.

@zxcware the plan to is provide two writers, one that uses http and the other that uses the Elasticsearch's Java Client `TransportClient`. I haven't done work for the http writer yet, but I will probably base it on `RestJsonWriter`.

**Comment by zxcware** [comment]
@sahilTakiar Don't do it based on `RestJsonWriter`, which will be deprecated. Checkout `AsyncHttpWriter`

**Comment by zxcware** [comment]
@sahilTakiar Just heads up, I am doing some refactoring over the whole sync piece in order to support http read. You may see some back incompatible changes

**Comment by sahilTakiar** [comment]
@zxcware thanks for the heads up, will do.

**Comment by zxcware** [comment]
@sahilTakiar How is the ElasticsearchWriter going?

**Comment by sahilTakiar** [comment]
I have a working version and some basic integration tests. Just working on cleaning up the code and writing some documentation. So probably a few more weeks.
