### ISSUE TITLE
KafkaExtractor custom metrics

### ISSUE THREAD

**Issue by jean-helsinki** [linkedin/gobblin#1944]
It's posible to create custom metric with Kafka offsets for all topics, to store high and low watermarks.
By design InstrumentedExtractor can track only read records metrics.
Where is better way to do this?

**Comment by ibuenros** [comment]
Hi Jean,

Are you interested in a metric that updates constantly? Or an event that
gets emitted at the end of the run with the offset for each partition?

Both are possible, but require dev work. Would you be interested in
implementing this?

Best,
Issac

**Comment by jean-helsinki** [comment]
Second, at end of the run task for each partition.
I agree to implement this.

**Comment by ibuenros** [comment]
You can use an EventSubmitter (
https://github.com/linkedin/gobblin/blob/master/gobblin-metrics-libs/gobblin-metrics-base/src/main/java/gobblin/metrics/event/EventSubmitter.java)
to submit events from the KafkaExtractor. You will need a handle to a
MetricContext to create an EventSubmitter, but that is already available
int he KafkaExtractor. You can include arbitrary metadata in the event
submitted.

For an example, see
https://github.com/linkedin/gobblin/blob/master/gobblin-runtime/src/main/java/gobblin/runtime/GobblinMultiTaskAttempt.java#L308
.

Thanks for taking the lead on this!

Best,
Issac

**Comment by jean-helsinki** [comment]
closed by issue #1961
