### ISSUE TITLE
Couldnt run gobblin-mapreduce using Kafka09ConsumerClient

### ISSUE THREAD

**Issue by bdigudadi** [linkedin/gobblin#1953]
Configuration added to override default 08 client:
gobblin.kafka.consumerClient.class=gobblin.kafka.client.Kafka09ConsumerClient$Factory.

When I run the job for first time without previous state store.
WorkUnits are not getting created. state store also not getting created.

> 2017-06-15 03:53:45 PDT ERROR [pool-8-thread-2] gobblin.source.extractor.extract.kafka.KafkaSource$WorkUnitCreator  553 - Caught error in creating work unit for topic1
> java.lang.UnsupportedOperationException: getEarliestOffset and getLatestOffset is not supported by Kafka-09
>         at gobblin.kafka.client.Kafka09ConsumerClient.getEarliestOffset(Kafka09ConsumerClient.java:115)
>         at gobblin.source.extractor.extract.kafka.KafkaSource.getWorkUnitForTopicPartition(KafkaSource.java:304)
>         at gobblin.source.extractor.extract.kafka.KafkaSource.getWorkUnitsForTopic(KafkaSource.java:267)
>         at gobblin.source.extractor.extract.kafka.KafkaSource.access$400(KafkaSource.java:72)
>         at gobblin.source.extractor.extract.kafka.KafkaSource$WorkUnitCreator.run(KafkaSource.java:551)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>         at java.lang.Thread.run(Thread.java:748)
> 2017-06-15 03:53:45 PDT ERROR [pool-8-thread-1] gobblin.source.extractor.extract.kafka.KafkaSource$WorkUnitCreator  553 - Caught error in creating work unit for topic2
> java.lang.UnsupportedOperationException: getEarliestOffset and getLatestOffset is not supported by Kafka-09
>         at gobblin.kafka.client.Kafka09ConsumerClient.getEarliestOffset(Kafka09ConsumerClient.java:115)
>         at gobblin.source.extractor.extract.kafka.KafkaSource.getWorkUnitForTopicPartition(KafkaSource.java:304)
>         at gobblin.source.extractor.extract.kafka.KafkaSource.getWorkUnitsForTopic(KafkaSource.java:267)
>         at gobblin.source.extractor.extract.kafka.KafkaSource.access$400(KafkaSource.java:72)
>         at gobblin.source.extractor.extract.kafka.KafkaSource$WorkUnitCreator.run(KafkaSource.java:551)
>         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
>         at java.util.concurrent.FutureTask.run(FutureTask.java:266)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
>         at java.lang.Thread.run(Thread.java:748)
> 2017-06-15 03:53:45 PDT INFO  [main] gobblin.util.ExecutorsUtils  205 - Successfully shutdown ExecutorService: java.util.concurrent.ThreadPoolExecutor@33eb6758[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]
> 2017-06-15 03:53:45 PDT INFO  [main] gobblin.source.extractor.extract.kafka.KafkaSource  186 - Created workunits for 0 topics in 0 seconds

When I run with a previous state store, fetching offsets fails(same as above). And WorkUnits gets created with same low and high watermark(using prev state-store) and nothing gets consumed.

> 2017-06-15 05:26:47 PDT ERROR [pool-9-thread-2] gobblin.source.extractor.extract.kafka.KafkaSource$WorkUnitCreator  553 - Caught error in creating work unit for topic1
> java.lang.UnsupportedOperationException: getEarliestOffset and getLatestOffset is not supported by Kafka-09
>         at ......
> 2017-06-15 05:26:47 PDT ERROR [pool-9-thread-1] gobblin.source.extractor.extract.kafka.KafkaSource$WorkUnitCreator  553 - Caught error in creating work unit for topic2
> java.lang.UnsupportedOperationException: getEarliestOffset and getLatestOffset is not supported by Kafka-09
>         at .....
> 2017-06-15 05:26:47 PDT INFO  [main] gobblin.util.ExecutorsUtils  205 - Successfully shutdown ExecutorService: java.util.concurrent.ThreadPoolExecutor@10b4e7f8[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 2]
> 2017-06-15 05:26:47 PDT INFO  [main] gobblin.source.extractor.extract.kafka.KafkaSource  186 - Created workunits for 0 topics in 0 seconds
> 2017-06-15 05:26:47 PDT INFO  [main] gobblin.source.extractor.extract.kafka.KafkaSource  466 - Created workunit for partition topic1:8: lowWatermark=20, highWatermark=20, range=0
> 2017-06-15 05:26:47 PDT INFO  [main] gobblin.source.extractor.extract.kafka.KafkaSource  466 - Created workunit for partition topic2:9: lowWatermark=19, highWatermark=19, range=0

 Mesages gets consumed only when I comment the below lines from "currentPartitionFinished" in "gobblin-modules/gobblin-kafka-common/src/main/java/gobblin/source/extractor/extract/kafka/KafkaExtractor.java"
>     //} else if (this.nextWatermark.get(this.currentPartitionIdx) >= this.highWatermark.get(this.currentPartitionIdx)) {
>       //LOG.info("Finished pulling partition " + this.getCurrentPartition());
>       //return true;

If kafka-09 doesnt support fetching offsets, How to proceed further? Am i missing some configuration here? Could you please let me know?

**Comment by autumnust** [comment]
@bdigudadi Just checked Kafka 0.9.x src and they do keep the offset-fetching api as 0.8.x, but in gobblin's implementation of `Kafka09ConsumerClient`, it is just not implemented and throw the UnsupportedOperation exception directly.

**Comment by bdigudadi** [comment]
@autumnust Thanks for the explanation.
I had to make few changes to make 09 client work with KafkaSource&Extractors. Where as kafkastreamingsource is working with 09client as it is.
