### ISSUE TITLE
consider migrating Gobblin JDBC adapters to a SQL builder library

### ISSUE THREAD

**Issue by chavdar** [linkedin/gobblin#236]
Currently gobblin uses rather error-prone string handling to generating SQL queries. We should consider migrating to a more robust SQL builder library like Jooq (www.jooq.org) or querydsl (www.querydsl.com).

**Comment by sahilTakiar** [comment]
Jooq seems interesting but requires Java 8.

The current `JDBCExtractor` converts a `ResultSet` into a GSON `JsonElement`. It would be more flexible to just return a `ResultSet` and have converts for `ResultSetToJson` and `ResultSetToAvro`.

The `JDBCExtractor` should probably not be an abstract class, so it can provide some default implementation for arbitrary JDBC adapters.
