### ISSUE TITLE
hdp2.2 can't  build

### ISSUE THREAD

**Issue by henryon** [linkedin/gobblin#322]
When I build gradlew with below command:
./gradlew clean build -PuseHadoop2 -PhadoopVersion=2.6.0
 the error shows 

gobblin.rest.JobExecutionInfoServerTest.setUp FAILED
    org.jboss.netty.channel.ChannelException at JobExecutionInfoServerTest.java:78
        Caused by: java.net.BindException at JobExecutionInfoServerTest.java:78

4 tests completed, 1 failed, 3 skipped
:gobblin-rest-service:gobblin-rest-server:test FAILED
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 warning

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':gobblin-rest-service:gobblin-rest-server:test'.
> There were failing tests. See the report at: file:///root/gobblin/build/gobblin-rest-server/reports/tests/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by sahilTakiar** [comment]
Hey henryon,

As an immediate fix you can run `/gradlew clean build -PuseHadoop2 -PhadoopVersion=2.6.0 -x test`. This will build everything without running any of the tests.

It looks like you already have an application bound to `localhost:8080` on your machine which is why the `JobExecutionInfoServerTest` test is failing.

**Comment by liyinan926** [comment]
@henryon as @sahilTakiar said, the test failed because the server failed to start on port `8080`. Can you check and see if you have anything running on that port? You can also add option `--info` to get more details on the test failure.

**Comment by henryon** [comment]
@liyinan926  thanks I will try it  and feedback to you

**Comment by henryon** [comment]
@liyinan926  it works now, i've tried it on another box, the original box  port 8080 has been occupied by ambari master process. thanks everyone
