### ISSUE TITLE
Very unstable kafka import

### ISSUE THREAD

**Issue by allmycode** [linkedin/gobblin#328]
When I'm using KafkaSimpleSource for importing kafka topic to HDFS, every time at job start I see _Reconnect due to socket error: java.nio.channels.ClosedChannelException_
and during work I see 
_Fetch message buffer for partition test1:0 has failed: java.net.SocketTimeoutException. This partition will be skipped._
One time it can export records from kafka to HDFS, but most time export fails, with _Extracted 0 data records_ due to socket timeouts. All my other clients works fine with those clusters.

**Comment by zliu41** [comment]
Hi @allmycode Gobblin currently uses `kafka.javaapi.consumer.fetch(kafka.javaapi.FetchRequest)` to fetch message buffers from Kafka brokers. What API do your other clients use? If they use the same one then there's no reason it works for them but not Gobblin.

btw we are in the process of adding support for the new Kafka API (`org.apache.kafka.clients.consumer.KafkaConsumer`).

**Comment by TheArtOfEngineering** [comment]
I am having what appears to be the same issue with the KafkaSimpleSource. I am able to connect to Kafka with the kafka-python module, so it doesn't appear to be a connection or firewall issue. Perhaps it has something to do with my configuration settings in my pull file?

My broker is specified as:
kafka.brokers=<hostname>:9092

The new API, is that just an apache implementation of the Gobblin KafkaConsumer?

**Comment by zliu41** [comment]
@allmycode @TheArtOfEngineering 
I recently tried to set up a Kafka job on my Macbook running OS X Yosemite, and it couldn't connect to any Kafka broker (even localhost) with the same `SocketTimeoutException`. However, on my Linux machine there's no problem whatsoever. I don't yet know why but you may want to try it in a different environment.

**Comment by DataEngg** [comment]
Any update on the issue ?

**Comment by shirshanka** [comment]
https://github.com/linkedin/gobblin/pull/1218 fixes this issue and has been merged to master. 

Please comment on this issue to let us know if this solved it for you.
