### ISSUE TITLE
bin/gobblin-mapreduce.sh: 11: bin/gobblin-mapreduce.sh: Syntax error: "(" unexpected

### ISSUE THREAD

**Issue by prasadnh** [linkedin/gobblin#388]
Hi,

What is this error...

bin/gobblin-mapreduce.sh: 11: bin/gobblin-mapreduce.sh: Syntax error: "(" unexpected

its throwing at function print_usage()

I tried different options in the command, returns same error for all
bin/gobblin-mapreduce.sh start --jt <<url>> --fs <<hdfsurl>> --logdir /home/ubuntu/gobblin/gobblin-dist/logs --conf /home/ubuntu/gobblin/gobblin-dist/conf/config

Prasad

**Comment by mwol** [comment]
this one works for me using /bin/bash instead of /bin/sh

**Comment by prasadnh** [comment]
Great!! thanks Mwol... atleast I don't see any syntax error after changing to bash
