### ISSUE TITLE
I get connection error when I try to run map-reduce.sh command with kafka.pull conf

### ISSUE THREAD

**Issue by prasadnh** [linkedin/gobblin#394]
Hi

Any idea about this error... i can see my spark/hadoop/kafka looks fine but when i run the command
bin/gobblin-mapreduce.sh start --conf /home/ubuntu/gobblin/gobblin-dist/conf/config/kafka.pull

Exception in thread "main" java.net.ConnectException: Call From <<host name/IP>> to localhost:8020 failed on connection exception: java.net.ConnectException:e:  http://wiki.apache.org/hadoop/ConnectionRefused

**Comment by zliu41** [comment]
@prasadnh please double check if `localhost:8020` is the correct uri for your hdfs. You may use `hdfs getconf -confKey fs.default.name` to verify.

**Comment by prasadnh** [comment]
thanks for the response...
so we cannot have different port  for hdfs?but we are using 9000...

-Prasad

On Mon, Oct 19, 2015 at 4:52 PM, Ziyang Liu <notifications@github.com>
wrote:

> @prasadnh <https://github.com/prasadnh> please double check if
> localhost:8020 is the correct uri for your hdfs. You may use hdfs getconf
> -confKey fs.default.name to verify.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/linkedin/gobblin/issues/394#issuecomment-149379315>.
>



-- 
Thanks,
Prasad

**Comment by liyinan926** [comment]
@prasadnh please change the setting of `fs.uri` in `conf/gobblin-mapreduce.properties` to the correct URI for the NameNode of your HDFS setup, e.g., `fs.uri=hdfs://localhost:9000`.

**Comment by prasadnh** [comment]
Thanks... I put wrong port number in properties file...updated and tried again... 

but I see same issue 

Exception in thread "main" java.net.ConnectException: Call From <> to localhost:8020 failed on connection exception: java.net.ConnectException:e: http://wiki.apache.org/hadoop/ConnectionRefused

**Comment by prasadnh** [comment]
I think we cannot give localhost...instead we need to hostname with 9000...but i get different exception

Exception in thread "main" java.lang.IllegalArgumentException: java.net.UnknownHostException: hdfs

**Comment by zliu41** [comment]
@prasadnh you can take a look at the stack trace. If the exception happens during the initialization of state store, you need to set `state.store.fs.uri=hdfs://localhost:9000`.

**Comment by prasadnh** [comment]
This value already there in properties file
state.store.fs.uri=${fs.uri}

**Comment by prasadnh** [comment]
what could be the reason command hangs forever here

./gobblin-mapreduce.sh stop --conf /home/ubuntu/gobblin/gobblin-dist/conf/config/kafka.pull
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/ubuntu/gobblin/gobblin-dist/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/bin/hadoop-2.6.0/share/hadoop/common/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]

**Comment by liyinan926** [comment]
`gobblin-mapreduce.sh` does not support the option `stop`.

**Comment by prasadnh** [comment]
oops copied wrong command... same behavior with start

./gobblin-mapreduce.sh start --conf /home/ubuntu/gobblin/gobblin-dist/conf/config/kafka.pull
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/ubuntu/gobblin/gobblin-dist/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/bin/hadoop-2.6.0/share/hadoop/common/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]

**Comment by liyinan926** [comment]
`gobblin-mapreduce.sh` does not support the option `start` either... Have you read https://github.com/linkedin/gobblin/wiki/Gobblin%20Deployment#Hadoop-MapReduce-Deployment?

**Comment by prasadnh** [comment]
sorry...not sure why I used this stop/start... i was running standalone before and just changed to mapreduce....
even no start/stop same issue... SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.



./gobblin-mapreduce.sh --conf /home/ubuntu/gobblin/gobblin-dist/conf/config/kafka.pull
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/ubuntu/gobblin/gobblin-dist/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/local/bin/hadoop-2.6.0/share/hadoop/common/lib/slf4j-log4j12-1.7.5.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]

**Comment by prasadnh** [comment]
I see process running but i don't see any logs, not sure its really working.

**Comment by liyinan926** [comment]
Please remove `gobblin-dist/lib/slf4j-log4j12-1.7.5.jar` and give a try.

**Comment by liyinan926** [comment]
@prasadnh any update on this issue?

**Comment by prasadnh** [comment]
No update... No success so far. 
I am working on upgrading our servers... Will try one more time once it's up and running.

Sent from Outlook




On Thu, Oct 29, 2015 at 12:16 PM -0700, "Yinan Li" <notifications@github.com> wrote:












@prasadnh any update on this issue?
