### ISSUE TITLE
What Java version is supported?

### ISSUE THREAD

**Issue by galgalesh** [linkedin/gobblin#413]
Is it possible to add to the documentation what the recommended java version is to compile and run?

**Comment by sahilTakiar** [comment]
Hey @galgalesh Gobblin is currently compiled against Java 7. This means the env you deploy Gobblin on must run Java 7+

I agree it is not well documented, you can see what Java Version we compile against by taking a look at this line in the main build.gradle script: https://github.com/linkedin/gobblin/blob/master/build.gradle#L158

**Comment by chavdar** [comment]
I've updated the "Getting Started" wiki: https://github.com/linkedin/gobblin/wiki/Getting-Started
