### ISSUE TITLE
Gobblin Binary Releases

### ISSUE THREAD

**Issue by mark1900** [linkedin/gobblin#419]
It is great to see that Gobblin is now tagging releases (0.5.0), though I think it would be very helpful if  there were some downloadable binary releases so that I could avoid the manual build process.

https://github.com/linkedin/gobblin/releases
* https://github.com/linkedin/gobblin/archive/gobblin_0.5.0.zip ~ 1.04 MB
* https://github.com/linkedin/gobblin/archive/gobblin-gobblin_0.5.0.tar.gz ~ 488 KB

Maybe target only the Hadoop releases shown on their page (2.7.1, 2.6.1, 2.6.0, 2.5.2).  
* http://hadoop.apache.org/releases.html

I would expect a script that included something like the following:
```
./gradlew clean build -x test -PuseHadoop2 -PhadoopVersion=2.7.1
mv gobblin-dist.tar.gz ${DIST_DIR}/gobblin-0.5.0-hadoop-2.7.1-dist.tar.gz
./gradlew clean build -x test -PuseHadoop2 -PhadoopVersion=2.6.1
cp gobblin-dist.tar.gz ${DIST_DIR}/gobblin-0.5.0-hadoop-2.6.1-dist.tar.gz
./gradlew clean build -x test -PuseHadoop2 -PhadoopVersion=2.6.0
cp gobblin-dist.tar.gz ${DIST_DIR}/gobblin-0.5.0-hadoop-2.6.0-dist.tar.gz
./gradlew clean build -x test -PuseHadoop2 -PhadoopVersion=2.5.2
cp gobblin-dist.tar.gz ${DIST_DIR}/gobblin-0.5.0-hadoop-2.5.2-dist.tar.gz
```

**Comment by rsimiciuc** [comment]
+1
It would be cool if you can publish some release timelines

**Comment by chavdar** [comment]
Hi,

We've been working on setting up a upload of artifacts to Maven. In fact, we have our first test upload: https://repo1.maven.org/maven2/com/linkedin/gobblin/

We expect to have our first official release to Maven next week (12/13).

**Comment by sahilTakiar** [comment]
Jars are on Maven, check out the latest release notes: http://linkedin.github.io/gobblin/release/2016/02/01/release-0.6.2.html
