### ISSUE TITLE
Gobblin Java + Maven Support

### ISSUE THREAD

**Issue by mark1900** [linkedin/gobblin#420]
I current work in a Java + Maven development environment and found that when extending Gobblin's functionality, the build process can get a little complicated.

Below is a sample Gobblin Maven project I wrote a couple of months ago:
https://github.com/mark1900/druid-sandbox/tree/master/kafka-gobblin-hdfs-test

Some suggestions that would make my life easier.
* Sample Maven project  ( Like gobblin-example )
    * To work around this I patched the gobblin-example to discover the Maven dependencies
```
diff --git a/gobblin-example/build.gradle b/gobblin-example/build.gradle
index afcd6ea..5ccaede 100644
--- a/gobblin-example/build.gradle
+++ b/gobblin-example/build.gradle
@@ -8,6 +8,7 @@
 // under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR
 // CONDITIONS OF ANY KIND, either express or implied.
 
+apply plugin: 'maven'
 apply plugin: 'java'
 
 dependencies {
@@ -41,3 +42,14 @@
 }
 
 classification="library"
+
+task createPom << {
+    pom {
+        project {
+            groupId 'com.github.linkedin.gobblin'
+            artifactId 'gobblin-example'
+            version '0.0.1'
+            inceptionYear '2015'
+        }
+    }.writeTo("pom.xml")
+}
\ No newline at end of file
```
* It would be nice if some of the Gobblin jars ( Such as gobblin-core, gobblin-api, gobblin-metrics) lived in a public Maven repository.

**Comment by sahilTakiar** [comment]
Hey @mark1900,

We are currently working on publishing Gobblin artifacts to Maven: https://github.com/linkedin/gobblin/pull/469

**Comment by liyinan926** [comment]
@mark1900 check out the Maven artifacts at https://repo1.maven.org/maven2/com/linkedin/gobblin/.

**Comment by mark1900** [comment]
Will there be a sample project highlighting Java Maven integration?  The one example that I could find uses Gradle - https://github.com/linkedin/gobblin/tree/master/gobblin-example.

Seems the Getting Started page only referrences Gradle as well:  https://github.com/linkedin/gobblin/wiki/Getting%20Started


Also is the following the current Maven Dependency recommendation?
```
<dependency>
	<groupId>com.linkedin.gobblin</groupId>
	<artifactId>gobblin-core</artifactId>
	<version>0.6.0</version>
	<scope>compile</scope>
</dependency>

<dependency>
	<groupId>com.linkedin.gobblin</groupId>
	<artifactId>gobblin-api</artifactId>
	<version>0.6.0</version>
	<scope>compile</scope>
</dependency>

<dependency>
	<groupId>com.linkedin.gobblin</groupId>
	<artifactId>gobblin-metrics</artifactId>
	<version>0.6.0</version>
	<scope>compile</scope>
</dependency>
```

**Comment by sahilTakiar** [comment]
Artifacts are now on Maven, checkout the latest release notes: http://linkedin.github.io/gobblin/release/2016/02/01/release-0.6.2.html

Also, yes that seems the correct way of adding Maven dependency on the Gobblin jars
