### ISSUE TITLE
"JSON Records" Writer Support

### ISSUE THREAD

**Issue by mark1900** [linkedin/gobblin#424]
Currently these is no out-of-the-box support for "JSON Records" (Hadoop Splittable multi-line JSON - Not "JSON Files") as an output format, even though it is a very popular data format It would be great if this was added.

The most common Hadoop File Formats:
* http://www.inquidia.com/news-and-info/hadoop-file-formats-its-not-just-csv-anymore

See Also:
* [WriterOutputFormat](https://github.com/linkedin/gobblin/blob/master/gobblin-api/src/main/java/gobblin/writer/WriterOutputFormat.java) 
* [Gobblin Writers](https://github.com/linkedin/gobblin/tree/master/gobblin-core/src/main/java/gobblin/writer)

Related Forum post
* https://groups.google.com/forum/#!topic/gobblin-users/cGmqj4qDxak

**Comment by mark1900** [comment]
It is also worth mentioning that [WriterOutputFormat.java](https://github.com/linkedin/gobblin/blob/master/gobblin-api/src/main/java/gobblin/writer/WriterOutputFormat.java) does not support JSON.

```java
public enum WriterOutputFormat {
  AVRO("avro"),
  PARQUET("parquet"),
  PROTOBUF("protobuf"),
  ORC("orc"),
  CSV("csv");
```

**Comment by mark1900** [comment]
Some Performance Metrics of differing output formats (Avro vs Parquet vs CSV vs JSON etc):
* http://grisha.org/blog/2013/06/11/avro-performance/
* https://github.com/eishay/jvm-serializers/wiki
* https://indico.cern.ch/event/304944/session/9/contribution/43/attachments/578924/797136/chep2015-scaleout-databases.pdf

**Comment by zliu41** [comment]
See google group post https://groups.google.com/forum/#!topic/gobblin-users/cGmqj4qDxak

**Comment by mark1900** [comment]
@zliu41, I don't feel like this post has addressed this issue.  Moreover, the one possible work-around of using the AVRO WriterOutputFormat value and hacking a class to overwrite the extension to JSON, doesn't really address the lack of good built-in support for JSON Records.

A suggested work-around:
>You can just leave it blank and it will default to Avro. If you're using SimpleDataWriterBuilder this will affect the file extension but nothing else (somebody please correct me if I'm wrong). If you want to change the file extension you can write your own SimpleDataWriterBuilder and hack the extension in the constructor where it sets the filename.
>Michael

**Comment by zliu41** [comment]
Hi @mark1900 we recently made some changes to `WriterOutputFormat` in #456. Now you can set `writer.output.format=json`.

I closed this issue since there's a thread on google group so this one is considered duplicate.

**Comment by mark1900** [comment]
@zliu41 Great to see that out-of-the-box support for the .json file extension (Or any file extension) has been added to Gobblin.

Has there been any change on "JSON Records" Writer Support?

Specifically combine multiple Kafka JSON messages into one JSON file, in a way that is similar to what happens when using persisting using the Avro data format.

For instance one .json file might contain 3 records...
```
{"timestamp": "2013-08-31T01:02:33Z", "page": "Gypsy Danger", "language" : "en", "user" : "nuclear", "unpatrolled" : "true", "newPage" : "true", "robot": "false", "anonymous": "false", "namespace":"article", "continent":"North America", "country":"United States", "region":"Bay Area", "city":"San Francisco", "added": 57, "deleted": 200, "delta": -143}
{"timestamp": "2013-08-31T03:32:45Z", "page": "Striker Eureka", "language" : "en", "user" : "speed", "unpatrolled" : "false", "newPage" : "true", "robot": "true", "anonymous": "false", "namespace":"wikipedia", "continent":"Australia", "country":"Australia", "region":"Cantebury", "city":"Syndey", "added": 459, "deleted": 129, "delta": 330}
{"timestamp": "2013-08-31T07:11:21Z", "page": "Cherno Alpha", "language" : "ru", "user" : "masterYi", "unpatrolled" : "false", "newPage" : "true", "robot": "true", "anonymous": "false", "namespace":"article", "continent":"Asia", "country":"Russia", "region":"Oblast", "city":"Moscow", "added": 123, "deleted": 12, "delta": 111}
```
