### ISSUE TITLE
how  can Gobblin run on storm or spark?   

### ISSUE THREAD

**Issue by superwood** [linkedin/gobblin#427]
how  can Gobblin run on storm or spark?     Is there some plugable access to do that?

**Comment by liyinan926** [comment]
@superwood Gobblin currently is not able to run on Spark or Storm. It's possible to make Gobblin run on Spark by wrapping Gobblin `Source` and `Extractor` into something like a `GobblinInputFormat` and `GobblinInputSplit` and additionally other Gobblin operators into Spark operators.
