### ISSUE TITLE
Failure: Build failed with an exception

### ISSUE THREAD

**Issue by x10ba** [linkedin/gobblin#471]
Hi,
I can't build gobblin via gradle.

system: centos

command: ./gradlew clean build -PhadoopVersion=2.7.1 --stacktrace --debug -PuseHadoop2

Error:
20:25:01.116 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTING
20:25:01.170 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Waiting until process started: command 'git'.
20:25:01.266 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: STARTED
20:25:01.279 [DEBUG] [org.gradle.process.internal.ExecHandleRunner] waiting until streams are handled...
20:25:01.284 [INFO] [org.gradle.process.internal.DefaultExecHandle] Successfully started process 'command 'git''
20:25:01.306 [ERROR] [system.err] fatal: No names found, cannot describe anything.
20:25:01.320 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: FAILED
20:25:01.321 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command 'git'' finished with exit value 128 (state: FAILED)
20:25:01.325 [DEBUG] [org.gradle.configuration.project.BuildScriptProcessor] Timing: Running the build script took 0.677 secs
20:25:01.327 [ERROR] [org.gradle.BuildExceptionReporter] 
20:25:01.328 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
20:25:01.328 [ERROR] [org.gradle.BuildExceptionReporter] 
20:25:01.329 [ERROR] [org.gradle.BuildExceptionReporter] * Where:
20:25:01.330 [ERROR] [org.gradle.BuildExceptionReporter] Build file '~/gobblin-master/build.gradle' line: 32
20:25:01.331 [ERROR] [org.gradle.BuildExceptionReporter] 
20:25:01.331 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
20:25:01.332 [ERROR] [org.gradle.BuildExceptionReporter] A problem occurred evaluating root project 'gobblin-master'.
20:25:01.333 [ERROR] [org.gradle.BuildExceptionReporter] > Process 'command 'git'' finished with non-zero exit value 128
20:25:01.333 [ERROR] [org.gradle.BuildExceptionReporter] 
20:25:01.334 [ERROR] [org.gradle.BuildExceptionReporter] * Exception is:
20:25:01.335 [ERROR] [org.gradle.BuildExceptionReporter] org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'gobblin-master'...

**Comment by zliu41** [comment]
Please do `git fetch -t upstream master`

**Comment by liyinan926** [comment]
We just posted an announcement here https://groups.google.com/forum/#!topic/gobblin-users/8i1gaMTMSXU.

**Comment by x10ba** [comment]
That worked.
I switched from the zip version to git clone and built successfully.
