### ISSUE TITLE
Error: ./gobblin-mapreduce.sh: line 124: /hadoop: Is a directory

### ISSUE THREAD

**Issue by x10ba** [linkedin/gobblin#490]
Hi.
Hadoop Version: (horton) 2.7.1.2.3.0.0-2557
OS: Centos 7

I run this command:
$ ./gobblin-mapreduce.sh --conf /gobblin/gobblin-dist/conf/gobblin-mapreduce.properties

I get this error:
./gobblin-mapreduce.sh: line 124: /hadoop: Is a directory

This is the shell:
...
# Launch the job to run on Hadoop
$HADOOP_BIN_DIR/hadoop jar \
        $FWDIR_LIB/gobblin-runtime.jar \
        gobblin.runtime.mapreduce.CliMRJobLauncher \
        -D mapreduce.user.classpath.first=true \
        -D mapreduce.job.user.classpath.first=true \
        $JT_COMMAND \
        $FS_COMMAND \
        -libjars $LIBJARS \
        -sysconfig $GOBBLIN_CONFIG_FILE \
        -jobconfig $JOB_CONFIG_FILE

thanks,
x10ba

**Comment by ydai1124** [comment]
@x10ba Can you check your env settings of HADOOP_BIN_DIR?

**Comment by x10ba** [comment]
Hi @ydai1124 
If I have it set to
 /usr/bin: I get "no such file or directory"
or
/usr/hdp/ver: I get " /hadoop: is a directory"

(I am researching credentials, paths and versioning issues)

Thanks,
x10ba.

**Comment by ydai1124** [comment]
Hi @x10ba 
`HADOOP_BIN_DIR` should be set to the `bin` directory under your Hadoop installation directory.

**Comment by x10ba** [comment]
closing issue since relates to config/ fs
