### ISSUE TITLE
Wrong directory referenced for yarn config

### ISSUE THREAD

**Issue by kadaan** [linkedin/gobblin#495]
A recent commit (#489) changed the location of the yarn config files from /conf to /conf/yarn, but the gobblin-yarn.sh script references them at /yarn/conf.  Which one is correct?

**Comment by liyinan926** [comment]
`conf/yarn` should be the correct location.

**Comment by kadaan** [comment]
I created a PR to fix this: #496

**Comment by sahilTakiar** [comment]
Yes, this was incorrectly set in https://github.com/linkedin/gobblin/pull/489/files but was fixed in https://github.com/linkedin/gobblin/pull/492 and https://github.com/linkedin/gobblin/pull/496

I just merged https://github.com/linkedin/gobblin/pull/496
