### ISSUE TITLE
Support for publishing artifacts to repositories other than sonatype

### ISSUE THREAD

**Issue by kadaan** [linkedin/gobblin#508]
It would be good if the build supported publishing artifacts to other repositories.  If this was supported I could then develop additional libraries in an external contrib project using features that have not yet been pushed to master.  My thinking here is that we should be able to disable signing (it will be enabled by default) and override the repository and snapshotRepository (it will default to your current repository).  What do you think?

**Comment by chavdar** [comment]
Sure. That should be easy to do.

**Comment by kadaan** [comment]
I'm claiming this one.

**Comment by kadaan** [comment]
@chavdar I got publishing to artifactory working, but I noticed that the version number of the jars is a little weird.  For instance, right now the jars are published with version: 0.5.0-337-g34cf68c.  This corresponds to the tag.  Additionally it publishes to the release repository. It seems like it would be better to publish snapshot versions until there is a release.  What do you think? What is the process you normally follow?

**Comment by chavdar** [comment]
Hi,

The version is based off the most recent tag. The idea is to create a
release tag gobblin_X.Y.Z and the build will generate a build with version
X.Y.Z. If there have been commits after the tag, those cause the
"-337-g34cf68c"
part. You can override the version using -Pversion=A.B.C .

We plan to have an official release to Maven Central about every 2 weeks
(our sprint duration). The first official release should be by the end of
this week.

We haven't considered having intermediate snapshot builds and we are open
to suggestions.

Thanks.

**Comment by kadaan** [comment]
I'm not really asking for you to release snapshot builds, but for the process to support snapshot builds easily.  Given the current plan, if I pull master and build I will get a new version.  Once I upload that version to artifactory I will have to change all references to it to take advantage of the latest unreleased changes.  This will be most painful when developing libraries against gobblin master.  Supporting snapshots will mean I only have to change dependencies every 2 weeks (my sprint duration as well). 

Alternatively, I could depend on a version range.

In my case, I'm creating a company internal gobblin_contrib library.  It will contain sources, extractors, etc. that are not generic enough to commit back.  In development I want to work against gobblin master, but not have to constantly update the maven dependency.

**Comment by kadaan** [comment]
Looking at this a little more, it seems like what you are doing might be match the versioning schema for Oracle provided artifacts as described here: https://docs.oracle.com/middleware/1212/core/MAVEN/maven_version.htm#MAVEN8903

If so, maven is supposed to handle this correctly.

**Comment by kadaan** [comment]
BTW, the following version specification in maven works to correctly limit the dependency to any instance of the 0.5.0 version: `<version>[0.5.0,0.5.1)</version>`
