### ISSUE TITLE
Yarn test fail when hadoop2 is enabled and hadoopVersion is 2.3.0

### ISSUE THREAD

**Issue by kadaan** [linkedin/gobblin#511]
If you run the yarn tests when the useHadoop2 property is set, but the version is left at the default (2.3.0), then GobblinApplicationMasterTest.setUp,GobblinWorkUnitRunnerTest.setUp, and GobblinYarnAppLauncherTest.setUp fail due to:
```
java.lang.NoSuchMethodError: org.apache.hadoop.http.HttpConfig.isSecure()Z
    at org.apache.hadoop.yarn.conf.YarnConfiguration.<clinit>(YarnConfiguration.java:322)
    at gobblin.yarn.GobblinApplicationMasterTest.setUp(GobblinApplicationMasterTest.java:64)
```
and
```
java.lang.NoClassDefFoundError: Could not initialize class org.apache.hadoop.yarn.conf.YarnConfiguration
    at gobblin.yarn.GobblinWorkUnitRunnerTest.setUp(GobblinWorkUnitRunnerTest.java:69)
```
These tests pass when hadoopVersion is set to 2.6.0.

**Comment by liyinan926** [comment]
I have seen a similar issue but for a different error. It was because Hadoop jars of different version were used at runtime. I fixed is by forcing the correct version of certain jars. Checkout here https://github.com/linkedin/gobblin/pull/501/files#diff-669258ececbf7d97481e2e734c29e339.

**Comment by kadaan** [comment]
The question is
