### ISSUE TITLE
TIMESTAMP Watermark type with milliseconds

### ISSUE THREAD

**Issue by chosh0615** [linkedin/gobblin#512]
The TIMESTAMP watermark type works fine when JDBC column type is defined with format yyyy-MM-dd HH:mm:ss. However, when working with a column with timestamp with fraction of seconds, yyyy-MM-dd HH:mm:ss.ffffff for instance, some data between previous high watermark and current low watermark. 
Is there any suggestion to workaround this?

If this type of source cannot be processed yet, we suggest a new type of watermark that accepts a timestamp format yyyy-MM-dd HH:mm:ss.ffffff.
I already implemented this and tested with mysql source.
If no one else is working on this, can I make a review request?

**Comment by thedrow** [comment]
Shouldn't the TIMESTAMP type support milliseconds? I don't think that introducing another type is necessary.

**Comment by chosh0615** [comment]
TIMESTAMP type supports only upto seconds, as I mentioned above. 
I think it is necessary to create another type to support upto milliseconds(6) just like DATE or HOUR watermark type. 
The only issue is size of the watermark value. The watermark should be compatible with Long type, but yyyyMMddHHmmssffffff format is too long for Long type. In order to fit in to Long type, we need to merge two fields. For example, we can merge the year and the month fields by making it number of months from 1970/01. That format should be fit into Long type. 
The final format would be [#month from 1970/01]ddHHmmssffffff

**Comment by chosh0615** [comment]
We had added a new watermark type with name TIMESTAMP_MS few months ago and we are using it until now. 
To explain what we've done, to be clear, 
As I mentioned in the earlier comment, TIMESTAMP watermark can only take care of a watermark column with value up to second. Timestamp value with fractions of second is too large to store in 'long' type. So, we added a new watermark type that translates timestamp value with fractions of second to some long value, and vise versa.
We had to modify Partitioner, QueryBasedExtractor, JdbcExtractor, and some more classes as well.

Now we are happy to apply this feature to the develop/master branch.
Can someone verify that this work is nesseccery? 
If this modification is acceptable, please assign this job to me. Otherwise, please guide me to a correct way. 
Thank you.

**Comment by abti** [comment]
Related PR was merged
