### ISSUE TITLE
No workflow to identify content type

### ISSUE THREAD

**Issue by thedrow** [linkedin/gobblin#521]
The extractor assumes that the same formats are always received from a Source which is not always the case.
One can write a composite extractor that is able to tell in which format the message is in (JSON, Avro, Protobuf etc.) and invoke the real extractor on it. However it feels like there should be a native concept that allows us to do just that.

**Comment by sahilTakiar** [comment]
Hey @thedrow thats an interesting idea. Do you have a specific use case in mind? For us we see that most of the time the data from a `Source` is usually all in one format.

**Comment by thedrow** [comment]
Our ETL process takes configuration files from a lot of sources and parses them with augeas.
In order to do so we need to identify the type of the configuration file.
We can invoke a ruby script using https://github.com/github/linguist to do so or provide the means to do so in a Java library.
If the best solution is to create a source per configuration file type that's also fine but I still think that this feature would be useful for identifying how to parse the message.
