### ISSUE TITLE
AvroKafkaDataWriter is a stub

### ISSUE THREAD

**Issue by thedrow** [linkedin/gobblin#522]
It's good idea for feature that will allow us to perform multiple ETL runs but it's currently not implemented.
I think we should either remove it or implement it as soon as possible to avoid confusion.
Also, it makes more sense to create a generic KafkaDataWriter.

**Comment by shirshanka** [comment]
@thedrow : This is now implemented. 

See http://gobblin.readthedocs.io/en/latest/sinks/Kafka/
