### ISSUE TITLE
Private version of Apache Helix causes maven repo to be unusable

### ISSUE THREAD

**Issue by kadaan** [linkedin/gobblin#525]
The gobblin-yarn build.gradle includes a reference to an private version of helix: `compile files('./src/main/resources/helix-core-0.6.6-SNAPSHOT.jar')`.  When the gobblin libraries are pushed to maven, the private version of helix is not pushed.  Because of this, tarballs built from maven are missing the helix jar.

Is it possible to switch to the latest release or snapshot version of helix?

**Comment by liyinan926** [comment]
The local Helix jar contains critical patches that have not been merged into the trunk yet. We are working on that though.

**Comment by kadaan** [comment]
For now we are just pushing it to artifactory. Please update this when the merge to helix trunk is done.

**Comment by kadaan** [comment]
What is the status of this?

**Comment by kadaan** [comment]
@liyinan926 Can you please provide links to the PRs for the critical patches to Helix so that we can track the progress of this?

**Comment by sahilTakiar** [comment]
Here on the PRs:

https://github.com/apache/helix/pull/34
https://github.com/apache/helix/pull/35

I believe release 0.7.2 of Helix will have these changes. I don't when it will be release to Maven.
