### ISSUE TITLE
Getting ClassNotFoundException for gobblin.compaction.CompactionRunner

### ISSUE THREAD

**Issue by abhiapsunde** [linkedin/gobblin#580]
I'm following instructions to run MR compactor.

The gobblin-compaction.jar has manifest hard coded to run following class :  gobblin.compaction.CompactionRunner
I don't think this class is even present in the codebase, there is one gobblin.compaction.hive.CompactionRunner though. My understanding from the documentation is its the second type of compactor [hive]. 

Am I missing something here, about running the MR compactor. My hunch was running the jar directly should run the MR compactor.

**Comment by lbendig** [comment]
Yes, this needs to be gobblin.compaction.hive.CompactionRunner. I've created a PR to fix this.
