### ISSUE TITLE
Why is KafkaSchemaRegistry inside "gobblin-metrics" package ?

### ISSUE THREAD

**Issue by valdo404** [linkedin/gobblin#581]
Looks like the class is in the wrong package :)

**Comment by kadaan** [comment]
This does seem like the wrong place this to live.

**Comment by vasanthrajamani** [comment]
Yes, this is not the best spot for the Kafka dependencies and should be moved. 
It will be moved to a better location.

**Comment by abti** [comment]
This has moved now :)
