### ISSUE TITLE
don't find gobblin-dist.tar.gz

### ISSUE THREAD

**Issue by hellof3** [linkedin/gobblin#612]
I use the command:' ./gradlew clean build -PuseHadoop2 -PhadoopVersion=2.6.0'  and I build successful,but i didn't find the file 'gobblin-dist.tar.gz',what's the problem?

**Comment by sahilTakiar** [comment]
@hellof3 did you resolve this issue?

**Comment by hellof3** [comment]
@sahilTakiar it's my questions,because when i firstly built the project,the file 'gobblin-dist.tar.gz' was in the gobblin's root folder,but next time i changed hadoop version and rebuilt,it was gone.Finally,I found it is in the  folder -- '{GOBBLIN}/build/gobblin-distribution/ '.
