### ISSUE TITLE
How to add  subpath like YYYYMMDD/HH  to the pusher.final.dir?

### ISSUE THREAD

**Issue by superwood** [linkedin/gobblin#619]
Dump data from kafka to hdfs.  The data finally is mv to hdfs:///data/gobblin/job-output/$topicname/

How to create the final dir like hdfs:///data/gobblin/job-output/$topicname/YYYYMMDD/HH/?

configure
data.publisher.final.dir=/data/gobblin/job-output

**Comment by ibuenros** [comment]
If your data is Avro, you can use:

writer.partitioner.class=gobblin.writer.partitioner.TimeBasedAvroWriterPartitioner
writer.builder.class=gobblin.writer.AvroDataWriterBuilder
writer.partition.pattern=yyyymmdd/hh
writer.partition.columns=<the column that contains the date, e.g.
header.time>

If the data is not Avro, you'll have to write a custom partitioner for your
data. See:

https://github.com/linkedin/gobblin/wiki/Partitioned%20Writers

**Comment by sahilTakiar** [comment]
Closing, please re-open if you have more questions.
