### ISSUE TITLE
gobblin core contributors should be founders in #gobblin IRC channel

### ISSUE THREAD

**Issue by kadaan** [linkedin/gobblin#622]
At least some of the gobblin core contributors (@sahilTakiar, etc.) should be founders in the #gobblin IRC channel.  To do this you will need to follow the steps on https://meta.wikimedia.org/wiki/IRC/Instructions#Register_your_nickname_and_identify to ensure you have exclusive access to your nickname.  Then contact @kadaan and schedule a time to meet in #gobblin. @kadaan will perform the following from http://richard.esplins.org/siwi/2011/07/08/getting-started-freenode-irc/: 

```
/msg chanserv flags #gobblin <username> +*F
/msg chanserv flags #gobblin <username> -OV
```

**Comment by kadaan** [comment]
@sahilTakiar This is only as useful as you guys are willing and able to participate.  Would something like gitter (https://gitter.im/openzipkin/zipkin) be more up your alley.  It would certainly have less to learn in regards to moderation.

**Comment by abti** [comment]
@kadaan We have setup Gitter to be more realtime. I will send out an announcement later
