### ISSUE TITLE
How and Where we use the  "metadata store"

### ISSUE THREAD

**Issue by superwood** [linkedin/gobblin#625]
How and Where we use the  "metadata store" ?

**Comment by sahilTakiar** [comment]
What are you referring to when you say "metadata store"? Is there a document you read that mentions this term? Can you point us to this document so we have more context.

Off the top of my head, there are two "metadata stores" Gobblin has:
* The Gobblin `state-store`: https://github.com/linkedin/gobblin/wiki/Gobblin-Architecture#job-state-management
* The Gobblin Job History Execution store: https://github.com/linkedin/gobblin/wiki/Job%20Execution%20History%20Store

**Comment by superwood** [comment]
https://github.com/linkedin/gobblin/wiki/Gobblin-Architecture

The "metadata-store"  shows  on  "Fig. 1: Gobblin architecture overview."

**Comment by chavdar** [comment]
The metadata store is used to store state: workunits, watermarks, etc.,

**Comment by superwood** [comment]
OK. But where the "metadata store"  is used?  It is configureable?  It can be a mysql  or other storage?

**Comment by chavdar** [comment]
Have a look at gobblin.metastore.StateStore interface. Currently, there is
only one implementation -- gobblin.metastore.FsStateStore which stores the
state on HDFS.

**Comment by sahilTakiar** [comment]
Closing, please re-open if there are more questions.
