### ISSUE TITLE
Getting Started: Wikipedia example fails not finding /lib/*

### ISSUE THREAD

**Issue by rgeissen** [linkedin/gobblin#628]
I created a sucessfull gradle build of gobblin, set GOBBLIN_JOB_CONFIG_DIR, GOBBLIN_WORK_DIR and JAVA_HOME appropriately but when I start:

bin/gobblin-standalone.sh start

gobblin stops immediately and I get the following feedback:

bin/gobblin-standalone.sh start
ls: cannot access /home/osboxes/gobblin/lib/*: No such file or directory
Starting Gobblin standalone daemon
Running command:
/opt/jdk1.8.0_66/bin/java -Xmx2g -Xms1g -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintTenuringDistribution -XX:+UseCompressedOops -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/home/osboxes/gobblin/logs/ -Xloggc:/home/osboxes/gobblin/logs/gobblin-gc.log -Dgobblin.logs.dir=/home/osboxes/gobblin/logs -Dlog4j.configuration=file:///home/osboxes/gobblin/conf/log4j-standalone.xml -cp :/home/osboxes/gobblin/conf -Dorg.quartz.properties=/home/osboxes/gobblin/conf/quartz.properties  gobblin.scheduler.SchedulerDaemon /home/osboxes/gobblin/conf/gobblin-standalone.properties 
nohup: appending output to ‘nohup.out’

in the gobblin-gc.log there is the following:

Java HotSpot(TM) 64-Bit Server VM (25.66-b17) for linux-amd64 JRE (1.8.0_66-b17), built on Oct  6 2015 17:28:34 by "java_re" with gcc 4.3.0 20080428 (Red Hat 4.3.0-8)
Memory: 4k page, physical 1868692k(53900k free), swap 4063228k(705396k free)
CommandLine flags: -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/home/osboxes/gobblin/logs/ -XX:InitialHeapSize=1073741824 -XX:MaxHeapSize=2147483648 -XX:MaxNewSize=174485504 -XX:MaxTenuringThreshold=6 -XX:NewSize=174485504 -XX:OldPLABSize=16 -XX:OldSize=348971008 -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintTenuringDistribution -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+UseConcMarkSweepGC -XX:+UseParNewGC 
Heap
 par new generation   total 153344K, used 5452K [0x0000000080000000, 0x000000008a660000, 0x000000008a660000)
  eden space 136320K,   4% used [0x0000000080000000, 0x0000000080553358, 0x0000000088520000)
  from space 17024K,   0% used [0x0000000088520000, 0x0000000088520000, 0x00000000895c0000)
  to   space 17024K,   0% used [0x00000000895c0000, 0x00000000895c0000, 0x000000008a660000)
 concurrent mark-sweep generation total 878208K, used 0K [0x000000008a660000, 0x00000000c0000000, 0x0000000100000000)
 Metaspace       used 2510K, capacity 4480K, committed 4480K, reserved 1056768K
  class space    used 281K, capacity 384K, committed 384K, reserved 1048576K

Any help on how to fix this is highly appreciated!

**Comment by sthirugnanasambandam** [comment]
@rgeissen have same issue. were you able to resolve it?

➜  gobblin git:(master) bin/gobblin-standalone.sh start                     
ls: /Users/<user>/dev/gobblin/lib/*: No such file or directory
Starting Gobblin standalone daemon
Running command:
/Library/Java/JavaVirtualMachines/jdk1.8.0_66.jdk/Contents/Home/bin/java -Xmx2g -Xms1g -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintTenuringDistribution -XX:+UseCompressedOops -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/Users/<user>/dev/gobblin/logs/ -Xloggc:/Users/<user>/dev/gobblin/logs/gobblin-gc.log -Dgobblin.logs.dir=/Users/<user>/dev/gobblin/logs -Dlog4j.configuration=file:///Users/<user>/dev/gobblin/conf/log4j-standalone.xml -cp :/Users/<user>/dev/gobblin/conf -Dorg.quartz.properties=/Users/<user>/dev/gobblin/conf/quartz.properties  gobblin.scheduler.SchedulerDaemon /Users/<user>/dev/gobblin/conf/gobblin-standalone.properties 
appending output to nohup.out

**Comment by fanliukund** [comment]
why closed
