### ISSUE TITLE
Gobblin Build successfull but cannot find gobblin-dist.tar.gz

### ISSUE THREAD

**Issue by rgeissen** [linkedin/gobblin#632]
Dear Experts,

after several clean builds of gobblin I am still not able to find the "gobblin-dist.tar.gz" even though the build status states successfull. There are still warnings and errors popping up during the build, but I cant't judge if this is the reason.

The command I used is "./gradlew clean build -PuseHadoop2"

I attached stout and sterr of the Build. 
[stdout.txt](https://github.com/linkedin/gobblin/files/103270/stdout.txt)
[errout.txt](https://github.com/linkedin/gobblin/files/103271/errout.txt)

Anyone able to guide me on what I am doing wrong?

Thanks and br,
Rainer

**Comment by sahilTakiar** [comment]
Hey @rgeissen there seems to be a bug in the build. To unblock you can find the tarball under `build/gobblin-distribution/distributions/`

**Comment by rgeissen** [comment]
thanks, that worked!
