### ISSUE TITLE
MySql data extracting issue

### ISSUE THREAD

**Issue by madhukotagiri** [linkedin/gobblin#659]
Hi Iam unable to extract data and save the data in hdfs

here is the configuration and .pull files 

common.properties  :    file location(/root/Desktop/madhu/goblin/gobblinjob)
========================================================
writer.staging.dir=/root/Desktop/madhu/goblin/staging/
writer.output.dir=/root/Desktop/madhu/goblin/output/

mysql.properties :  file location(/root/Desktop/madhu/goblin/gobblinjob)
==========================================================

source.class=gobblin.source.extractor.extract.jdbc.MysqlSource

source.max.number.of.partitions=1
source.querybased.partition.interval=1
source.querybased.is.compression=true
source.querybased.watermark.type=timestamp

source.conn.driver=com.mysql.jdbc.Driver
source.conn.username=root
source.conn.password=root
source.conn.host=MY  IP IS HERE
source.conn.port=3306
source.conn.timeout=1500

converter.classes=gobblin.converter.avro.JsonIntermediateToAvroConverter

converter.avro.timestamp.format=yyyy-MM-dd HH:mm:ss'.0'
converter.avro.date.format=yyyy-MM-dd
converter.avro.time.format=HH:mm:ss

qualitychecker.task.policies=gobblin.policies.count.RowCountPolicy,gobblin.policies.schema.SchemaCompatibilityPolicy
qualitychecker.task.policy.types=OPTIONAL,OPTIONAL

data.publisher.type=gobblin.publisher.BaseDataPublisher

table_full.pull  : file location (/root/Desktop/madhu/goblin)
=====================================================

include=common.properties

job.name=GobblinMySql
job.group=MySql
job.description=Data pull from MySql

extract.table.type=snapshot_only
extract.table.name=test_sq

extract.is.full=true

source.querybased.schema=praveen_schema
source.entity=test_sq
source.querybased.extract.type=snapshot

command : 
==================================================================

bin/gobblin-standalone.sh start --workdir /root/Desktop/madhu/goblin/gobblinwork/  --conf /root/Desktop/madhu/goblin/gobblinjob/ --logdir /root/Desktop/madhu/goblin/gobblinlog/ 

nohup.out
=======================================================
=====================================================
Exception in thread "main" java.lang.NoSuchFieldError: DEFAULT_SCHEDULER_WAIT_FOR_JOB_COMPLETION
	at gobblin.scheduler.JobScheduler.<init>(JobScheduler.java:135)
	at gobblin.scheduler.SchedulerDaemon.<init>(SchedulerDaemon.java:72)
	at gobblin.scheduler.SchedulerDaemon.main(SchedulerDaemon.java:143)

gobblin-current.log
==========================================================================================================================
2016-02-03 12:44:52 IST INFO  [main] org.quartz.impl.StdSchedulerFactory  1339 - Quartz scheduler 'LocalJobScheduler' initialized from specified file: '/users/gobblin-dist/conf/quartz.properties'
2016-02-03 12:44:52 IST INFO  [main] org.quartz.impl.StdSchedulerFactory  1343 - Quartz scheduler version: 2.2.1

please let me know what iam doing mistake.  and give me a solution

**Comment by chavdar** [comment]
From the nohup.out:

Exception in thread "main" java.lang.NoSuchFieldError:
DEFAULT_SCHEDULER_WAIT_FOR_JOB_COMPLETION
at gobblin.schedule.rJobScheduler(JobScheduler.java:135)
at gobblin.scheduler.SchedulerDaemon(SchedulerDaemon.java:72)
at gobblin.scheduler.SchedulerDaemonmain(SchedulerDaemon.java:143)

This looks like a compilation/packaging issue. I suggest doing a clean
rebuild.

**Comment by madhukotagiri** [comment]
we are not doing any compilation .
just we installed in one of cluster and trying to run the mentioned command .
we are not writing any custom code just we are exceuting the 

below command:
=============

bin/gobblin-standalone.sh start --workdir /root/Desktop/madhu/goblin/gobblinwork/ --conf /root/Desktop/madhu/goblin/gobblinjob/ --logdir /root/Desktop/madhu/goblin/gobblinlog/

**Comment by sahilTakiar** [comment]
Unless you are using the Jars on Maven Central, you need to execute the following commands to run a job:

```
git clone git@github.com:linkedin/gobblin.git
cd gobblin
./gradlew clean build -PuseHadoop2 -x test
tar -xvf gobblin-distribution-0.6.2-13-g069c2ea.tar.gz
cd gobblin-dist
./bin/gobblin-standalone.sh start ...
```

**Comment by madhukotagiri** [comment]
after rebuilding we are getting 

below issues:

From the nohup.out:
=====================
Error: Could not find or load main class gobblin.scheduler.SchedulerDaemon



in the logs file:
============

/opt/gobblin-dist/logs path 
============

Java HotSpot(TM) 64-Bit Server VM (25.51-b03) for linux-amd64 JRE (1.8.0_51-b16), built on Jun  8 2015 19:28:07 by "java_re" with gcc 4.3.0 20080428 (Red Hat 4.3.0-8)
Memory: 4k page, physical 32881120k(249740k free), swap 8191996k(8164840k free)
CommandLine flags: -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/gobblin-dist/logs/ -XX:InitialHeapSize=1073741824 -XX:MaxHeapSize=2147483648 -XX:MaxNewSize=174485504 -XX:MaxTenuringThreshold=6 -XX:NewSize=174485504 -XX:OldPLABSize=16 -XX:OldSize=348971008 -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintTenuringDistribution -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+UseConcMarkSweepGC -XX:+UseParNewGC 
Heap
 par new generation   total 153344K, used 5452K [0x0000000080000000, 0x000000008a660000, 0x000000008a660000)
  eden space 136320K,   4% used [0x0000000080000000, 0x0000000080553358, 0x0000000088520000)
  from space 17024K,   0% used [0x0000000088520000, 0x0000000088520000, 0x00000000895c0000)
  to   space 17024K,   0% used [0x00000000895c0000, 0x00000000895c0000, 0x000000008a660000)
 concurrent mark-sweep generation total 878208K, used 0K [0x000000008a660000, 0x00000000c0000000, 0x0000000100000000)
 Metaspace       used 2467K, capacity 4480K, committed 4480K, reserved 1056768K
  class space    used 278K, capacity 384K, committed 384K, reserved 1048576K

**Comment by sahilTakiar** [comment]
It seems the classpath for `bin/gobblin-standalone.sh` is not set correctly. Can you add the following parameter when launching the `bin/gobblin-standalone.sh` script: `--jars /path/to/jars/`

The `/path/to/jars/` should be the absolute path to all the Gobblin jar dependencies. The jars are located under the `gobblin-dist/lib` folder after you un-tar the `gobblin-distribution-[projectVersion].tar.gz` file.

**Comment by madhukotagiri** [comment]
the above problem was resolved by rebuilding the entire code with new version

how to use this module 
https://github.com/linkedin/gobblin/tree/master/gobblin-hive-registration
to pull the data from rdbms and dump in to hive 

is there any example extractor ?

**Comment by sahilTakiar** [comment]
Closing as https://github.com/linkedin/gobblin/issues/800 has been opened to address remaining questions
