### ISSUE TITLE
Is there a way to get the sibship of datas which are processed by gobblin

### ISSUE THREAD

**Issue by superwood** [linkedin/gobblin#660]
Is there a way to get the sibship of datas which are processed by gobblin?

**Comment by chavdar** [comment]
Could you please clarify your question?

**Comment by superwood** [comment]
dataA ===>|  [gobblin--job] ===>dataC
                  |
dataB===>|


There is a ease way to show that   datac  is come from   dataA and dataB ?

**Comment by chavdar** [comment]
Currently, there is no standard way to do that (i.e. data lineage) although
we would like to work that in the (not-so-distant) future.

If I would to implement that, I would have the Source/Extract put
properties in the WorkUnit state identifying the source. Then you can
extend the publisher to emit a tracking event (
https://github.com/linkedin/gobblin/wiki/Gobblin%20Metrics%20Architecture)
with the input(s) and the output(s).
