### ISSUE TITLE
"Gobblin project version is not set!" or jars not found/do not exist

### ISSUE THREAD

**Issue by the3rdNotch** [linkedin/gobblin#662]
When running the `gobblin-mapreduce.sh` job I always receiving a `Gobblin project version is not set!` response.  If I attempt to pass a version with`--projectversion`, then I get a \<whatever>-\<projectversion>.jar does not exist or can't be found in /gobblin-dist/lib/...  
  
In `gobblin-mapreduce.sh` the variable is set:
`# Set during the distribution build`
`GOBBLIN_VERSION="0.6.2-4-g1f0109a"`  
  
There is a check for a `GOBBLIN_VERSION` further down that seems that it will always return the "Gobblin project version is not set!" response anytime an attempt in made to run the `gobblin-mapreduce.sh` job with the initial build.  
`if ( [ -z "$GOBBLIN_VERSION" ] || [ "$GOBBLIN_VERSION" == ""0.6.2-4-g1f0109a"" ] ); then`
`  die "Gobblin project version is not set!"`
`fi` 
  
Changing `[ "$GOBBLIN_VERSION" == ""0.6.2-4-g1f0109a"" ]` to `[ "$GOBBLIN_VERSION" != ""0.6.2-4-g1f0109a"" ]` resulted in the job running successfully.

**Comment by the3rdNotch** [comment]
Actually, just removing the `|| [ "$GOBBLIN_VERSION" == ""0.6.2-4-g1f0109a"" ]` seems to be a better solution.  That will still allow for other versions to be passed with `--projectversion`.

**Comment by sahilTakiar** [comment]
This seems to be a bug with the approach taken in https://github.com/linkedin/gobblin/pull/635

Sorry for the trouble. Will work on a solution to this.

**Comment by lbendig** [comment]
It is definitely ugly. I'll take care of it!
