### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by awaemmanuel** [linkedin/gobblin#666]
GLib-GIO-ERROR **: Settings schema 'org.gnome.system.proxy' is not installed

**Comment by sahilTakiar** [comment]
@awaemmanuel can you provide a little more info? The command you running? What OS you are running on? The full logs of the error would also help.

**Comment by awaemmanuel** [comment]
Hello @sahilTakiar  I use this ` ./gradlew clean build -PuseHadoop2 -PhadoopVersion=2.7.1 `

**Comment by awaemmanuel** [comment]
Ran it on Ubuntu...

**Comment by lbendig** [comment]
Which JDK do you have? Does the build succeed if you remove the 
`-Djava.net.useSystemProxies=true` flag from the javadoc settings in `build.gradle` (main project) ?
If so then I think that the Gnome system proxies are [not picked up] (https://bugs.launchpad.net/ubuntu/+bug/1199822), however according to [Java Networking and Proxies](https://docs.oracle.com/javase/7/docs/technotes/guides/net/proxies.html) one would think that it should:
> On recent Windows systems and on Gnome 2.x platforms it is possible to tell the default ProxySelector to use the system proxy settings (both recent versions of Windows and Gnome 2.x let you set proxies globally through their user interface). If the system property java.net.useSystemProxies is set to true (by default it is set to false for compatibility sake), then the default ProxySelector will try to use these settings.

Probably the proxy settings need to be added manually to `gradle.properties`
```
systemProp.http.proxyHost=host
systemProp.http.proxyPort=port
systemProp.http.proxyUser=username
systemProp.http.proxyPassword=password
```

And then we could check for their existence before passing them to the javadoc jflag options

**Comment by chavdar** [comment]
https://bugs.launchpad.net/ubuntu/+source/openjdk-7/+bug/1419026

**Comment by sahilTakiar** [comment]
Closing, please re-open if there are more issues.
