### ISSUE TITLE
JobHistory cannot be saved

### ISSUE THREAD

**Issue by kadaan** [linkedin/gobblin#678]
The job history cannot be saved to the history mysql db because the endTime is before the epoch.  This seems to be caused by a TimeZone mismatch.  The client is running as PST.  The server is running as UTC.  When the client calls setEndTime() it sets the time as '1969-12-31 16:00:01'.  This results in MySql rejecting the insert with the following error: `Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Incorrect datetime value: '1969-12-31 16:00:01' for column 'end_time' at row 1`

**Comment by kadaan** [comment]
@lbendig You were the last person to work on this specific code.  Any ideas?

**Comment by kadaan** [comment]
The fix is to specify `useLegacyDatetimeCode=false` as part of the mysql connection string.  I think this should be called out in the docs.

**Comment by lakshmanantokbox** [comment]
I am also running into this same issue.
Can you give an example on how to do this as part of mysql connection string.
Right now the example is
job.history.store.url=jdbc:mysql://localhost/gobblin

**Comment by lakshmanantokbox** [comment]
I think this works.
job.history.store.url=jdbc:mysql://localhost/gobblin?useLegacyDatetimeCode=false

**Comment by kadaan** [comment]
Thanks, I noticed this as well and it is part of my change to improve JobHistoryStore performance.
