### ISSUE TITLE
Foster a more active community by keeping track of all enhancements, issues, etc. in github

### ISSUE THREAD

**Issue by kadaan** [linkedin/gobblin#695]
The gobblin community could be grown and development paces accelerated by careful curation of github issues.  As an example, see the Presto project: https://github.com/facebook/presto/issues.  This would not only provide a good idea about the direction of gobblin, but also allow people to jump in and tackle task which may be lower priority for the linkedin team.

**Comment by sahilTakiar** [comment]
Could you expand a little more on what Presto does that you think Gobblin could learn from? Are you referring to the "labels" on the GitHub issues in Presto?

**Comment by kadaan** [comment]
The use of labels is one big thing.  Additionally, keeping track of "all" enhancement ideas in github would allow people to see what has been though about, ask questions, claim them, etc.

**Comment by kadaan** [comment]
Thanks for the labels.  That really helps.
