### ISSUE TITLE
MRJobLauncher adds jobState props to each WorkUnit

### ISSUE THREAD

**Issue by sahilTakiar** [linkedin/gobblin#696]
The following block in `MRJobLauncher` causes all `jobState` properties to be duplicated across all `WorkUnit`s

```
if (workUnit instanceof MultiWorkUnit) {
    List<WorkUnit> flattenedWorkUnits =
    JobLauncherUtils.flattenWorkUnits(((MultiWorkUnit) workUnit).getWorkUnits());
    for (WorkUnit flattenedWorkUnit : flattenedWorkUnits) {
        flattenedWorkUnit.addAllIfNotExist(this.jobState);
    }
    this.workUnits.addAll(flattenedWorkUnits);
} else {
    workUnit.addAllIfNotExist(this.jobState);
    this.workUnits.add(workUnit);
}
```

This is problematic since these `WorkUnit`s will eventually be serialized to a temp file and read into memory by the driver. The duplicate `jobState` props are not necessary and removing them can save a significant amount of memory.

The `WorkUnit` still needs access to props in the `jobState` but it shouldn't need a full copy of them. The code should be changed so that each `WorkUnit` only has a pointer to the `JobState`.

**Comment by kadaan** [comment]
I'm also removing dupes while writing the data to the history store.
