### ISSUE TITLE
Publishing fails if same named file exists

### ISSUE THREAD

**Issue by kadaan** [linkedin/gobblin#718]
If a file already exists, in the publish location, with the same name as the file being published, then the publish step will fail.  This will result in the workunit being retried on the next run of the job.  This pattern will keep repeating.

I propose that the following methods be changed to overwrite files with the same names:

1. `HadoopUtils.copy()`
1. `HadoopUtils.move()`
1. `HadoopUtils.rename()`

What do you think?

**Comment by sahilTakiar** [comment]
I think adding a parameter `boolean overwrite` would be good, so that users of this method explicitly know what behavior they are signed up for when invoking the method.

**Comment by kadaan** [comment]
If I add this, I want to add overwrite=true to the calls from BaseDataPublisher.

**Comment by sahilTakiar** [comment]
Sure, but maybe we can make it a config option for `BaseDataPublisher` if it overwrites data or not. I would prefer it to be set to false by default so that users don't accidentally overwrite data that already exists.

**Comment by kadaan** [comment]
Sure
