### ISSUE TITLE
Allow Users to Submit PRs for Documentation

### ISSUE THREAD

**Issue by sahilTakiar** [linkedin/gobblin#724]
Currently, there is no way for outside users of Gobblin to make changes to the wiki. Only the GitHub owners are allowed to do that. There should be an easy way for users to create a PR for changes to the wiki.

Relevant Links:

https://groups.google.com/forum/#!topic/gobblin-users/FuKybhhZh8M
https://github.com/linkedin/gobblin/pull/685

**Comment by sahilTakiar** [comment]
Some discussion that was done internally:

Notes on Possible Approaches:
* The GitHub wiki is also a git project, git://github.com/linkedin/gobblin.wiki.git
    * Unfortunately, you cannot fork the wiki git repo
    * It is possible to add the wiki git repo as a git submodule, but git submodules have a number of issues that make it hard to deal with
* Many projects don't use the GitHub wiki for this reason, and instead use https://pages.github.com/ to host the documentation
    * The content of this page are checked into the branch called gh-pages on GitHub
    * This is arguably more flexible than the GitHub wiki as it allows us to make more dynamic documentation using HTML, JavaScript, etc.
* Presto uses a similar approach, but most documentation is stored in rst format and then converted to html using a tool called sphinx
    * It seems that all the docs are in the main branch under presto-docs, and users submit PRs directly to these files
    * The project owners then have to manually build the docs on their own machine and then update them to the gh-pages branch

From Chavdar:

* The gh-pages supports the Markdown format of the wiki so moving the pages should not be overly hard. We should make sure that we can create PRs for the gh-pages branch.
* The main downside that I see to using gh-pages is losing the search box for wikis. Arguably, google should be able to take care of that.

**Comment by kadaan** [comment]
One thing to note is that having different branches/repos for code and documentation make it difficult to have a single PR which encompasses an entire feature (code, tests, documentation, etc).  Also, hosting docs on https://readthedocs.org would provide a searchable, version-able place to host documents.  Airflow from AirBnB is an example project which had documentation there.  You can see it at: http://airflow.readthedocs.org.  The source for the documentation is in the regular github repo: https://github.com/airbnb/airflow/tree/master/docs

**Comment by sahilTakiar** [comment]
Sphinx and readthedocs seem interesting. Although it seems Sphinx is primarily geared towards documenting Python projects (I believe Airflow is written in Python). However, there is Java integration: http://bronto.github.io/javasphinx/

**Comment by kadaan** [comment]
Yes, Airflow is python and sphinx was geared to python originally, but there are other non-python projects like Presto which use it.  It seems no less capable as far a documentation is concerned than the GitHub wiki or GitHub pages.  javasphinx seems nice for documenting java apis, but I have no experience with it.  The other proposed documentation approaches also don't handle documenting java apis.

**Comment by kadaan** [comment]
Another readthedocs example: http://docs.qubole.com/en/latest/

**Comment by sahilTakiar** [comment]
I played around this for a while last night and for most of today, and I should have a working version that uses MkDocs and readthedocs.

Some observations:
* I played around with pandoc, sphinx, mkdocs, and readthedocs
* readthedocs seems geared towards sphinx support with MkDocs support added, but not fully integrated, see https://github.com/rtfd/readthedocs.org/issues/978
* Sphinx requires `.rst`, while MkDocs uses `.md`
** Since we have been using MarkDown for a while now in the GitHub wiki I think it may be better to stick with MarkDown
** While pandoc can do the conversion, it will be hard to automate + more conversion = more bugs
* MkDocs can only use the ReadTheDocs theme, it cannot use any of the themes built for MkDocs
** While this is a limitation I think the UI still looks good and it provides all the core features we are looking for

@kadaan, any objections to using readthedocs + MkDocs

The setup will be as follows:

./mk-docs.yml
/docs/[bunch of MarkDown files]

**Comment by ibuenros** [comment]
Does mkdocs support github flavored markdown?

**Comment by sahilTakiar** [comment]
@ibuenros it seems it does not have full support for it, I believe it uses Python Markdown, although I am not sure what the difference is: https://github.com/mkdocs/mkdocs/issues/99

**Comment by sahilTakiar** [comment]
It seems to be possible though: https://github.com/google/py-gfm

Docs on what Python Markdown is: https://pythonhosted.org/Markdown/

**Comment by kadaan** [comment]
This seems great. I can't wait!

**Comment by sahilTakiar** [comment]
@kadaan no some of those features will probably not be available. However, Python Markdown provides a number of extensions that can be added that provide features like automatically created Table of Contents: http://pythonhosted.org/Markdown/extensions/

**Comment by kadaan** [comment]
This sounds like a great place to start and way better than trying to use the github wiki.

**Comment by sahilTakiar** [comment]
@liyinan926 do you have admin privileges on the GitHub Gobblin project? I want to edit the project settings but they aren't showing up for me. Can you add me?

There should be a settings tab like below:

<img width="803" alt="screen shot 2016-02-22 at 10 52 36 pm" src="https://cloud.githubusercontent.com/assets/1282583/13243908/1a352356-d9b7-11e5-9603-ad50c4c16f3c.png">

But I don't see one:

<img width="777" alt="screen shot 2016-02-22 at 10 52 26 pm" src="https://cloud.githubusercontent.com/assets/1282583/13243913/226a12d4-d9b7-11e5-8c5a-4218e5ef7fc6.png">

**Comment by liyinan926** [comment]
@sahilTakiar It seems my admin/write access has been revoked. You probably need to check with the owners of the linkedin org.

**Comment by sahilTakiar** [comment]
K thanks Yinan, will consult internally.

Initial version using ReadTheDocs and MkDocs: http://gobblin-sahiltakiar.readthedocs.org/en/readthedocs/

Still working out some formatting and build issues, need to get WebHooks setup too.

**Comment by kadaan** [comment]
Looking really good!  Any idea why the the bottom left pull-put menu isn't working?

### Gobblin
<img width="336" alt="screen shot 2016-02-22 at 11 43 56 pm" src="https://cloud.githubusercontent.com/assets/1904898/13244850/4b3d6682-d9be-11e5-92d3-4e6fb3d36d91.png">

### Airflow
<img width="403" alt="screen shot 2016-02-22 at 11 43 35 pm" src="https://cloud.githubusercontent.com/assets/1904898/13244859/5696da18-d9be-11e5-9357-b7d08b279b08.png">

**Comment by sahilTakiar** [comment]
Thanks!

I haven't pin-pointed the cause yet, but there is some JavaScript error when loading the footer:

```
Error loading Read the Docs footer
$.ajax.error @ readthedocs-doc-embed.js:1
```

**Comment by kadaan** [comment]
I see a 404 when loading:
https://readthedocs.org//api/v2/footer_html/?callback=jQuery211033368984144181013_1456216601639&project=gobblin-sahiltakiar&version=readTheDocs&page=index&theme=sphinx_rtd_theme&format=jsonp&docroot=%2Fhome%2Fdocs%2Fcheckouts%2Freadthedocs.org%2Fuser_builds%2Fgobblin-sahiltakiar%2Fcheckouts%2Freadthedocs%2Fgobblin-docs&source_suffix=.md&_=1456216601640

Whereas in airflow:
https://readthedocs.org//api/v2/footer_html/?callback=jQuery20306277235785964876_1456216654291&project=airflow&version=latest&page=index&theme=sphinx_rtd_theme&format=jsonp&docroot=%2Fdocs%2F&source_suffix=.rst&_=1456216654292

returns:
```javascript
jQuery20306277235785964876_1456216654291({
    "version_compare": {
        "project": "None",
        "version": "None",
        "is_highest": true
    },
    "promo": true,
    "version_active": true,
    "version_supported": true,
    "html": "<!-- Inserted RTD Footer -->\n<div class=\"injected\">\n\n  \n\n      \n      \n      \n      \n\n      \n      \n      <dl>\n        <dt>Downloads</dt>\n        \n        <dd><a href=\"//readthedocs.org/projects/airflow/downloads/htmlzip/latest/\">HTML</a></dd>\n        \n      </dl>\n      \n      \n\n      \n      <dl>\n        <!-- These are kept as relative links for internal installs that are http -->\n        <dt>On Read the Docs</dt>\n        <dd>\n          <a href=\"//readthedocs.org/projects/airflow/\">Project Home</a>\n        </dd>\n        <dd>\n          <a href=\"//readthedocs.org/projects/airflow/builds/\">Builds</a>\n        </dd>\n        <dd>\n          <a href=\"//readthedocs.org/projects/airflow/downloads/\">Downloads</a>\n        </dd>\n      </dl>\n      \n\n      \n\n      \n      <dl>\n        <dt>On GitHub</dt>\n        <dd>\n          <a href=\"https://github.com/airbnb/airflow/blob/master/docs/index.rst\">View</a>\n        </dd>\n        <dd>\n          <a href=\"https://github.com/airbnb/airflow/edit/master/docs/index.rst\">Edit</a>\n        </dd>\n      </dl>\n      \n      \n\n      \n      <dl>\n        <dt>Search</dt>\n        <dd>\n          <div style=\"padding: 6px;\">\n            <form id=\"flyout-search-form\" class=\"wy-form\" target=\"_blank\" action=\"https://readthedocs.org/projects/airflow/search/\" method=\"get\">\n              <input type=\"text\" name=\"q\" placeholder=\"Search docs\">\n              </form>\n          </div>\n        </dd>\n      </dl>\n      \n\n\n\n      <hr/>\n      \n      Free document hosting provided by <a href=\"https://readthedocs.org\">Read the Docs</a>. \n      \n\n      \n\n</div>\n",
    "promo_data": {
        "text": "Thanks for supporting Read the Docs!",
        "image": "",
        "link": "",
        "id": "gold-user"
    }
});
```

**Comment by sahilTakiar** [comment]
hmm I still need to investigate, there are a few outstanding issues like this I'm trying to resolve before making the PR.

**Comment by sahilTakiar** [comment]
Post Commit Webhooks work, push to the `readthedocs` branch now automatically trigger a build.

Couldn't find out why the ReadTheDocs footer is not loading so opened an issue the ReadTheDocs GitHub page: https://github.com/rtfd/readthedocs.org/issues/2015

**Comment by sahilTakiar** [comment]
Initial PR: https://github.com/linkedin/gobblin/pull/788

**Comment by sahilTakiar** [comment]
New documentation system is live: http://gobblin.readthedocs.org/en/latest/
