### ISSUE TITLE
Gobblin Yarn overwrites job start date.

### ISSUE THREAD

**Issue by kadaan** [linkedin/gobblin#734]
The `GobblinHelixJobLauncher.waitForJobCompletion()` method overwrite the job start time.  This results in all instances of the job being recorded to the history database with the same start time.

**Comment by kadaan** [comment]
<img width="799" alt="screen shot 2016-02-22 at 12 32 14 am" src="https://cloud.githubusercontent.com/assets/1904898/13213214/14b1d6ba-d8fc-11e5-88e3-0f9505c34286.png">

**Comment by sahilTakiar** [comment]
Closing as this was fixed a while ago
