### ISSUE TITLE
Gobblin Metrics race condition results in metric reporter failing to start

### ISSUE THREAD

**Issue by kadaan** [linkedin/gobblin#739]
@ibuenros There is a race condition in the Gobblin Metrics initialization of `ScheduledReporter`.  The problem is the order of the following lines:
```java
public ScheduledReporter(String name, Config config) {
    super(name, config);
    this.executor = Executors.newSingleThreadScheduledExecutor(
        ExecutorsUtils.newDaemonThreadFactory(Optional.of(log), Optional.of("metrics-" + name + "-scheduler")));
    ...
```

The following stack show the problem:

1. `ScheduledReporter.init<>()`
1. `ContextAwareReporter.init<>()`
1. `RootMetricContext.addNewReporter()`
1. `ContextAwareReporter.start()`
1. `ScheduledReporter.startImpl()`

At this point, `ScheduledReporter.startImpl()` attempts to use `this.executor` and finds that it has not been initialized.

```java
this.scheduledTask = Optional.<ScheduledFuture>of(this.executor.scheduleAtFixedRate(new Runnable() {
  @Override public void run() {
    report();
  }
}, 0, this.reportingPeriodSeconds, TimeUnit.SECONDS));
```

**Comment by sahilTakiar** [comment]
Good catch. Looks like this will only come up if `RootMetricContext.addNewReporter` is invoked after `startReporting` is invoked (because of the flag `RootMetricContext.reportingStarted`), which is probably why we have never seen this before. Should definitely be fixed because we should be able to add reporters even after reporting has started.

**Comment by sahilTakiar** [comment]
Fixed in https://github.com/linkedin/gobblin/pull/747

**Comment by sahilTakiar** [comment]
@kadaan re-opening this because #747 is causing a FindBugs warning to be triggered:

```
File: ScheduledReporter.java, Line: 109, Type: DC_DOUBLECHECK, Priority: Normal, Category: CORRECTNESS
Possible doublecheck on gobblin.metrics.reporter.ScheduledReporter.metricFilter in gobblin.metrics.reporter.ScheduledReporter.ensureMetricFilterIsInitialized(Config)

This method may contain an instance of double-checked locking.  This idiom is not correct according to the semantics of the Java memory model.  For more information, see the web page http://www.cs.umd.edu/~pugh/java/memoryModel/DoubleCheckedLocking.html.
```

I think the solution is to add `synchronized` to the method `ensureMetricFilterIsInitialized`

**Comment by sahilTakiar** [comment]
Fixed in https://github.com/linkedin/gobblin/pull/771
