### ISSUE TITLE
How to compress kafka message data to hdfs?

### ISSUE THREAD

**Issue by zhenglu696** [linkedin/gobblin#744]

**Comment by zhenglu696** [comment]
hi,now I want to get data from kafka to hdfs ,I want to konw how to compress data when put data into hdfs process.

**Comment by ibuenros** [comment]
Hi,
We currently only have uncompressed writers implemented in Gobblin. You
will probably have to extend the writer appropriate to your format (you
didn't mention the format, plaintext? avro?) to write into a compressed
file.
Issac

**Comment by zhenglu696** [comment]
hi, ibuenros;
   we log format is plaintext。
