### ISSUE TITLE
GobblinYarnAppLauncher should not stop running applications when stopped.

### ISSUE THREAD

**Issue by kadaan** [linkedin/gobblin#745]
Currently, when GobblinYarnAppLauncher is started it sets up a shutdown hook which is used as a signal to stop the underlying Yarn application when GobblinYarnAppLauncher.  However, GobblinYarnAppLauncher also has code to reconnecting to a RUNNING Yarn application.  This would allow the driver to to be independently upgraded from the application.  To accomplish this, the shutdown hook will no longer stop the running application.  A management program/script will need to be developed to allow starting/stopping the driver, with the option of stopping the underlying application and maybe a "drain" option.

@liyinan926 What do you think?

**Comment by liyinan926** [comment]
@kadaan sounds like a good idea to me.
