### ISSUE TITLE
Gobblin Yarn doesn't write job or task metrics to the JobHistoryDatabase

### ISSUE THREAD

**Issue by kadaan** [linkedin/gobblin#746]
@liyinan926 It seems as if task metrics and job metrics are not getting published to the JobHistoryDatabase when running under Gobblin Yarn.  Does the current implementation do this?  If so, what classes deal with this so that I can try to figure out why it is not working?  If not, what is the plan to make this happen?

**Comment by ydai1124** [comment]
@kadaan Did you enable these two options: `job.execinfo.server.enabled` and `job.history.store.enabled`?

**Comment by kadaan** [comment]
Yes, they are enabled. Executions/properties are getting reported.  I recently changed the DatabaseStore class, but I have verified (by debugging) that no metrics are available to be written to the database.

Here is the pertinent config:
```
# Directory where metrics log files are stored
metrics.log.dir=${gobblin.yarn.work.dir}/metrics

# Enable metrics / events
metrics.enabled=true

# Job history store
job.history.store.enabled=true
job.history.store.url="jdbc:mysql://database_server/gobblin"
job.history.store.jdbc.driver=com.mysql.jdbc.Driver
job.history.store.user="my_user"
job.history.store.password="my_password"

# Job execution info service
rest.server.host=127.0.0.1
rest.server.port=8281
rest.server.advertised.uri="https://gobblin_vip/rest"
job.execinfo.server.enabled=true

# Admin service
admin.server.enabled=true
admin.server.host=127.0.0.1
admin.server.port=8280

# Librato metrics
metrics.reporting.file.enabled=true

gobblin.metrics.reporter.librato.enabled=true
gobblin.metrics.reporter.librato.user="my@email.com"
gobblin.metrics.reporter.librato.token="my_token"
gobblin.metrics.reporter.librato.source.pattern="myserver"
gobblin.metrics.reporter.librato.filter.regex=".*"

metrics.reporting.custom.builders=com.librato.metrics.GobblinLibratoReporterFactory
```

**Comment by kadaan** [comment]
I think it is related to my fix for #739. Still investigating.

**Comment by ydai1124** [comment]
Checked my past executions, and I do see job level metrics get written to JobHistoryDatabase. But not task level metrics. Investigating.

**Comment by kadaan** [comment]
My guess is task  metrics are not reported from the containers back to the app master

**Comment by liyinan926** [comment]
@kadaan @ydai1124 yes, task metrics are not currently reported back to the app master.

**Comment by kadaan** [comment]
If they Were to be reported, how would we do it?  Via task state files?  Via new metric files?  Something else?

**Comment by kadaan** [comment]
This was broken locally by one of my changes that was fixing a different issue.  I am going to open up an issue to track reporting task metrics to the job history db.

**Comment by ydai1124** [comment]
@kadaan We are deprecating the Job/Task metrics you are using. It is better to switch to Gobblin Metrics: https://github.com/linkedin/gobblin/wiki/Gobblin%20Metrics%20Architecture. It has more contents and more stable. But we don't have the reporter to report to database yet. You can implement your own reporter: https://github.com/linkedin/gobblin/wiki/Implementing%20New%20Reporters.

**Comment by kadaan** [comment]
Hmmmm.  I don’t really want them, but there are a couple of UI elements which depend on values from the job metrics.  Can you update #748 with this information?

**Comment by ydai1124** [comment]
Just saw the newly opened one. Pasted the previous comment there.
