### ISSUE TITLE
Gobblin metrics schema registry is not compatible with Confluent schema registry

### ISSUE THREAD

**Issue by rahulmittal91** [linkedin/gobblin#765]
Hello , KafkaAvroSchemaRegistry provides a implementation where **id** is String and Confluent schema registry uses **id** as integer .
Also in KafkaAvroEventReporter the serializer that it returns is always of type AvroSerializer which I think should be injectible , as I dont want to write a new KafkaAvroEventReporter and use the same with , new implementation of SchemaRegistry

**Comment by ibuenros** [comment]
Hello,
Is there a reason you can't extend KafkaAvroSchemaRegistry to handle this
difference in id type? It could do the conversion between String and int
internally.
Also, I don't understand the issue with the AvroSerializer, it is simply
intended to serialize Avro using any avro serializer and any
SchemaVersionWriter. What are you trying to achieve that can't be achieved
through this?
Issac

**Comment by rahulmittal91** [comment]
Hi ,

There is no issue with AvroSerializer . The confusion I have is in KafkaAvroEventReporter . Here SchemaVersionWriter is always tied to SchemaRegistryVersionWriter . And I cannot change that without extending KafkaAvroEventReporter class which I dont want to .

I can extend KafkaAvroSchemaRegistry but was a bit skeptical in type safety , as I wanted to use a version of CachedSchemaRegistryClient .

**Comment by abti** [comment]
There is a ConfluentSchemaRegistry available now.
