### ISSUE TITLE
FsRenameCommitStep.execute doesn't perform same steps as ParallelRunner.movePath

### ISSUE THREAD

**Issue by kadaan** [linkedin/gobblin#781]
When exactly-once job publishing is enabled `FsRenameCommitStep` is used to ensure that the files make it to the destination.  However, it doesn't result in the same state as the method used when exactly-once job publishing is disabled: `ParallelRunner.movePath`.  The `ParallelRunner.movePath` method both moves the path and sets the group, but `FsRenameCommitStep.execute` only moves the file.
### ParallelRunner.movePath

``` java
if (fs.exists(src)) {
  HadoopUtils.movePath(fs, src, dstFs, dst, overwrite, dstFs.getConf());
  if (group.isPresent()) {
    HadoopUtils.setGroup(dstFs, dst, group.get());
  }
}
```
### FsRenameCommitStep.execute

``` java
log.info(String.format("Moving %s to %s", this.srcPath, this.dstPath));
HadoopUtils.movePath(this.srcFs, this.srcPath, this.dstFs, this.dstPath, this.dstFs.getConf());
```

**Comment by kadaan** [comment]
@zliu41 you might want to look at this one

**Comment by zliu41** [comment]
Good catch. It's an easy fix but we'll probably do some surgery to exactly-once in the next few weeks so this will be fixed as part of that.
