### ISSUE TITLE
AbstractJobLauncher leaks metrics reporters when job cannot lock

### ISSUE THREAD

**Issue by kadaan** [linkedin/gobblin#785]
@sahilTakiar AbstractJobLauncher can cause a leak of metrics reports when jobs fail to get the job lock because the metrics reporting is started, but JobException thrown when failing to get the lock causes metrics reporting to not get stopped.

```java
@Override
public void launchJob(JobListener jobListener) throws JobException {
  if (this.jobContext.getJobMetricsOptional().isPresent()) {
    this.jobContext.getJobMetricsOptional().get().startMetricReporting(this.jobProps);
  }
  try {
    if (!tryLockJob()) {
      throw new JobException(String.format("Previous instance of job %s is still running, skipping this scheduled run", this.jobContext.getJobName()));
    }
    ...
  } finally {
    try {
      ...
    } finally {
      unlockJob();
    }
  }
  ...
  // Stop metrics reporting
  if (this.jobContext.getJobMetricsOptional().isPresent()) {
    this.jobContext.getJobMetricsOptional().get().stopMetricsReporting();
    JobMetrics.remove(jobState);
  }
  ...
}
```

**Comment by sahilTakiar** [comment]
Thanks for reporting the issue, looks like a bug.

**Comment by kadaan** [comment]
@sahilTakiar There is more to it than this.  Still looking into it.

**Comment by kadaan** [comment]
@sahilTakiar This issue correctly fixes the described but, but there are a number of others which affect Gobblin on Yarn.  I will open another issue to track those.

**Comment by sahilTakiar** [comment]
Closing as #764 has been merged
