### ISSUE TITLE
I am getting gradle building issue 

### ISSUE THREAD

**Issue by madhukotagiri** [linkedin/gobblin#786]
Gradle building issue:

Parallel execution with configuration on demand is an incubating feature.
fatal: Not a git repository (or any of the parent directories): .git

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\gradle\example source\gobblin-master\build.gradle' line: 63

* What went wrong:
A problem occurred evaluating root project 'gobblin-master'.
> Process 'command 'git'' finished with non-zero exit value 128

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by zliu41** [comment]
what is in your "gobblin-master" folder? If it contains a "gobblin" folder, you need to cd to that folder to build.

**Comment by madhukotagiri** [comment]
my code directery path is: /opt/buildGobblin/gobblin

./gradlew clean build
Parallel execution with configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'gobblin'.
> Could not resolve all dependencies for configuration ':classpath'.
   > Could not resolve gradle.plugin.org.inferred:gradle-processors:1.1.2.
     Required by:
         :gobblin:unspecified
      > Could not GET 'https://plugins.gradle.org/m2/gradle/plugin/org/inferred/gradle-processors/1.1.2/gradle-processors-1.1.2.pom'.
         > peer not authenticated

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by madhukotagiri** [comment]
the error was gone getting below error:

Iam trying to build the gobblin 

**/opt/path/to/gobblin

Cd /opt/path/to/gobblin**

**./gradlew clean build**


./gradlew clean build
Parallel execution with configuration on demand is an incubating feature.
fatal: Not a git repository (or any of the parent directories): .git

FAILURE: Build failed with an exception.

* Where:
Build file '/opt/path/to/gobblin/build.gradle' line: 63

* What went wrong:
A problem occurred evaluating root project '**gobblin**'.
> Process 'command 'git'' finished with non-zero exit value 128

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**BUILD FAILED**

Total time: 1.233 secs


Please help us to resolve the issue. thank you sahil for your support

**Comment by sahilTakiar** [comment]
Try adding `-Pversion=gobblin_0.6.2-180-g5a11598` to your build command.

**Comment by madhukotagiri** [comment]
Can you explain me clear ly

**Comment by sahilTakiar** [comment]
Try running `./gradlew clean assemble -Pversion=gobblin_0.6.2-180-g5a11598`

**Comment by madhukotagiri** [comment]
works fine with above option 
thank you.
