### ISSUE TITLE
Please let me know about Gobblin below querys?

### ISSUE THREAD

**Issue by madhukotagiri** [linkedin/gobblin#800]
Hi Thank you very much for your support.

Please let me know the below questions.

1)  what is Gobblin Hive Registration.
     are you implemented equivalent schema creation of RDMS to Hive?(like sqoop in cloudera) 

2) Is Gobblin support incremental data ?
   we have created one sample configuration file  with cron job and tried with below tags
  extract.table.type=append_only , snapshot_append,simple,
   source.querybased.watermark.type=timestamp
  and manually we inserted the data in mysql 
  each and every time the gobblin extreacting entire data and writes in hdfs with diffrent folder location
for example: firsttime the folder location : xxxx/timestamp/10 records
                 inserted 2 records:
next iteration its getting entire 12 records in folder location : xxxx/timestamp/12 records (not fetching the latest 2 records)

 3) do we have option to call the gobblin from rest services.because i need to integrate in web ui project.

**Comment by sahilTakiar** [comment]
1. Are you referring to the `gobblin-hive-registration` module? It is still under active development, but it provides automatic registration of data into Hive. So everytime a dataset is published, it gets registered with the Hive metastore as an EXTERNAL table. Note this is different from directly writing data into Hive (https://cwiki.apache.org/confluence/display/Hive/LanguageManual+DDL#LanguageManualDDL-ExternalTables)

2. Yes, Gobblin does support incremental data extraction from Relational Databases. Can you please send us you full config file?

3. Do you mean launch a Gobblin job via a REST call? There currently is no service to do that, although Gobblin can be launched via [Azkaban](https://azkaban.github.io/) or [Oozie](https://oozie.apache.org/) - both provide a nice Web UI. This page has more info on how to schedule and launch Gobblin jobs: https://github.com/linkedin/gobblin/wiki/Gobblin-Schedulers

**Comment by madhukotagiri** [comment]
1) is not clear to me.
    i want to execute the gobblin job same like sqoop.
  means : a) pull the schema and along with data from rdbms 
                b)create equalent schema in hive with external table 
                c) and dump the data into hive(total 3 steps with gobblin job).

**Comment by madhukotagiri** [comment]
below is the pull file : 

#=========================================================================
# Job properties
#=========================================================================
job.name=LatestSql
job.group=LatestSql
job.description=Data pull from MySql Latest one
job.schedule=0 0/1 * * * ?
job.execinfo.server.enabled=true



job.history.store.url=jdbc:mysql://ipaddress/database
job.history.store.jdbc.driver=com.mysql.jdbc.Driver
job.history.store.user=xxxxx
job.history.store.password=xxxxx


#=========================================================================
# Source properties - source class to extract data from Mysql Source
#=========================================================================
source.querybased.schema=ecommerce_db
source.entity=customerpayment
source.querybased.extract.type=snapshot

source.class=gobblin.source.extractor.extract.jdbc.MysqlSource


source.max.number.of.partitions=1
source.querybased.partition.interval=1
source.querybased.is.compression=true
source.querybased.watermark.type=simple

#=========================================================================================================
# Source connection properties
#=========================================================================================================
source.conn.driver=com.mysql.jdbc.Driver
source.conn.username=xxx
source.conn.password=xxx
source.conn.host=ip address of host
source.conn.port=3306
source.conn.timeout=10

#=========================================================================================================
# Extract properties
#=========================================================================================================
extract.namespace=gobblin.source.extractor.extract.jdbc.MysqlExtractor
extract.table.type=append_only
extract.table.name=customerpayment
extract.delta.fields=id
extract.primary.key.fields=id

extract.is.full=true

#=========================================================================================================
# Converter properties - Record from mysql source will be processed by the below series of converters
#=========================================================================================================
converter.classes=gobblin.converter.avro.JsonIntermediateToAvroConverter
# date columns format
converter.avro.timestamp.format=yyyy-MM-dd HH:mm:ss'.0'
converter.avro.date.format=yyyy-MM-dd
converter.avro.time.format=HH:mm:ss

#=========================================================================================================
#Writer properties
#=========================================================================================================

writer.destination.type=HDFS
writer.output.format=AVRO
writer.fs.uri=hdfs://loaction
writer.part=mysql

# Qualitychecker properties
qualitychecker.task.policies=gobblin.policies.count.RowCountPolicy,gobblin.policies.schema.SchemaCompatibilityPolicy
qualitychecker.task.policy.types=OPTIONAL,OPTIONAL

#=========================================================================================================
# Publisher properties
#=========================================================================================================
data.publisher.type=gobblin.publisher.BaseDataPublisher
data.publisher.final.dir=hdfs://location
data.publisher.replace.final.dir=true


#=========================================
#restserver
#========================================
rest.server.host=IP
rest.server.port=8080
#============================================

**Comment by sahilTakiar** [comment]
* Try setting `extract.is.full` to `false`. That should trigger the incremental extract.
* To register data into Hive set `data.publisher.task.type` to `gobblin.publisher.BaseDataPublisher` and `data.publisher.job.type` to `gobblin.publisher.HiveRegistrationPublisher`
    * Depending on the output format of your data, you may need a new implementation of `HiveRegistrationPolicy`

**Comment by madhukotagiri** [comment]
already tried with extract.is.full is false but no luck

**Comment by sahilTakiar** [comment]
Can you send the logs from two consecutive executions?

**Comment by sahilTakiar** [comment]
Actually setting `source.querybased.extract.type` to `APPEND_HOURLY` should do the trick.

**Comment by madhukotagiri** [comment]
also  tried with source.querybased.extract.type to APPEND_HOURLY 

still it is extracting the entire data from rdbms.
note please the the attached log file
[2iterations log.txt](https://github.com/linkedin/gobblin/files/164576/2iterations.log.txt)

**Comment by zliu41** [comment]
@madhukotagiri you can do (1) by first extracting the data from rdbms using jdbc extractor, write the data to HDFS, and store the appropriate metadata (schema etc.) in the workunitstates; then implement an appropriate `HiveRegistrationPolicy` and use `HiveRegistrationPublisher` to register the data with hive.

**Comment by madhukotagiri** [comment]
for that i need to write custom java class right?
if yes,how do i use gobblin API?
Please Post us the custom java example project  with maven.so that any one can understand How to use the API.

Unfortunately no examples are found in the internet except GitHub.
so far i am executed just .pull property file.

**Comment by sahilTakiar** [comment]
* Seems `MySQLExtractor` only allows Watermark types `TIMESTAMP` or `DATE` - so you need to set `source.querybased.watermark.type` to `TIMESTAMP`, your current config has it set to `SIMPLE`
* Are you positive `extract.is.full` is set to `false`, please check your `.pull` and `.properties` file
    * I see the following log statement which indicates it is being set to `true` somewhere `gobblin.source.extractor.partition.Partitioner  75 - is full extract: true`

**Comment by sahilTakiar** [comment]
I believe you would only need to implement ]`HiveRegistrationPolicy`](https://github.com/linkedin/gobblin/blob/master/gobblin-hive-registration/src/main/java/gobblin/hive/policy/HiveRegistrationPolicy.java)

Some example classes that implement this interface are:

https://github.com/linkedin/gobblin/blob/master/gobblin-hive-registration/src/main/java/gobblin/hive/policy/HiveRegistrationPolicyBase.java
https://github.com/linkedin/gobblin/blob/master/gobblin-hive-registration/src/main/java/gobblin/hive/policy/HiveSnapshotRegistrationPolicy.java

**Comment by madhukotagiri** [comment]
Hi SahilTakiar

Please Let me know you available time to discuss over Skype call.
please share your Skype details to my mail id:   madhu.kotagiri007@gmail.com

**Comment by sahilTakiar** [comment]
hey @madhukotagiri i probably don't have cycles to do a skype call anytime soon, but if you have a gitter account (https://gitter.im/home) feel free to ping be directly

**Comment by madhukotagiri** [comment]
Hi Sahil,
I am scheduling multiple jobs (for example job_A, job_B, job_C, job_D, job_E,....) from the terminal. 
do we have option to stop specific job by job name ( Job_A) ?

**Comment by sahilTakiar** [comment]
@madhukotagiri how are you launching your job? in standalone or mapreduce mode?

Currently, there is no way to kill a specific job, short of killing the entire application. It would be really nice to have some type of REST API that can kill jobs, start new jobs, check the status of jobs, etc. We could then have some type of CLI that uses the API to query that status of a job.

**Comment by madhukotagiri** [comment]
Present iam launching the job from standalone mode.
Can you help me to achieve my requirement?

**Comment by sahilTakiar** [comment]
The stand-alone instance uses Quartz to schedule jobs, Gobblin currently has no integration with any Quartz UI or REST API for managing job life cycles.

Gobblin does work other schedulers though such as Oozie and Azkaban. These tools provide command line tools to kill jobs / monitor jobs, as well as nice UIs.

Take a look at http://gobblin.readthedocs.org/en/latest/user-guide/Gobblin-Schedulers/ for more info.
