### ISSUE TITLE
Partitioner not creating folder according to WriterPartitioner

### ISSUE THREAD

**Issue by krtiwari1981** [linkedin/gobblin#807]
I implemented WriterPartitioner

 assembler = assembler.name("year").type(Schema.create(Schema.Type.STRING)).noDefault();
        assembler = assembler.name("month").type(Schema.create(Schema.Type.STRING)).noDefault();
        assembler = assembler.name("day").type(Schema.create(Schema.Type.STRING)).noDefault();
        assembler = assembler.name("hour").type(Schema.create(Schema.Type.STRING)).noDefault();

--some logic 

 partition.put("year",yr);
        partition.put("month",mn);
        partition.put("day",dy);
        partition.put("hour",hr);

First the folder structure of output is 

gobblin/example/job-output/purged/page_visits/2016/03/04/01/filename

The seconds time it is year insider year 

gobblin/example/job-output/purged/page_visits/2016/2016/03/04/01/filename

and third time it fails.

Do i have to set prefix to avoid this ?

**Comment by sahilTakiar** [comment]
Can you make sure you are setting `data.publisher.job.type` to `gobblin.publisher.TimePartitionedDataPublisher`

**Comment by krtiwari1981** [comment]
Thanks so much. The issue is resolved after changing the config of data.publisher.type
to gobblin.publisher.TimePartitionedDataPublisher
