### ISSUE TITLE
Consider migration away from google-groups

### ISSUE THREAD

**Issue by sahilTakiar** [linkedin/gobblin#809]
Not a huge fan of how discussion for Gobblin is split between Google Groups and GitHub issues:
- The Google Groups integration with GitHub isn't great
- It would be nice to have a unified labeling standard so we can see what users really care about
- Agree with a lot of these comments made here: https://github.com/grafana/grafana/issues/1281

A quick googling suggests https://groups.io/ could be a good alternative.

**Comment by kadaan** [comment]
I agree something other than google groups would be better. That said, I think that having a vibrant IRC or hitter channel can be a huge benefit. Lake a look at #ansible on greener for an example.

**Comment by sahilTakiar** [comment]
Yes, Gitter looks like a solid option for adding chat; need to see how the rest of the team feels.

Still want to explore groups.io as it is also nice to have a mailing list so we can send announcements about major changes / updates to Gobblin.

**Comment by kadaan** [comment]
@sahilTakiar Thanks for considering it.  At least for me, chat could be really useful when I've found a major bug and just want to sanity check that the issue isn't just in my head.

**Comment by zliu41** [comment]
https://groups.io/ looks great at the first glance. @sahilTakiar do you want to create a group for gobblin for us to play with?

**Comment by abti** [comment]
We have setup Gitter for real time communication, and we would keep google-group alive till we incubate.

**Comment by abti** [comment]
Just to update this thread, we now have a Gitter Lobby:
https://gitter.im/gobblin/Lobby

Regards
Abhishek
