### ISSUE TITLE
Gobblin Yarn log size is unbounded

### ISSUE THREAD

**Issue by kadaan** [linkedin/gobblin#814]
The current solution for handling logs in Gobblin Yarn results in logs files which keep growing.  To handle this, we should support log rotation.  

Additionally, while looking into this, it seems like `LogCopier` may no longer be needed when running [Yarn 2.6.0](https://hadoop.apache.org/docs/r2.6.0/hadoop-yarn/hadoop-yarn-common/yarn-default.xml) or greater (`yarn.nodemanager.log-aggregation.roll-monitoring-interval-seconds`, but it might be slower than the current solution.

**Comment by liyinan926** [comment]
I believe we do have log rotation built in. @zliu41 can comment on this.

**Comment by zliu41** [comment]
There are ways to avoid a single log file to grow unboundedly (`MaxMinutesPerLogFile` and `MaxBytesPerLogFile`) but I don't think there's log rotation support.

**Comment by kadaan** [comment]
@zliu41 It looks like if either of those configuration keys are specified `LogCopier` will rotate the files in the `createNewLogFileIfNeeded()` method.
