### ISSUE TITLE
Modularize build.gradle File

### ISSUE THREAD

**Issue by sahilTakiar** [linkedin/gobblin#827]
The current `build.gradle` file is over 500 lines long and is hard to understand. We should break it down into separate `.gradle` files and use the `apply from:` command to apply them in the top-level `build.gradle` file. This will help make the build script more modular and easier to understand. For example, we can move all commands relevant to publishing artifacts to a file `gradle/scripts/publish-artifacts.gradle`

Any example of how to use `apply from:` can be found in this PR: https://github.com/linkedin/gobblin/pull/826

**Comment by kadaan** [comment]
This should help how slow that file is when editing it in Intellij Idea

**Comment by zliu41** [comment]
Also adding Eclipse support (generating the correct root `.classpath` file) with similar functionality as the `build_eclipse.py` we use internally would be helpful.
