### ISSUE TITLE
Exclude hive-exec-1.0.1.jar from gobblin-distribution.tar.gz

### ISSUE THREAD

**Issue by sahilTakiar** [linkedin/gobblin#830]
The `gobblin-distribution-[projectVersion].tar.gz` that is generated includes the `hive-exec-1.0.1.jar`, which fat jars all its dependencies, including `guava-11.0.2.jar`. This causes a lot of problems because Gobblin is dependent on `guava-15.0.jar`. This causes problems similar to https://github.com/linkedin/gobblin/issues/804

Hive provides a non-fat jar verison of `hive-exec` called `hive-exec-core-1.0.1.jar`, we have explicit dependencies on this non-fat jar version in `gobblin-compaction`, `gobblin-core`, and `gobblin-hive-registration`.

The problem is that `gobblin-compaction` has an explicit dependency on `hive-service-1.0.1.jar` which has a transitive dependency on `hive-exec-1.01.jar` (the Fat Jar version). So ultimately `hive-exec-1.0.1.jar` and `hive-exec-core-1.0.1.jar` both end up as in the tar-ball.

It seems that only Hive `gobblin-compaction` needs the `hive-service-1.0.1.jar` as a dependency, perhaps we can re-organize the code and create three submodules under `gobblin-compaction` called `gobblin-hive-compaction`, `gobblin-mr-compaction`, and `gobblin-compaction-api`. This way `gobblin-distribution` doesn't need to have a dependency on `gobblin-hive-compaction` - the module can create its own tar-ball (which I think it is doing already).

@zliu41 what do you think?

**Comment by zliu41** [comment]
I'll double check if hive-service is really needed for hive compaction because I doubt it. If it is then we can do what you suggested.

**Comment by kadaan** [comment]
If it possible to just exclude the dependency from `hive-service-1.0.1.jar` to `hive-exec-1.01.jar` and explicitly include `hive-exec-core-1.0.1.jar`?

**Comment by sahilTakiar** [comment]
It may be possible, but I couldn't find a clean way to do it. Excluding the dependency is easy, but I can't find a way to include something that has already been excluded.

**Comment by kadaan** [comment]
Can you do something like: http://stackoverflow.com/questions/30728533/gradle-override-transitive-dependency-by-version-classifier

**Comment by sahilTakiar** [comment]
Yeah that works, I created a PR: https://github.com/linkedin/gobblin/pull/832

My goal was to add the exclusion rule in `gobblin-distribution/build.gradle` so `hive-exec` would be excluded regardless of which sub-module pulls it in, but I'm not sure if thats possible.

**Comment by sahilTakiar** [comment]
Fixed in #832
