### ISSUE TITLE
TimebasedAvroPartitioner casting issue

### ISSUE THREAD

**Issue by sbjroll** [linkedin/gobblin#833]
In [TimebasedAvroPartitioner.java](https://github.com/linkedin/gobblin/blob/master/gobblin-core/src/main/java/gobblin/writer/partitioner/TimeBasedAvroWriterPartitioner.java)

`private long getRecordTimestamp(Optional<Object> writerPartitionColumnValue) {
    return writerPartitionColumnValue.orNull() instanceof Long ? (Long) writerPartitionColumnValue.get()
        : System.currentTimeMillis();
  }`

if the partitioning column is not instance of Long, it will return the currently timestamp.

It works generally, however, if there system failure for more then one "partitioning time", let's say partition by hour, then all the data from previous partitions will all goto the current partition.

In our use case, our partitioning column is type of integer. So it always picks current timestamp.

I think it's better to throw the exceptions or let the developer to do work around.

**Comment by sahilTakiar** [comment]
@sbjroll I agree that doesn't seem like the best default behavior. It may be better for the `TimeBasedAvroWriterPartitioner` to throw an exception in this case.

We can have a separate `CurrentTimeBasedWriterPartitioner` that partitions solely on the current time.

@zliu41 thoughts?

**Comment by sbjroll** [comment]
That would be great

**Comment by zliu41** [comment]
@sahilTakiar how about moving `long getRecordTimestamp(Optional<Object> writerPartitionColumnValue)` from `TimeBasedAvroWriterPartitioner` to the parent class `TimeBasedWriterPartitioner` and make it protected, so that one can override it and do whatever he wants, as long as it returns a `long`.

**Comment by sahilTakiar** [comment]
@zliu41 that sounds good to me

Can we add to the javadoc of `TimeBasedAvroWriterPartitioner` that `getRecordTimestamp` will use the current time by default? This way users don't get confused.
