### ISSUE TITLE
SimpleDataWriter should set simple.writer.prepend.size to false by default 

### ISSUE THREAD

**Issue by sahilTakiar** [linkedin/gobblin#845]
Currently, `SimpleDataWriter` sets `simple.writer.prepend.size` to `true` by default, which causes confusion for a lot of users (see links below). It may be better to set it to `false` by default.

https://groups.google.com/d/topic/gobblin-users/wBTRrTPZpSM/discussion
https://groups.google.com/d/topic/gobblin-users/bYmWyYVWCA8/discussion

@akshaynanavati are you ok with this change?

**Comment by akshaynanavati** [comment]
I think that should be okay.
