### ISSUE TITLE
Forked converters doesn't know their branch id

### ISSUE THREAD

**Issue by Zogtark** [linkedin/gobblin#848]
Been having issues with supplying my forked converters with individual settings and finally found the error. The property for the forked branch index wasn't set in the TaskState that was supplied to the forked converter.

This is from the constructor in gobblin.runtime.Fork

```
this.forkTaskState = branches > 1 ? new TaskState(this.taskState) : this.taskState;
this.taskId = this.taskState.getTaskId();

this.branches = branches;
this.index = index;

this.converter = this.closer.register(new MultiConverter(this.taskContext.getConverters(this.index, this.forkTaskState)));
this.convertedSchema = Optional.fromNullable(this.converter.convertSchema(schema, this.taskState));
```

The first row is relevant as here we create a copy of the TaskState for this specific fork. The last rows are the root of the issue. The branch index property is set through the getConverters method in this following row on the _forkTaskState_ object:
`this.converter = this.closer.register(new MultiConverter(this.taskContext.getConverters(this.index, this.forkTaskState)));`

But the forked schema conversion is supplied with the original _taskState_, and not the _forkTaskState_ which had the branch id set:
`this.convertedSchema = Optional.fromNullable(this.converter.convertSchema(schema, this.taskState));`

I don't know if this is intentional. To me it seems like a simple mistake from the coders, and that the forked convertSchema method should in fact be supplied with forkTaskState instead of the original taskState.

Edit:
The same goes for when converter.convertRecord is called in processRecords() further down in Fork.java. It is also supplied with the non-forked version of the TaskState.

**Comment by sahilTakiar** [comment]
@Zogtark yes that seems like a bug, `this.forkTaskState` should be used instead of `this.taskState` in both locations you mentioned. The fix should be simple.
