### ISSUE TITLE
Performance related statistics -- Running Slow

### ISSUE THREAD

**Issue by krtiwari1981** [linkedin/gobblin#868]
i am running gobblin in MR mode. Below are my numbers.

Hadoop cluster 1 master 4 slaves - 
each machine is 8 core 30 gb ram with processor 2.6 GHz.

Topic = 1 topic with 32 partitions 

Also I have a added my fork class and splitting into 8 branches but each record is present in only one branch and schema is in all.

case 1 
Without implementing converts and using simple data writer. 
I am processing 2 gb of data within 4.5 minutes.
cpu utilization is in 40%

case 2
After adding my converters and data writer it is taking for 2gb data 9 minutes.
cpu utilization is in 60%

From my observation the bottle neck is cpu and for better performance i need to upgrade to better machines. 

I just want to know does the above numbers makes sense and it is expected behavior  or you can point to some useful link.

**Comment by sahilTakiar** [comment]
Hey @krtiwari1981 its hard to say what the bottleneck is without getting a more detailed analysis of your job. What tools are you using to determine the CPU utilization? Can you send the full reports so we can determine which class / method is taking the most time?

It also depends on the nature of your converters, are they CPU intensive?
