### ISSUE TITLE
Source Kafka 0.9

### ISSUE THREAD

**Issue by never-summer** [linkedin/gobblin#870]
Hey,
When planned to add source for Kafka 0.9?
Thanks

**Comment by sahilTakiar** [comment]
What features in Kafka 0.9 would you like to see Gobblin integrate with?

There are plans to integrate with the new consumer (see `KafkaWrapper.KafkaNewAPI` for details, the class is not implemented, but feel free to add the implementation).

**Comment by zliu41** [comment]
There are some backward incompatible changes in kafka 0.9 (in particular the test.jar) which requires `gobblin.metrics.reporter.KafkaTestBase` (if not others) to be rewritten.
