### ISSUE TITLE
Remove current.jst from FsStateStore, add state-store retention to driver

### ISSUE THREAD

**Issue by sahilTakiar** [linkedin/gobblin#882]
- The `FsStateStore` creates and updates a `current.jst` to track the most recent version of the job state
- The problem is that for AWS users, the state-store typically has be put on S3
- The problem is that for overwriting data, S3 only provides eventual consistency
- This can cause problems as Gobblin jobs will see an old version of the state-store

A simple solution to this problem would be to:
- Remove the concept of `current.jst` and just let each state-store entry be of the form `job_id.jst`
- The gobblin just does a `ls` on the state-store directory, sorts the contents by file name and picks the most recent one
- File listing time + sorting the listing shouldn't take long, but just in case the state-store retention job should be run as part of the Gobblin core job - either in the `ApplicationLauncher` or the `JobLauncher`

**Comment by sahilTakiar** [comment]
@zliu41 I believe we discussed this briefly while working on #741, any comments on the above approach?

**Comment by zliu41** [comment]
LGTM except that if a job has multiple datasets there will be multiple `current.jst`s so you'll need to find the most recent one for each dataset urn.

**Comment by kadaan** [comment]
I've started working on this.

**Comment by lakshmanantokbox** [comment]
If the consistency is turned on in EMR,“consistent view” for EMRFS(https://blogs.aws.amazon.com/bigdata/post/Tx1WL4KR7SE37YY/Ensuring-Consistency-When-Using-Amazon-S3-and-Amazon-Elastic-MapReduce-for-ETL-W), this problem can be avoided

**Comment by kadaan** [comment]
Correct, but for those use Qubole, this is not the case.
