### ISSUE TITLE
Gradle build fails to publish due to GRADLE-2492

### ISSUE THREAD

**Issue by kadaan** [linkedin/gobblin#891]
When running the gradle build and trying to publish to the local maven repository it randomly fails due to the underlying code not being thread safe.  This is detailed in the following [discussion](https://discuss.gradle.org/t/gradle-v2-2-gradle-install-and-gradle-uploadarchive-dont-work-when-parallel-build-option-is-activated/1975/2) and [issue](https://issues.gradle.org/browse/GRADLE-2492).  There is a temporary [fix](https://github.com/gradle/gradle/blob/master/gradle/fix-GRADLE-2492.gradle) which solved my build problems locally.

**Comment by abti** [comment]
@chavdar Is this still an issue after your enhancements to build?
