### ISSUE TITLE
2 Docker ---Hadoop and gobblin

### ISSUE THREAD

**Issue by jesusvillagra** [linkedin/gobblin#900]
I want to create 2 Docker containers. One with Hadood 2.7.2 and the other one with the last Gobblin realise. But I need to Launch the job to run on Hadoop "$HADOOP_BIN_DIR/hadoop jar \" from the gobblin container. And I always recived the same message, " this isn't a file or directory". I dont Know the way to launch a command throught the containers.

**Comment by sahilTakiar** [comment]
I don't have much experience with Docker, maybe other Gobblin users have more experience. But it would be helpful if you attached your Dockerfiles to this Issue.

**Comment by jesusvillagra** [comment]
My instance of Goblin is isolated from Hadoop instance and I can not get access to Hadoop container files primary. Instead this I need to use volumes. Example:

docker run -v $HADOOP_BIN_DIR/hadoop.jar --name hadoop Hadoop
docker run --volumes-from hadoop Goblin

More information about volumes here https://docs.docker.com/engine/userguide/containers/dockervolumes/


Thanks !!!!!!!!!!!!!!!!
