### ISSUE TITLE
Gobblin Yarn doesn't clean up Helix IdealStates

### ISSUE THREAD

**Issue by kadaan** [linkedin/gobblin#925]
After running gobblin on yarn for 24 hours I noticed that the IdealStates in Zookeeper are not getting cleaned up.  I've seen the number steadily increase to 504 instance, with no signs of stopping.  This seems like a major blocker for gobblin on yarn and could unintentionally result in a issue for other services which rely on zookeeper.

**Comment by kadaan** [comment]
@liyinan926 You seems to do a lot of the work for gobblin on yarn.  What do you think?

**Comment by chavdar** [comment]
Hi,

What kind of job are you running?

**Comment by kadaan** [comment]
We are running just three jobs that pull from files in s3 and write to files in s3.

**Comment by liyinan926** [comment]
@kadaan Yes, I wrote Gobblin on Yarn. This looks like a bug in the Helix controller, which should be responsible for cleaning up ZooKeeper upon being shutdown. I would suggest filing a bug against Helix.

**Comment by kadaan** [comment]
@liyinan926 I don't really know, but wouldn't `this.helixTaskDriver.deleteJob(this.helixQueueName, this.jobContext.getJobId());` cleanup the `idealstates`?  It looks like the intent is that this is called by `GobblinHelixJobLauncher.close()`, but it only runs if the job has started and has _not_ completed.

```java
@Override
protected void executeCancellation() {
  if (this.jobSubmitted && !this.jobComplete) {
    this.helixTaskDriver.deleteJob(this.helixQueueName, this.jobContext.getJobId());
  }
}
```

**Comment by kadaan** [comment]
@liyinan926 @chavdar What do you think of my comment above?

**Comment by liyinan926** [comment]
@kadaan I am not sure deleting a job will also takes care of deleting the ideal state. Under normal circumstances, `deleteJob` won't even be called if a job completes. I still believe this is a bug with the Helix task execution framework.

**Comment by kadaan** [comment]
@liyinan926 I double checked and in Helix deleting a job cleans up the resources, which in turn cleans up the idealstates.

```java
public class TaskDriver {
  ...
  private final HelixAdmin _admin;
  ...
  /** Delete a job from an existing named queue, the queue has to be stopped prior to this call */
  public void deleteJob(final String queueName, final String jobName) {
    ...
    // delete the ideal state and resource config for the job
    _admin.dropResource(_clusterName, namespacedJobName);
    ...
  }
  ...
}

public class ZKHelixAdmin implements HelixAdmin {
  ...
  @Override
  public void dropResource(String clusterName, String resourceName) {
    HelixDataAccessor accessor =
        new ZKHelixDataAccessor(clusterName, new ZkBaseDataAccessor<ZNRecord>(_zkClient));
    Builder keyBuilder = accessor.keyBuilder();

    accessor.removeProperty(keyBuilder.idealStates(resourceName));
    accessor.removeProperty(keyBuilder.resourceConfig(resourceName));
  }
  ...
}
```

**Comment by liyinan926** [comment]
Thanks for finding out. I assume Helix should take care of deleting a completed job from the queue and clean up its ideal states.

**Comment by kadaan** [comment]
@liyinan926 I don't think this is the case.  From what it looks like in Helix when you run `enqueueJob` it creates a new ideal state.  This state doesn't get automatically cleaned up.

```java
public class TaskDriver {
  ...
  private final HelixAdmin _admin;
  ...
  public void enqueueJob(final String queueName, final String jobName, JobConfig.Builder jobBuilder) {
    ...
    // Schedule the job
    scheduleJob(namespacedJobName, jobConfig);
    ...
  }

  private void scheduleJob(String jobResource, JobConfig jobConfig) throws Exception {
    ...
    _admin.setResourceIdealState(_clusterName, jobResource, is);
    ...
  }
}

public class ZKHelixAdmin implements HelixAdmin {
  ...
  @Override
  public void setResourceIdealState(String clusterName, String resourceName, IdealState idealState) {
    ...
    accessor.setProperty(keyBuilder.idealStates(resourceName), idealState);
    ...
  }
  ...
}
```

Nothing in Helix calls `TaskDriver.deleteJob(final String queueName, final String jobName)`, so it seems like that is our responsibility.  Also, because gobblin is still using an "old" version of Helix it is hard to check what it is actually doing.

**Comment by sahilTakiar** [comment]
That sounds like a bug in Helix, but can also manually cleanup the ideal state in Gobblin until the fix in Helix is merged.

**Comment by kadaan** [comment]
Just to test I replace the `GobblinHelixJobLauncher.executeCancellation` method with: 
```java
@Override
  protected void executeCancellation() {
    if (this.jobSubmitted && !this.jobComplete) {
      this.helixTaskDriver.deleteJob(this.helixQueueName, this.jobContext.getJobId());
    }
  }
```
This seems to resolve the issue, ensuring that `idealstates` don't keep building up.

**Comment by liyinan926** [comment]
I agree that we should do it manually given how slow Helix release can be. It can be done in `close()`.

**Comment by kishoreg** [comment]
was pointed to this thread. I am dev on Helix. If I understand correctly, you are saying that job gets completed but Helix Task Driver does not delete the task from IdealState?. Can you please confirm that task is completed. Also please post this on Helix ML.

**Comment by kadaan** [comment]
@kishoreg Yes, from what I am seeing, the contents of IdealState keeps growing.  As far as I know the tasks are completed.  The workflow being performed in Gobblin is: 

### Startup
1. Create Helix Task Driver

### Run
1. Create queue using Helix Task Driver
1. Enqueue job using Helix Task Driver

### Cleanup
1. Delete job using Helix Task Driver if it has been submitted, but not completed

I'm not sure how to verify if the tasks are completed in Helix.  Changing the Cleanup code to always delete the job seems to solve the issue with the contents of IdealState constantly growing.

**Comment by kishoreg** [comment]
That helps, I will get back to you once I have more info.

**Comment by kadaan** [comment]
@liyinan926 @sahilTakiar I've been running my proposed fix for some time now and it is looking good.  What do you guys think about adopting it?

**Comment by sahilTakiar** [comment]
Sounds good to me, I believe you created a JIRA for the issue on the Helix side: HELIX-628 - can you just be sure to reference the JIRA in the code?

**Comment by kadaan** [comment]
@kishoreg Is this related to HELIX-617?

**Comment by lei-xia** [comment]
@kadaan   Before, the IdealState of a job remained even after the job is completed, but in the lastest Helix 0.6.x code, we fixed it by adding idealstate only when the job starts to run and removing idealstate immediately once the job is completed.  This should solve your issue perfectly.

If you do not want to upgrade to new version or you are using helix 0.7,  there are two options:
1) Delete the job in your code,  deleting a job will delete idealstate and job context.
2) Set up an expiry time for your job.  Helix will automatically clean up the job after expiry time.

**Comment by abti** [comment]
Closing since @kadaan's fix for this issue is merged in.
