### ISSUE TITLE
data ingestion from linux file system to hdfs using gobblin 

### ISSUE THREAD

**Issue by anujsen18** [linkedin/gobblin#939]
I want to ingest data from some linux system to hdfs.
1. files are coming on daily basis  these file could be in csv ot txt  format

Questions-
Please suggest me the suitable source,extractor,convertor and writer for filebased source 
is it possible to capture file metadata using gobblin ?

**Comment by sahilTakiar** [comment]
* Is this a simple copy job from Linux to HDFS, or do you need to do some data transformation / conversion also?
* Yes, it is possible to capture file metadata using Gobblin, what metadata are you specifically interested in?

**Comment by anujsen18** [comment]
My scenrio is :-
Myltiple files are comming in each minute.
I need to merge these similar file, remove header n footer from each file and creare a  one big file in each hour and than I want to store the same in hdfs 
I can use shell script , but i am looking for some genralized and configurable solution where i can just modify some cobfiguration .
2. Metadata like no of records file firmat,seprator,file permissions etc.

I m looking if there is some place or some class where i can create my logic and plugg in with gobblin

**Comment by sahilTakiar** [comment]
If you need to combine all the files, then you can use Gobblin but you would have to use only one thread of execution - meaning the reading of all the files would be sequential.

You would also have to write custom converters to strip the header and footer of each file.
