### ISSUE TITLE
From string to orc format?

### ISSUE THREAD

**Issue by zhuqunzhou** [linkedin/gobblin#961]
Hello,

I have my input data in string(from kafka), I have some logic in converter to modify the data, currently I am writing the output in text and everything is fine.
Now i have to modify the outputformat from string to Orc Format, are there any useful pointers, i should consider?

**Comment by zliu41** [comment]
If you are looking at converting delimited Strings into Orc, you may take a look at [HiveSerDeConverter](https://github.com/linkedin/gobblin/blob/master/gobblin-core/src/main/java/gobblin/converter/serde/HiveSerDeConverter.java). You may want to use a CSV serializer and an Orc deserializer.

**Comment by sahilTakiar** [comment]
There is now a tutorial on how to write data to ORC files: http://gobblin.readthedocs.io/en/latest/case-studies/Writing-ORC-Data/
