### ISSUE TITLE
gobblin.metastore.DatabaseJobHistoryStore is vulnerable to SQL injection

### ISSUE THREAD

**Issue by sahilTakiar** [linkedin/gobblin#969]
- The `constructTableFilter(Table table)` method in `DatabaseJobHistoryStore` is vulnerable to SQL injection; it injects a filter based on the value of  `gobblin.rest.Table` (in `gobblin-rest-api`)
- It causes the following FindBugs warning to be raised, which has been suppressed until a viable solution has been determined: `SQL_PREPARED_STATEMENT_GENERATED_FROM_NONCONSTANT_STRING`

**Comment by kadaan** [comment]
This should be simple to fix by parameterizing the filter just like is done in other places in `DatabaseJobHistoryStoreV101`
